# Generated by Django 5.1.2 on 2024-11-21 23:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralclick",
            unique_together={("page", "user", "identifier")},
        ),
    ]
