# Generated by Django 5.1.2 on 2024-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_alter_referralclick_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralclick",
            name="identifier",
            field=models.CharField(max_length=80),
        ),
    ]
