# Generated by Django 4.2.8 on 2023-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0006_evecorporationapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporationapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
