# Generated by Django 4.2.8 on 2023-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0011_evecorporationapplication_discord_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecorporationapplication",
            name="discord_thread_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
