# Generated by Django 4.2.10 on 2024-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0019_eveprimarycharacter_evecharacter_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecharacter",
            name="character_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="evecharacter",
            name="skills_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
