# Generated by Django 4.2.10 on 2024-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0021_delete_evecorporationapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecorporation",
            name="ceo_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evecorporation",
            name="member_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evecorporation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="evecorporation",
            name="ticker",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="evecorporation",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alliance", "Alliance"),
                    ("militia", "Militia"),
                    ("associate", "Associate"),
                    ("public", "Public"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
