# Generated by Django 4.2.10 on 2024-02-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("eveonline", "0023_alter_evecorporation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evealliance",
            name="executor_corporation_id",
        ),
        migrations.RemoveField(
            model_name="evecorporation",
            name="alliance_id",
        ),
        migrations.RemoveField(
            model_name="evecorporation",
            name="ceo_id",
        ),
        migrations.RemoveField(
            model_name="evecorporation",
            name="faction_id",
        ),
        migrations.AddField(
            model_name="evealliance",
            name="executor_corporation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecorporation",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="alliance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evealliance",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="ceo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveuniverse.evefaction",
            ),
        ),
    ]
