# Generated by Django 4.2.10 on 2024-02-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eveonline",
            "0024_remove_evealliance_executor_corporation_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EveSkillset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("skills", models.TextField(blank=True)),
                ("total_skill_points", models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="evecharacterskillset",
            name="name",
        ),
        migrations.RemoveField(
            model_name="evecharacterskillset",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="evecharacterskillset",
            name="total_skill_points",
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="assets_json",
            field=models.TextField(blank=True, default="{}"),
        ),
        migrations.AddField(
            model_name="evecharacterskillset",
            name="character",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evecharacter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterskillset",
            name="missing_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evecharacterskillset",
            name="progress",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EveCharacterAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("type_name", models.CharField(max_length=255)),
                ("location_id", models.BigIntegerField()),
                ("location_name", models.CharField(max_length=255)),
                ("system", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evecharacterskillset",
            name="eve_skillset",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.eveskillset",
            ),
            preserve_default=False,
        ),
    ]
