# Generated by Django 4.2.10 on 2024-02-25 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "eveonline",
            "0025_eveskillset_remove_evecharacterskillset_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evecharacterasset",
            name="region",
        ),
        migrations.RemoveField(
            model_name="evecharacterasset",
            name="system",
        ),
    ]
