# Generated by Django 4.2.10 on 2024-02-29 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0026_remove_evecharacterasset_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evecorporation",
            name="type",
        ),
    ]
