# Generated by Django 5.0.4 on 2024-04-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0030_evecharacter_alliance_evecharacter_faction"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecharacter",
            name="alliance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evealliance",
            ),
        ),
        migrations.AlterField(
            model_name="evecharacter",
            name="corporation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecorporation",
            ),
        ),
        migrations.AlterField(
            model_name="evecharacter",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveuniverse.evefaction",
            ),
        ),
    ]
