# Generated by Django 5.0.4 on 2024-05-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0033_evecharacter_exempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.IntegerField()),
                ("skill_name", models.CharField(max_length=255)),
                ("skill_points", models.IntegerField()),
                ("skill_level", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
    ]
