# Generated by Django 5.0.4 on 2024-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0034_evecharacterskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="timezones",
            field=models.TextField(blank=True),
        ),
    ]
