# Generated by Django 5.0.4 on 2024-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveonline",
            "0035_evecorporation_biography_evecorporation_introduction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecorporation",
            name="corporation_id",
            field=models.IntegerField(unique=True),
        ),
    ]
