# Generated by Django 5.0.6 on 2024-07-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveonline",
            "0038_remove_evecharacterlog_primary_character_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterKillmail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("killmail_hash", models.CharField(max_length=255)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
    ]
