# Generated by Django 5.0.6 on 2024-07-17 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0039_evecharacterkillmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="attackers",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="items",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="killmail_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="ship_type_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="solar_system_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="victim_alliance_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="victim_character_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="victim_corporation_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="victim_faction_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
