# Generated by Django 5.0.6 on 2024-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0040_evecharacterkillmail_attackers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterkillmail",
            name="killmail_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evecharacterkillmail",
            name="victim_alliance_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="evecharacterkillmail",
            name="victim_character_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="evecharacterkillmail",
            name="victim_corporation_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="evecharacterkillmail",
            name="victim_faction_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
