# Generated by Django 5.0.6 on 2024-07-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0041_evecharacterkillmail_killmail_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterKillmailAttacker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(null=True)),
                ("corporation_id", models.BigIntegerField(null=True)),
                ("alliance_id", models.BigIntegerField(null=True)),
                ("faction_id", models.BigIntegerField(null=True)),
                ("ship_type_id", models.BigIntegerField(null=True)),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacterkillmail",
                    ),
                ),
            ],
        ),
    ]
