# Generated by Django 5.1.2 on 2024-10-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esi", "0012_fix_token_type_choices"),
        ("eveonline", "0043_alter_evecharacter_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecharacter",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="esi.token",
            ),
        ),
    ]
