# Generated by Django 5.1.2 on 2025-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0044_alter_evecharacter_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="esi_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
