# Generated by Django 5.1.2 on 2025-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0045_evecharacter_esi_suspended"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterlog",
            name="added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
