# Generated by Django 5.1.2 on 2025-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0046_evecharacterlog_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="esi_token_level",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
