# Generated by Django 5.1.2 on 2025-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0050_evetag_evecharactertag"),
    ]

    operations = [
        migrations.AddField(
            model_name="evetag",
            name="image_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="evetag",
            name="title",
            field=models.CharField(default="TBC", max_length=40),
        ),
    ]
