# Generated by Django 5.1.2 on 2025-05-09 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esi", "0012_fix_token_type_choices"),
        ("eveonline", "0051_evetag_image_name_evetag_title"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="evecharacter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="unique_primary_user",
            ),
        ),
    ]
