# Generated by Django 5.1.2 on 2025-05-09 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esi", "0012_fix_token_type_choices"),
        ("eveonline", "0052_evecharacter_is_primary_and_more"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evecharacter",
            index=models.Index(
                fields=["user", "is_primary"],
                name="eveonline_e_user_id_e36f8a_idx",
            ),
        ),
    ]
