# Generated by Django 5.1.2 on 2025-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0053_evecharacter_eveonline_e_user_id_e36f8a_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evealliance",
            name="alliance_id",
            field=models.IntegerField(unique=True),
        ),
    ]
