# Generated by Django 5.1.2 on 2025-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0055_eveplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="eveplayer",
            name="prime_time",
            field=models.CharField(
                choices=[
                    ("US", "US"),
                    ("US_AP", "US / AP"),
                    ("AP", "AP"),
                    ("AP_EU", "AP / EU"),
                    ("EU", "EU"),
                    ("EU_US", "EU / US"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
