# Generated by Django 5.1.2 on 2025-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0056_eveplayer_prime_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecharacter",
            name="is_primary",
            field=models.BooleanField(help_text="Deprecated", null=True),
        ),
    ]
