# Generated by Django 5.1.2 on 2025-05-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0057_alter_evecharacter_is_primary"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evecharacter",
            name="unique_primary_user",
        ),
    ]
