# Generated by Django 5.1.2 on 2025-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0058_remove_evecharacter_unique_primary_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eveplayer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="eveplayer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
