# Generated by Django 5.1.2 on 2025-05-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0059_eveplayer_created_at_eveplayer_modified_at"),
        ("structures", "0010_alter_evestructuretimer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveLocation",
            fields=[
                (
                    "location_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("solar_system_id", models.BigIntegerField()),
                ("solar_system_name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=32)),
                ("market_active", models.BooleanField(default=False)),
                ("freight_active", models.BooleanField(default=False)),
                ("staging_active", models.BooleanField(default=False)),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.evestructure",
                    ),
                ),
            ],
        ),
    ]
