# Generated by Django 5.1.2 on 2025-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0061_alter_eveplayer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="recruitment_active",
            field=models.BooleanField(default=True),
        ),
    ]
