# Generated by Django 5.1.2 on 2025-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0062_evecorporation_recruitment_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterasset",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="evecharacterasset",
            name="location_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="evecharacterasset",
            name="type_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
