# Generated by Django 5.1.2 on 2025-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0063_evecharacterasset_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterasset",
            name="item_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
