# Generated by Django 5.1.2 on 2025-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0064_evecharacterasset_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecharacterasset",
            name="item_id",
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
