# Generated by Django 5.1.9 on 2025-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0065_alter_evecharacterasset_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evelocation",
            name="region_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
