# Generated by Django 5.2.9 on 2026-01-12 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esi", "0013_squashed_0012_fix_token_type_choices"),
        (
            "eveonline",
            "0067_evealliance_created_at_evealliance_updated_at_and_more",
        ),
        ("eveuniverse", "0011_extend_industry_activites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eveprimarycharacter",
            name="character",
        ),
        migrations.RemoveField(
            model_name="eveprimarycharacter",
            name="user",
        ),
        migrations.DeleteModel(
            name="EvePrimaryCharacterChangeLog",
        ),
        migrations.RemoveIndex(
            model_name="evecharacter",
            name="eveonline_e_user_id_e36f8a_idx",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="assets_json",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="skills_json",
        ),
        migrations.AddIndex(
            model_name="evecharacter",
            index=models.Index(
                fields=["user"], name="eveonline_e_user_id_108fd0_idx"
            ),
        ),
        migrations.DeleteModel(
            name="EvePrimaryCharacter",
        ),
    ]
