# Generated by Django 5.2.9 on 2026-01-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0068_remove_eveprimarycharacter_character_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evealliance",
            index=models.Index(
                fields=["name"], name="eveonline_e_name_44ecf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evecharacterkillmail",
            index=models.Index(
                fields=["killmail_time"], name="eveonline_e_killmai_970eb9_idx"
            ),
        ),
    ]
