# Generated by Django 5.1.2 on 2026-01-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0069_evealliance_eveonline_e_name_44ecf1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evelocation",
            name="structure",
        ),
    ]
