# Generated by Django 5.1.2 on 2026-02-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0070_remove_evelocation_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                related_name="corporation_director_of",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="recruiters",
            field=models.ManyToManyField(
                blank=True,
                related_name="corporation_recruiter_of",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="stewards",
            field=models.ManyToManyField(
                blank=True,
                related_name="corporation_steward_of",
                to="eveonline.evecharacter",
            ),
        ),
    ]
