# Generated by Django 5.1.2 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0071_evecorporation_directors_recruiters_stewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="generate_corporation_groups",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, create and sync Corp <TICKER>, Recruiter, Director, and Gunner groups.",
            ),
        ),
        migrations.AddField(
            model_name="evecorporation",
            name="gunners",
            field=models.ManyToManyField(
                blank=True,
                related_name="corporation_gunner_of",
                to="eveonline.evecharacter",
            ),
        ),
    ]
