# Generated by Django 5.1.2 on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveonline",
            "0072_evecorporation_generate_corporation_groups_gunners",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evecorporation",
            name="gunners",
        ),
    ]
