# Generated by Django 5.1.2 on 2026-02-08

from django.db import migrations, models


def copy_fk_ids_to_temp_orm(apps, schema_editor):
    """Copy EVE IDs from related corporation/alliance/faction onto temp fields."""
    EveCharacter = apps.get_model("eveonline", "EveCharacter")
    EveCorporation = apps.get_model("eveonline", "EveCorporation")
    EveAlliance = apps.get_model("eveonline", "EveAlliance")
    EveFaction = apps.get_model("eveuniverse", "EveFaction")

    for char in EveCharacter.objects.all():
        updated = False
        if char.corporation_id:  # FK column: stores EveCorporation.pk
            corp = EveCorporation.objects.filter(
                pk=char.corporation_id
            ).first()
            if corp is not None:
                char._corp_id = corp.corporation_id
                updated = True
        if char.alliance_id:
            alli = EveAlliance.objects.filter(pk=char.alliance_id).first()
            if alli is not None:
                char._alli_id = alli.alliance_id
                updated = True
        if char.faction_id:
            fact = EveFaction.objects.filter(pk=char.faction_id).first()
            if fact is not None:
                char._fact_id = fact.id
                updated = True
        if updated:
            char.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0073_remove_evecorporation_gunners"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="_corp_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="_alli_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="_fact_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_fk_ids_to_temp_orm, noop),
        migrations.RemoveField(
            model_name="evecharacter",
            name="corporation",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="alliance",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="faction",
        ),
        migrations.RenameField(
            model_name="evecharacter",
            old_name="_corp_id",
            new_name="corporation_id",
        ),
        migrations.RenameField(
            model_name="evecharacter",
            old_name="_alli_id",
            new_name="alliance_id",
        ),
        migrations.RenameField(
            model_name="evecharacter",
            old_name="_fact_id",
            new_name="faction_id",
        ),
    ]
