# Generated by Django 5.1.2 on 2026-02-08

from django.db import migrations, models


# (scope_name, group_name) – token must have scope to count as having that group
# Advanced removed: blueprints/planets/industry map into Basic+Director etc.
_SCOPE_GROUP_SIGNATURES = [
    ("publicData", "Public"),
    ("esi-fleets.read_fleet.v1", "Basic"),
    ("esi-characters.read_notifications.v1", "Director"),
    ("esi-corporations.read_corporation_membership.v1", "CEO"),
    ("esi-contracts.read_corporation_contracts.v1", "Freight"),
    ("esi-contracts.read_character_contracts.v1", "Market"),
    ("esi-mail.send_mail.v1", "Executor"),
]


def _scope_groups_from_scope_names(scope_names_list):
    """Return all scope groups the token's scopes satisfy (multiple groups)."""
    scope_set = set(scope_names_list)
    return [
        group
        for _scope, group in _SCOPE_GROUP_SIGNATURES
        if _scope in scope_set
    ]


def backfill_scope_groups(apps, schema_editor):
    """Set esi_scope_groups from token scopes or esi_token_level for existing characters."""
    EveCharacter = apps.get_model("eveonline", "EveCharacter")
    Token = apps.get_model("esi", "Token")

    for char in EveCharacter.objects.all():
        groups = []

        # Prefer inferring from the character's token if present
        token = None
        if getattr(char, "token_id", None):
            token = Token.objects.filter(pk=char.token_id).first()
        if token is None and getattr(char, "character_id", None):
            token = Token.objects.filter(character_id=char.character_id).first()

        if token:
            scope_names_list = list(
                token.scopes.values_list("name", flat=True)
            )
            if scope_names_list:
                groups = _scope_groups_from_scope_names(scope_names_list)

        # Fall back to existing esi_token_level (single group)
        if not groups and char.esi_token_level:
            groups = [char.esi_token_level.strip()]

        if groups:
            char.esi_scope_groups = groups
            char.save(update_fields=["esi_scope_groups"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0074_evecharacter_corporation_id_alliance_id_faction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="esi_scope_groups",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_scope_groups, noop),
    ]
