# Generated by Django 5.1.2 on 2026-02-08

from django.db import migrations


def migrate_advanced_to_basic(apps, schema_editor):
    """Replace Advanced with Basic in esi_scope_groups and esi_token_level."""
    EveCharacter = apps.get_model("eveonline", "EveCharacter")

    for char in EveCharacter.objects.all():
        updated = False

        if char.esi_scope_groups and "Advanced" in char.esi_scope_groups:
            new_groups = [
                "Basic" if g == "Advanced" else g
                for g in char.esi_scope_groups
            ]
            # Dedupe while preserving order (e.g. [Basic, Advanced] -> [Basic])
            seen = set()
            char.esi_scope_groups = [
                g for g in new_groups if g not in seen and not seen.add(g)
            ]
            updated = True

        if char.esi_token_level and char.esi_token_level.strip() == "Advanced":
            char.esi_token_level = "Basic"
            updated = True

        if updated:
            char.save(update_fields=["esi_scope_groups", "esi_token_level"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0075_evecharacter_esi_scope_groups"),
    ]

    operations = [
        migrations.RunPython(migrate_advanced_to_basic, noop),
    ]
