# Generated by Django 5.1.2 on 2026-02-19 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0078_add_corporation_contract_and_industry_job"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterPlanet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet_id", models.IntegerField()),
                ("planet_type", models.CharField(max_length=32)),
                ("solar_system_id", models.IntegerField()),
                ("upgrade_level", models.IntegerField(default=0)),
                ("num_pins", models.IntegerField(default=0)),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the colony was updated in-game (from ESI).",
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planets",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveCharacterPlanetOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("harvested", "Harvested"),
                            ("produced", "Produced"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="eveonline.evecharacterplanet",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="evecharacterplanet",
            index=models.Index(
                fields=["planet_id"], name="eveonline_e_planet__aab547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evecharacterplanet",
            index=models.Index(
                fields=["solar_system_id"],
                name="eveonline_e_solar_s_8ded17_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evecharacterplanet",
            unique_together={("character", "planet_id")},
        ),
        migrations.AddIndex(
            model_name="evecharacterplanetoutput",
            index=models.Index(
                fields=["eve_type"], name="eveonline_e_eve_typ_31df22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evecharacterplanetoutput",
            index=models.Index(
                fields=["output_type"], name="eveonline_e_output__cf40d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evecharacterplanetoutput",
            unique_together={("planet", "eve_type", "output_type")},
        ),
    ]
