# Generated by Django 5.1.2 on 2026-02-19 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveonline",
            "0079_evecharacterplanet_evecharacterplanetoutput_and_more",
        ),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterMiningEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.BigIntegerField()),
                ("solar_system_id", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_entries",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["eve_type"],
                        name="eveonline_e_eve_typ_231f79_idx",
                    ),
                    models.Index(
                        fields=["date"], name="eveonline_e_date_b2b4af_idx"
                    ),
                ],
                "unique_together": {
                    ("character", "eve_type", "date", "solar_system_id")
                },
            },
        ),
    ]
