# Generated by Django 5.1.2 on 2026-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0080_evecharacterminingentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveUniverseSchematic",
            fields=[
                (
                    "schematic_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("schematic_name", models.CharField(max_length=128)),
                (
                    "cycle_time",
                    models.PositiveIntegerField(
                        help_text="Time in seconds to complete one factory cycle."
                    ),
                ),
            ],
            options={
                "verbose_name": "Universe schematic (PI)",
                "verbose_name_plural": "Universe schematics (PI)",
            },
        ),
    ]
