# Generated by Django 5.1.2 on 2026-02-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0081_add_eveuniverseschematic"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterplanetoutput",
            name="daily_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated units produced or harvested per day.",
                max_digits=20,
            ),
        ),
    ]
