# Generated by Django 5.1.2 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0082_add_planet_output_daily_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharactercontract",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evecorporationcontract",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
