# Generated by Django 5.1.2

from django.db import migrations, models


def set_prices_active_from_market_active(apps, schema_editor):
    """Set prices_active = market_active for existing locations to preserve behavior."""
    EveLocation = apps.get_model("eveonline", "EveLocation")
    EveLocation.objects.filter(market_active=True).update(prices_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0083_add_contract_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="evelocation",
            name="prices_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_prices_active_from_market_active, migrations.RunPython.noop
        ),
    ]
