# Generated by Django 5.1.2 on 2026-02-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0084_evelocation_prices_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCharacterBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(db_index=True)),
                ("type_id", models.IntegerField(db_index=True)),
                ("location_id", models.BigIntegerField(db_index=True)),
                (
                    "location_flag",
                    models.CharField(db_index=True, max_length=32),
                ),
                (
                    "material_efficiency",
                    models.SmallIntegerField(
                        help_text="ME level 0-10; -1 if not researched."
                    ),
                ),
                (
                    "time_efficiency",
                    models.SmallIntegerField(
                        help_text="TE level 0-20; -1 if not researched."
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Copy count; -1 for BPO (original)."
                    ),
                ),
                (
                    "runs",
                    models.IntegerField(
                        help_text="Manufacturing runs left; -1 for BPO."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character", "type_id"],
                        name="eveonline_e_charact_306162_idx",
                    )
                ],
                "unique_together": {("character", "item_id")},
            },
        ),
        migrations.CreateModel(
            name="EveCorporationBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(db_index=True)),
                ("type_id", models.IntegerField(db_index=True)),
                ("location_id", models.BigIntegerField(db_index=True)),
                (
                    "location_flag",
                    models.CharField(db_index=True, max_length=32),
                ),
                (
                    "material_efficiency",
                    models.SmallIntegerField(
                        help_text="ME level 0-10; -1 if not researched."
                    ),
                ),
                (
                    "time_efficiency",
                    models.SmallIntegerField(
                        help_text="TE level 0-20; -1 if not researched."
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Copy count; -1 for BPO (original)."
                    ),
                ),
                (
                    "runs",
                    models.IntegerField(
                        help_text="Manufacturing runs left; -1 for BPO."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="eveonline.evecorporation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["corporation", "type_id"],
                        name="eveonline_e_corpora_796f26_idx",
                    )
                ],
                "unique_together": {("corporation", "item_id")},
            },
        ),
    ]
