# Generated by Django 5.1.2 on 2026-02-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0085_add_character_and_corporation_blueprints"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCorporationWalletJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Wallet division 1-7."
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Unique journal entry ID from ESI.",
                    ),
                ),
                ("date", models.DateTimeField(db_index=True)),
                ("ref_type", models.CharField(db_index=True, max_length=64)),
                (
                    "first_party_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "second_party_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=32, null=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=32, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("context_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "context_id_type",
                    models.CharField(blank=True, max_length=32),
                ),
                ("reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_journal_entries",
                        to="eveonline.evecorporation",
                    ),
                ),
            ],
            options={
                "verbose_name": "corporation wallet journal entry",
                "verbose_name_plural": "corporation wallet journal entries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["corporation", "ref_type"],
                        name="eveonline_e_corpora_857f41_idx",
                    ),
                    models.Index(
                        fields=["corporation", "date"],
                        name="eveonline_e_corpora_e8d44f_idx",
                    ),
                ],
                "unique_together": {("corporation", "division", "ref_id")},
            },
        ),
    ]
