# Generated by Django 5.1.2 on 2026-02-27

from django.db import migrations
from django.utils import timezone


def set_expired_status_by_date(apps, schema_editor):
    """Set status to 'expired' where date_expired is in the past but status is not."""
    EveCorporationContract = apps.get_model(
        "eveonline", "EveCorporationContract"
    )
    now = timezone.now()
    updated = EveCorporationContract.objects.filter(
        date_expired__lt=now,
        status__in=("outstanding", "in_progress"),
    ).update(status="expired")
    if updated:
        # Log would require app logger; migration runs are typically logged by caller
        pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0086_add_corporation_wallet_journal"),
    ]

    operations = [
        migrations.RunPython(set_expired_status_by_date, noop),
    ]
