# Generated by Django 5.1.2 on 2026-02-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0087_fix_corporation_contract_expired_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="evelocation",
            name="price_baseline",
            field=models.BooleanField(default=False),
        ),
    ]
