# Generated by Django 5.1.2 on 2026-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0088_evelocation_price_baseline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evelocation",
            name="price_baseline",
            field=models.BooleanField(
                default=False,
                help_text="At most one location may be the price baseline. Used as the reference for markup calculations.",
            ),
        ),
        migrations.AddConstraint(
            model_name="evelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("price_baseline", True)),
                fields=("price_baseline",),
                name="unique_price_baseline_location",
            ),
        ),
    ]
