# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0089_evelocation_unique_price_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="evelocation",
            name="is_structure",
            field=models.BooleanField(
                default=False,
                help_text="True if location_id is an Upwell structure (use structure markets API). False for NPC station (use region orders API).",
            ),
        ),
    ]
