# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterplanetoutput",
            name="extractor_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of extractor pins for this type (harvested only).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evecharacterplanetoutput",
            name="factory_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of end-result factory pins for this type (produced only).",
                null=True,
            ),
        ),
    ]
