# Generated by Django 5.1.15 on 2026-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0091_evecharacterplanetoutput_extractor_factory_count"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evelocation",
            name="unique_price_baseline_location",
        ),
        migrations.AddField(
            model_name="evelocation",
            name="deleted",
            field=models.DateTimeField(
                db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="evelocation",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="evelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("price_baseline", True), ("deleted__isnull", True)
                ),
                fields=("price_baseline",),
                name="unique_price_baseline_location",
            ),
        ),
    ]
