# Generated by Django 5.1.15 on 2026-06-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0092_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="clones_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="medical_clone_location_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="medical_clone_location_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="EveCharacterClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clone_id", models.BigIntegerField()),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("implants", models.JSONField(blank=True, default=list)),
                ("total_value_isk", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jump_clones",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character"],
                        name="eveonline_e_charact_4ac732_idx",
                    ),
                    models.Index(
                        fields=["is_active"],
                        name="eveonline_e_is_acti_eaa85a_idx",
                    ),
                ],
                "unique_together": {("character", "clone_id")},
            },
        ),
    ]
