# Generated by Django 5.1.15 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0093_evecharacter_clones_synced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="security_status",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
