# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0095_evelocation_market_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="active_implants",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
