# Generated by Django 5.2.16 on 2026-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0096_evecharacter_active_implants"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evecharacterindustryjob",
            index=models.Index(
                fields=["status", "blueprint_id"],
                name="eveonline_e_status_533f34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evecorporationindustryjob",
            index=models.Index(
                fields=["status", "blueprint_id"],
                name="eveonline_e_status_ccc75f_idx",
            ),
        ),
    ]
