# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0097_industry_job_status_blueprint_id_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evelocation",
            name="staging_active",
            field=models.BooleanField(
                default=False,
                help_text="At most one location may be the active staging system.",
            ),
        ),
        migrations.AddConstraint(
            model_name="evelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("staging_active", True), ("deleted__isnull", True)
                ),
                fields=("staging_active",),
                name="unique_active_staging_location",
            ),
        ),
    ]
