# Generated by Django 5.2.16 on 2026-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0098_unique_active_staging_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="esi_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="esi_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
