# Generated by Django 5.2.16 on 2026-07-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0099_evecharacter_esi_deleted"),
        ("eveonline", "0099_evecorporation_executor_notes"),
    ]

    operations = []
