# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0100_merge_0099_esi_deleted_executor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="trial",
            field=models.BooleanField(
                default=False,
                help_text="Whether this corporation is on trial with the alliance.",
            ),
        ),
    ]
