# Generated by Django 5.2.16 on 2026-08-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0101_evecorporation_trial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveCorporationAllianceHistorySync",
            fields=[
                (
                    "corporation_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("synced_at", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="corporation_history_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When ESI corporation history was last synced for this character.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EveCorporationAllianceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("record_id", models.IntegerField()),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="True if the alliance has been closed (ESI flag).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Eve corporation alliance histories",
                "ordering": ["-start_date", "-record_id"],
                "indexes": [
                    models.Index(
                        fields=["corporation_id", "start_date"],
                        name="eveonline_e_corpora_44b7d3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("corporation_id", "record_id"),
                        name="eveonline_corp_alliance_history_corp_record_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EveCharacterCorporationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.IntegerField(
                        help_text="ESI record_id; canonical order when start_date ties."
                    ),
                ),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("start_date", models.DateTimeField()),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="True if the corporation has been deleted (ESI flag).",
                    ),
                ),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                ("faction_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporation_history",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Eve character corporation histories",
                "ordering": ["-start_date", "-record_id"],
                "indexes": [
                    models.Index(
                        fields=["character", "start_date"],
                        name="eveonline_e_charact_9102aa_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "record_id"),
                        name="eveonline_char_corp_history_character_record_uniq",
                    )
                ],
            },
        ),
    ]
