# Generated by Django 5.2.16 on 2026-09-19 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0103_evelocation_fleets_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="FwPayoutEventCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_code",
                    models.IntegerField(db_index=True, unique=True),
                ),
                (
                    "site_kind",
                    models.CharField(
                        default="unknown",
                        help_text="Matches campaigns.models.SiteKind values.",
                        max_length=24,
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "amount_rule",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How the LP amount is derived, for humans.",
                        max_length=128,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Unconfirmed codes are never scored.",
                    ),
                ),
                (
                    "confirmed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "FW payout event code",
                "ordering": ["event_code"],
            },
        ),
        migrations.CreateModel(
            name="EveCharacterFwLpPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("notification_type", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("amount_lp", models.IntegerField(default=0)),
                ("corp_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "event_code",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "location_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Solar system id.",
                        null=True,
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="itemRefID: the site instance for a complex, or the killmail id for a kill payout.",
                        null=True,
                    ),
                ),
                ("char_ref_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "disqualification_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("raw_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fw_lp_payouts",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "verbose_name": "FW LP payout",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["character", "-occurred_at"],
                        name="eveonline_e_charact_e01be2_idx",
                    ),
                    models.Index(
                        fields=["location_id", "-occurred_at"],
                        name="eveonline_e_locatio_65e9a0_idx",
                    ),
                    models.Index(
                        fields=["event_code", "ref_id"],
                        name="eveonline_e_event_c_3b5f62_idx",
                    ),
                ],
            },
        ),
    ]
