# Generated by Django 5.1.15 on 2026-06-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0094_evecharacter_security_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveAccessList",
            fields=[
                (
                    "access_list_id",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Access list ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("allow_everyone", models.BooleanField(default=False)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "owner_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_lists",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access list",
                "verbose_name_plural": "Access lists",
            },
        ),
        migrations.CreateModel(
            name="EveAccessListMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("corporation", "Corporation"),
                            ("alliance", "Alliance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("entity_name", models.CharField(blank=True, max_length=255)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("Blocked", "Blocked"),
                            ("Allowed", "Allowed"),
                            ("Manager", "Manager"),
                            ("Admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "access_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="access_lists.eveaccesslist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access list member",
                "verbose_name_plural": "Access list members",
            },
        ),
        migrations.AddIndex(
            model_name="eveaccesslist",
            index=models.Index(
                fields=["name"], name="access_list_name_6b157c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eveaccesslist",
            index=models.Index(
                fields=["owner_character"],
                name="access_list_owner_c_984587_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eveaccesslistmember",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="access_list_entity__bc6b81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eveaccesslistmember",
            index=models.Index(
                fields=["access"], name="access_list_access_001e30_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eveaccesslistmember",
            constraint=models.UniqueConstraint(
                fields=("access_list", "entity_type", "entity_id"),
                name="access_lists_unique_member",
            ),
        ),
    ]
