# Generated by Django 5.1.2 on 2024-12-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combatlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatlog",
            name="character_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="combatlog",
            name="solar_system_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
