# Generated by Django 5.1.9 on 2025-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "combatlog",
            "0002_combatlog_character_name_combatlog_solar_system_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="combatlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
