# Generated by Django 4.2.8 on 2023-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0010_alter_evecorporation_alliance_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporationapplication",
            name="discord_thread_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
