# Generated by Django 5.2.16 on 2026-07-31 21:45

from django.db import migrations, models

CONSTRAINT_NAME = "uniq_notif_delivery_idem_channel"
TABLE_NAME = "notifications_notificationdelivery"


def _drop_idem_constraint_if_exists(apps, schema_editor):
    """
    Partial unique constraints are skipped on MySQL, so 0001 may never have
    created this index. Drop only when present, then 0003 re-adds unconditional.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "mysql":
            cursor.execute(
                """
                SELECT 1 FROM information_schema.statistics
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND index_name = %s
                LIMIT 1
                """,
                [TABLE_NAME, CONSTRAINT_NAME],
            )
            if cursor.fetchone():
                cursor.execute(
                    f"ALTER TABLE {TABLE_NAME} DROP INDEX `{CONSTRAINT_NAME}`"
                )
        elif connection.vendor == "postgresql":
            cursor.execute(
                f"ALTER TABLE {TABLE_NAME} "
                f"DROP CONSTRAINT IF EXISTS {CONSTRAINT_NAME}"
            )
        elif connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA index_list('{TABLE_NAME}')")
            names = {row[1] for row in cursor.fetchall()}
            if CONSTRAINT_NAME in names:
                cursor.execute(f"DROP INDEX IF EXISTS {CONSTRAINT_NAME}")


def _add_idem_constraint(apps, schema_editor):
    NotificationDelivery = apps.get_model(
        "notifications", "NotificationDelivery"
    )
    constraint = models.UniqueConstraint(
        fields=["idempotency_key", "channel"],
        name=CONSTRAINT_NAME,
    )
    schema_editor.add_constraint(NotificationDelivery, constraint)


def _remove_idem_constraint(apps, schema_editor):
    NotificationDelivery = apps.get_model(
        "notifications", "NotificationDelivery"
    )
    constraint = models.UniqueConstraint(
        fields=["idempotency_key", "channel"],
        name=CONSTRAINT_NAME,
    )
    schema_editor.remove_constraint(NotificationDelivery, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_delivery_read_discord_ids"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="notificationdelivery",
                    name=CONSTRAINT_NAME,
                ),
                migrations.AddConstraint(
                    model_name="notificationdelivery",
                    constraint=models.UniqueConstraint(
                        fields=("idempotency_key", "channel"),
                        name=CONSTRAINT_NAME,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _drop_idem_constraint_if_exists,
                    migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    _add_idem_constraint,
                    _remove_idem_constraint,
                ),
            ],
        ),
    ]
