services:
    app:
        build:
            context: ./backend/.
            dockerfile: Dockerfile.dev
        working_dir: /opt/minmatar
        command: ./dev-start.sh
        env_file:
            - ./backend/standalone.env
        networks:
          - local-network
        ports:
            - "8000:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backend:/opt/minmatar
    frontend:
      build:
          context: ./frontend/
          dockerfile: Dockerfile
      depends_on:
          - app
      env_file:
          - frontend/standalone.env
      networks:
          - local-network
      ports:
          - "4321:4321"
      volumes:
          - "./frontend/app/src/data:/app/src/data"

networks:
    local-network:

volumes:
    backend-src: