# Generated by Django 5.0.4 on 2024-04-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fleets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetnotificationchannel",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="evefleet",
            name="audience",
        ),
        migrations.AddField(
            model_name="evefleet",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
            ),
        ),
    ]
