# Generated by Django 5.0.4 on 2024-05-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0003_evefleet_location_id_alter_evefleet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetnotificationchannel",
            name="webhook_url",
            field=models.CharField(
                default="https://discord.com/api/webhooks/1127086536375148615/t9sca8Xm9MY_gauPxfnw7sgdl23JJVlZR3p4AZuTbETGid5dE3jBjoy5Ei1xipysqX8k",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
