# Generated by Django 5.0.4 on 2024-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0004_evefleetnotificationchannel_webhook_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefleetinstancemember",
            name="character",
        ),
        migrations.AddField(
            model_name="evefleetinstancemember",
            name="character_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetinstancemember",
            name="character_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetinstancemember",
            name="ship_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetinstancemember",
            name="solar_system_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
