# Generated by Django 5.0.4 on 2024-05-22 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0005_remove_evefleetinstancemember_character_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveStandingFleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("last_commander_change", models.DateTimeField(auto_now=True)),
                ("external_fleet_id", models.BigIntegerField()),
                (
                    "active_fleet_commander_character_id",
                    models.BigIntegerField(),
                ),
                (
                    "active_fleet_commander_character_name",
                    models.CharField(max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveStandingFleetCommanderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                (
                    "eve_standing_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleets.evestandingfleet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveStandingFleetMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                (
                    "eve_standing_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleets.evestandingfleet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveStandingFleetMemberLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                (
                    "eve_standing_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleets.evestandingfleet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EveFleetNotification",
        ),
    ]
