# Generated by Django 5.0.4 on 2024-05-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0008_remove_evefleet_location_id_alter_evefleet_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefleet",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fleets.evefleetlocation",
            ),
        ),
        migrations.AlterField(
            model_name="evefleetinstancemember",
            name="squad_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="evefleetinstancemember",
            name="wing_id",
            field=models.BigIntegerField(),
        ),
    ]
