# Generated by Django 5.0.4 on 2024-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0009_alter_evefleet_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetlocation",
            name="solar_system_id",
            field=models.BigIntegerField(default=30003070),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetlocation",
            name="solar_system_name",
            field=models.CharField(default="Sosala", max_length=255),
            preserve_default=False,
        ),
    ]
