# Generated by Django 5.0.4 on 2024-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0010_evefleetlocation_solar_system_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefleet",
            name="type",
            field=models.CharField(
                choices=[
                    ("strategic", "Strategic Operation"),
                    ("non_strategic", "Non Strategic Operation"),
                    ("training", "Training Operation"),
                ],
                max_length=32,
            ),
        ),
    ]
