# Generated by Django 5.0.4 on 2024-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fleets", "0011_alter_evefleet_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "discord_channel_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "discord_channel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "webhook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(blank=True, to="auth.group"),
                ),
            ],
        ),
    ]
