# Generated by Django 5.0.4 on 2024-05-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0012_evefleetaudience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefleetaudience",
            name="webhook_url",
        ),
        migrations.AlterField(
            model_name="evefleet",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fleets.evefleetaudience",
            ),
        ),
    ]
