# Generated by Django 5.0.6 on 2024-06-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0013_remove_evefleetaudience_webhook_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EveFleetNotificationChannel",
        ),
    ]
