# Generated by Django 5.0.6 on 2024-06-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0014_delete_evefleetnotificationchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetaudience",
            name="discord_voice_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="EveFleetAudienceWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_url", models.CharField(max_length=255)),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleets.evefleetaudience",
                    ),
                ),
            ],
        ),
    ]
