# Generated by Django 5.0.6 on 2024-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0015_evefleetaudience_discord_voice_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetaudience",
            name="discord_voice_channel_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
