# Generated by Django 5.0.8 on 2024-09-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0016_evefleetaudience_discord_voice_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="disable_motd",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
