# Generated by Django 5.1.2 on 2024-11-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0017_evefleet_disable_motd"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetShipReimbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_killmail_link", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("killmail_id", models.BigIntegerField()),
                ("character_id", models.BigIntegerField()),
                ("primary_character_id", models.BigIntegerField()),
                ("amount", models.BigIntegerField()),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fleets.evefleet",
                    ),
                ),
            ],
        ),
    ]
