# Generated by Django 5.1.2 on 2024-11-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0018_evefleetshipreimbursement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EveFleetShipReimbursement",
        ),
    ]
