# Generated by Django 5.1.2 on 2025-02-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0019_delete_evefleetshipreimbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetaudience",
            name="add_to_schedule",
            field=models.BooleanField(default=True),
        ),
    ]
