# Generated by Django 5.1.2 on 2025-03-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0020_evefleetaudience_add_to_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("complete", "Complete"),
                    ("cancelled", "Cancelled"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
