# Generated by Django 5.1.2 on 2025-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0021_evefleet_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetinstance",
            name="boss_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evefleetinstance",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
