# Generated by Django 5.1.2 on 2025-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0022_evefleetinstance_boss_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetaudience",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
