# Generated by Django 5.1.2 on 2025-05-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0060_evelocation"),
        ("fleets", "0023_evefleetaudience_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefleet",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evelocation",
            ),
        ),
    ]
