# Generated by Django 5.1.9 on 2025-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0024_alter_evefleet_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="aar_link",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
