# Generated by Django 5.2.9 on 2026-01-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0068_remove_eveprimarycharacter_character_and_more"),
        ("fleets", "0026_evefleet_created_at_evefleet_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefleetaudiencewebhook",
            name="audience",
        ),
        migrations.DeleteModel(
            name="EveFleetLocation",
        ),
        migrations.RemoveField(
            model_name="evestandingfleetmemberlog",
            name="eve_standing_fleet",
        ),
        migrations.RemoveField(
            model_name="evestandingfleetcommanderlog",
            name="eve_standing_fleet",
        ),
        migrations.RemoveField(
            model_name="evestandingfleetmember",
            name="eve_standing_fleet",
        ),
        migrations.RemoveField(
            model_name="evefleetaudience",
            name="discord_voice_channel",
        ),
        migrations.RemoveField(
            model_name="evefleetaudience",
            name="discord_voice_channel_name",
        ),
        migrations.AddField(
            model_name="evefleetaudience",
            name="staging_location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evefleet",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="DEPRECATED: Use audience.staging_location instead. Kept for data migration purposes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evelocation",
            ),
        ),
        migrations.DeleteModel(
            name="EveFleetAudienceWebhook",
        ),
        migrations.DeleteModel(
            name="EveStandingFleetMemberLog",
        ),
        migrations.DeleteModel(
            name="EveStandingFleetCommanderLog",
        ),
        migrations.DeleteModel(
            name="EveStandingFleet",
        ),
        migrations.DeleteModel(
            name="EveStandingFleetMember",
        ),
    ]
