# Generated by Django 5.2.9 on 2026-01-21 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0069_evealliance_eveonline_e_name_44ecf1_idx_and_more"),
        ("fittings", "0012_alter_evedoctrine_type"),
        ("fleets", "0028_evefleetaudience_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evefleet",
            index=models.Index(
                fields=["start_time"], name="fleets_evef_start_t_51cb81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evefleetinstancemember",
            index=models.Index(
                fields=["character_id"], name="fleets_evef_charact_e6d5da_idx"
            ),
        ),
    ]
