# Generated by Django 5.1.2 on 2026-02-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0029_evefleet_fleets_evef_start_t_51cb81_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetInstanceMemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("logi_anchor", "Logi Anchor"),
                            ("dps_anchor", "DPS Anchor"),
                            ("link_shield", "Links (Shield)"),
                            ("link_armor", "Links (Armor)"),
                            ("link_information", "Links (Information)"),
                            ("link_skirmish", "Links (Skirmish)"),
                            ("cyno", "Cyno"),
                            ("scout", "Scout"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "eve_fleet_instance_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_roles",
                        to="fleets.evefleetinstancemember",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["eve_fleet_instance_member", "role"],
                        name="fleets_evef_eve_fle_a980b7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("eve_fleet_instance_member", "role"),
                        name="fleets_member_role_unique",
                    )
                ],
            },
        ),
    ]
