# Generated by Django 5.1.2 on 2026-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0030_evefleetinstancememberrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetinstancememberrole",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional; for roles that need a count (e.g. link slots).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evefleetinstancememberrole",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armor", "Armor"),
                    ("shield", "Shield"),
                    ("info", "Info"),
                    ("command", "Command"),
                ],
                help_text="Optional; e.g. armor, shield, info, command for roles that need it.",
                max_length=16,
                null=True,
            ),
        ),
    ]
