# Generated by Django 5.1.2 on 2026-02-07 21:57

from django.db import migrations, models

LINK_ROLE_TO_SUBTYPE = {
    "link_shield": "shield",
    "link_armor": "armor",
    "link_information": "info",
    "link_skirmish": "skirmish",
}


def migrate_link_roles_to_links(apps, schema_editor):
    EveFleetInstanceMemberRole = apps.get_model(
        "fleets", "EveFleetInstanceMemberRole"
    )
    for old_role, subtype in LINK_ROLE_TO_SUBTYPE.items():
        EveFleetInstanceMemberRole.objects.filter(role=old_role).update(
            role="links", subtype=subtype
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0031_member_role_subtype_quantity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evefleetinstancememberrole",
            name="fleets_member_role_unique",
        ),
        migrations.RunPython(migrate_link_roles_to_links, noop),
        migrations.AlterField(
            model_name="evefleetinstancememberrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("logi_anchor", "Logi Anchor"),
                    ("dps_anchor", "DPS Anchor"),
                    ("links", "Links"),
                    ("cyno", "Cyno"),
                    ("scout", "Scout"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetinstancememberrole",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armor", "Armor"),
                    ("shield", "Shield"),
                    ("info", "Info"),
                    ("skirmish", "Skirmish"),
                    ("command", "Command"),
                ],
                help_text="Optional; e.g. armor, shield, info, command for roles that need it.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetinstancememberrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subtype__isnull", True)),
                fields=("eve_fleet_instance_member", "role"),
                name="fleets_member_role_unique_null_subtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetinstancememberrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subtype__isnull", False)),
                fields=("eve_fleet_instance_member", "role", "subtype"),
                name="fleets_member_role_unique_with_subtype",
            ),
        ),
    ]
