# Generated by Django 5.1.2 on 2026-02-07 21:59

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def copy_role_detail_to_new_model(apps, schema_editor):
    EveFleetInstanceMemberRole = apps.get_model(
        "fleets", "EveFleetInstanceMemberRole"
    )
    EveFleetInstanceMemberRoleDetail = apps.get_model(
        "fleets", "EveFleetInstanceMemberRoleDetail"
    )
    for role in EveFleetInstanceMemberRole.objects.filter(
        Q(subtype__isnull=False) | Q(quantity__isnull=False)
    ):
        EveFleetInstanceMemberRoleDetail.objects.get_or_create(
            eve_fleet_instance_member_role=role,
            defaults={"subtype": role.subtype, "quantity": role.quantity},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0032_links_role_single_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetInstanceMemberRoleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("armor", "Armor"),
                            ("shield", "Shield"),
                            ("info", "Info"),
                            ("skirmish", "Skirmish"),
                            ("command", "Command"),
                        ],
                        help_text="Optional; e.g. armor, shield, info, command for roles that need it.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional; for roles that need a count (e.g. link slots).",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evefleetinstancememberroledetail",
            name="eve_fleet_instance_member_role",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="fleets.evefleetinstancememberrole",
            ),
        ),
        migrations.RunPython(copy_role_detail_to_new_model, noop),
        migrations.RemoveConstraint(
            model_name="evefleetinstancememberrole",
            name="fleets_member_role_unique_null_subtype",
        ),
        migrations.RemoveConstraint(
            model_name="evefleetinstancememberrole",
            name="fleets_member_role_unique_with_subtype",
        ),
        migrations.RemoveField(
            model_name="evefleetinstancememberrole",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="evefleetinstancememberrole",
            name="subtype",
        ),
        migrations.AddConstraint(
            model_name="evefleetinstancememberrole",
            constraint=models.UniqueConstraint(
                fields=("eve_fleet_instance_member", "role"),
                name="fleets_member_role_unique",
            ),
        ),
    ]
