# Generated by Django 5.1.2 on 2026-02-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0033_role_detail_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetRoleVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("logi_anchor", "Logi Anchor"),
                            ("dps_anchor", "DPS Anchor"),
                            ("links", "Links"),
                            ("cyno", "Cyno"),
                            ("scout", "Scout"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("armor", "Armor"),
                            ("shield", "Shield"),
                            ("info", "Info"),
                            ("skirmish", "Skirmish"),
                            ("command", "Command"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "eve_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_volunteers",
                        to="fleets.evefleet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["eve_fleet"],
                        name="fleets_evef_eve_fle_b4ecb9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("eve_fleet", "character_id", "role"),
                        name="fleets_role_volunteer_unique",
                    )
                ],
            },
        ),
    ]
