# Generated by Django 5.1.2 on 2026-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0034_evefleetrolevolunteer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evefleetrolevolunteer",
            options={
                "ordering": ["eve_fleet", "role", "order", "character_name"]
            },
        ),
        migrations.AddField(
            model_name="evefleetrolevolunteer",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Position within this role (0 = first logi anchor, etc.).",
            ),
        ),
        migrations.AddIndex(
            model_name="evefleetrolevolunteer",
            index=models.Index(
                fields=["eve_fleet", "role", "order"],
                name="fleets_evef_eve_fle_9d230e_idx",
            ),
        ),
    ]
