# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0035_role_volunteer_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evefleetrolevolunteer",
            options={"ordering": ["eve_fleet", "role", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="evefleetrolevolunteer",
            name="fleets_evef_eve_fle_9d230e_idx",
        ),
        migrations.RemoveField(
            model_name="evefleetrolevolunteer",
            name="order",
        ),
    ]
