# Generated by Django 5.1.2 on 2026-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0036_remove_role_volunteer_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefleetinstancememberroledetail",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armor", "Armor"),
                    ("shield", "Shield"),
                    ("info", "Info"),
                    ("skirmish", "Skirmish"),
                ],
                help_text="Optional; e.g. armor, shield, info, skirmish for roles that need it.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetrolevolunteer",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armor", "Armor"),
                    ("shield", "Shield"),
                    ("info", "Info"),
                    ("skirmish", "Skirmish"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
