# Generated by Django 5.1.2 on 2026-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fleets",
            "0037_alter_evefleetinstancememberroledetail_subtype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="objective",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short tagline for the fleet (one sentence).",
                max_length=200,
            ),
        ),
    ]
