# Generated by Django 5.1.15 on 2026-06-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0038_evefleet_objective"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetInstanceMemberImplantSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("implants", models.JSONField(blank=True, default=dict)),
                ("estimated_value_isk", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implant_snapshots",
                        to="fleets.evefleetinstancemember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "created_at"],
                        name="fleets_evef_member__e2fd83_idx",
                    )
                ],
            },
        ),
    ]
