# Generated by Django 5.1.15 on 2026-06-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0039_evefleetinstancememberimplantsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFleetInstanceMemberShipSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_type_id", models.BigIntegerField()),
                ("ship_name", models.CharField(max_length=255)),
                ("solar_system_id", models.BigIntegerField()),
                ("solar_system_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship_snapshots",
                        to="fleets.evefleetinstancemember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "created_at"],
                        name="fleets_evef_member__3c7970_idx",
                    ),
                    models.Index(
                        fields=["member", "ship_type_id"],
                        name="fleets_evef_member__06a35d_idx",
                    ),
                ],
            },
        ),
    ]
