# Generated by Django 5.1.2 on 2026-06-30

from django.db import migrations, models


def merge_armor_shield_to_ehp(apps, schema_editor):
    EveFleetRoleVolunteer = apps.get_model("fleets", "EveFleetRoleVolunteer")
    EveFleetRoleVolunteer.objects.filter(
        subtype__in=["armor", "shield"]
    ).update(subtype="ehp")
    EveFleetRoleVolunteer.objects.filter(role="dps_anchor").delete()

    EveFleetInstanceMemberRole = apps.get_model(
        "fleets", "EveFleetInstanceMemberRole"
    )
    EveFleetInstanceMemberRoleDetail = apps.get_model(
        "fleets", "EveFleetInstanceMemberRoleDetail"
    )
    EveFleetInstanceMemberRole.objects.filter(role="dps_anchor").delete()

    EveFleetInstanceMemberRoleDetail.objects.filter(
        subtype__in=["armor", "shield"]
    ).update(subtype="ehp")

    seen_member_roles = set()
    for detail in (
        EveFleetInstanceMemberRoleDetail.objects.filter(subtype="ehp")
        .select_related("eve_fleet_instance_member_role")
        .order_by("id")
    ):
        member_role = detail.eve_fleet_instance_member_role
        if member_role.role != "links":
            continue
        key = member_role.eve_fleet_instance_member_id
        if key in seen_member_roles:
            detail.delete()
        else:
            seen_member_roles.add(key)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0040_evefleetinstancemembershipsnapshot"),
    ]

    operations = [
        migrations.RunPython(merge_armor_shield_to_ehp, noop),
        migrations.AlterField(
            model_name="evefleetinstancememberrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("logi_anchor", "Logi Anchor"),
                    ("links", "Links"),
                    ("cyno", "Cyno"),
                    ("scout", "Scout"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetinstancememberroledetail",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ehp", "EHP"),
                    ("info", "Info"),
                    ("skirmish", "Skirmish"),
                ],
                help_text="Optional; e.g. ehp, info, skirmish for roles that need it.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetrolevolunteer",
            name="role",
            field=models.CharField(
                choices=[
                    ("logi_anchor", "Logi Anchor"),
                    ("links", "Links"),
                    ("cyno", "Cyno"),
                    ("scout", "Scout"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetrolevolunteer",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ehp", "EHP"),
                    ("info", "Info"),
                    ("skirmish", "Skirmish"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
