# Generated by Django 5.2.16 on 2026-08-18 22:39

import django.db.models.deletion
from django.db import migrations, models

UNALIGNED_FEED_URL = (
    "https://unaligned-event-api-984689261396.europe-west1.run.app/events"
)


def seed_unaligned_source(apps, schema_editor):
    NpsiEventSource = apps.get_model("fleets", "NpsiEventSource")
    NpsiEventSource.objects.update_or_create(
        name="Unaligned",
        defaults={
            "feed_url": UNALIGNED_FEED_URL,
            "fc_character_name": "Vex Drake",
            "default_type": "non_strategic",
            "enabled": True,
        },
    )


def unseed_unaligned_source(apps, schema_editor):
    NpsiEventSource = apps.get_model("fleets", "NpsiEventSource")
    NpsiEventSource.objects.filter(name="Unaligned").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0102_character_corporation_history"),
        ("fleets", "0041_ehp_links_remove_dps_anchor"),
    ]

    operations = [
        migrations.CreateModel(
            name="NpsiEventSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("feed_url", models.URLField(max_length=500)),
                (
                    "fc_character_name",
                    models.CharField(
                        help_text="Fallback FC if the feed item has no character_name.",
                        max_length=255,
                    ),
                ),
                (
                    "default_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Strategic Operation"),
                            ("non_strategic", "Non Strategic Operation"),
                            ("training", "Training Operation"),
                        ],
                        default="non_strategic",
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_audience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required before events can be posted to the schedule.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleetaudience",
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "NPSI event source",
            },
        ),
        migrations.CreateModel(
            name="NpsiExternalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, unique=True
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "location_text",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("seen", "Seen"),
                            ("notified", "Notified"),
                            ("created", "Posted"),
                            ("skipped", "Skipped"),
                        ],
                        default="seen",
                        max_length=16,
                    ),
                ),
                ("skip_reason", models.CharField(blank=True, max_length=255)),
                (
                    "discord_channel_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "discord_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eve_fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleet",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="fleets.npsieventsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "NPSI external event",
                "ordering": ["start_time"],
            },
        ),
        migrations.RunPython(seed_unaligned_source, unseed_unaligned_source),
    ]
