# Generated by Django 5.2.16 on 2026-09-06 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0103_evelocation_fleets_active"),
        ("fittings", "0033_evefittingchangerequest_refit_set_null"),
        ("fleets", "0043_fleet_location_npsi"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetrolevolunteer",
            name="solar_system_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evefleetrolevolunteer",
            name="solar_system_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="evefleet",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evefleetinstancememberrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("logi_anchor", "Logi FC"),
                    ("links", "Links"),
                    ("cyno", "Cyno"),
                    ("scout", "Scout"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evefleetrolevolunteer",
            name="role",
            field=models.CharField(
                choices=[
                    ("logi_anchor", "Logi FC"),
                    ("links", "Links"),
                    ("cyno", "Cyno"),
                    ("scout", "Scout"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="EveFleetFitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ship_id", models.IntegerField()),
                (
                    "eft_format",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="EFT block for manual fits (ignored for catalog fits).",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("support", "Support"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "esi_fitting_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "esi_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "eve_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_fittings",
                        to="fleets.evefleet",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catalog fitting; leave empty for a manual EFT fit.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_fittings",
                        to="fittings.evefitting",
                    ),
                ),
            ],
            options={
                "ordering": ["eve_fleet", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EveFleetFittingRefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cargo_modules",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Modules to carry in cargo, one per line (``Name xN``).",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "eft_format",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full EFT of the refitted ship (for in-game links).",
                    ),
                ),
                (
                    "esi_fitting_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "esi_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "eve_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refits",
                        to="fleets.evefleet",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_refits",
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "fleet_fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refits",
                        to="fleets.evefleetfitting",
                    ),
                ),
                (
                    "refit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_refits",
                        to="fittings.evefittingrefit",
                    ),
                ),
            ],
            options={
                "ordering": ["eve_fleet", "fitting", "fleet_fitting", "id"],
            },
        ),
        migrations.CreateModel(
            name="EveFleetShipVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "eve_fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship_volunteers",
                        to="fleets.evefleet",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_ship_volunteers",
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "fleet_fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship_volunteers",
                        to="fleets.evefleetfitting",
                    ),
                ),
            ],
            options={
                "ordering": ["eve_fleet", "fitting", "fleet_fitting", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="evefleetfitting",
            index=models.Index(
                fields=["eve_fleet"], name="fleets_evef_eve_fle_a7ea69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evefleetfittingrefit",
            index=models.Index(
                fields=["eve_fleet"], name="fleets_evef_eve_fle_5f30b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetfittingrefit",
            constraint=models.UniqueConstraint(
                fields=("eve_fleet", "fitting", "name"),
                name="fleets_refit_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetfittingrefit",
            constraint=models.UniqueConstraint(
                fields=("eve_fleet", "fleet_fitting", "name"),
                name="fleets_refit_fleet_fitting_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetfittingrefit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("fitting__isnull", False),
                        ("fleet_fitting__isnull", True),
                    ),
                    models.Q(
                        ("fitting__isnull", True),
                        ("fleet_fitting__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fleets_refit_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="evefleetshipvolunteer",
            index=models.Index(
                fields=["eve_fleet"], name="fleets_evef_eve_fle_f29a78_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetshipvolunteer",
            constraint=models.UniqueConstraint(
                fields=("eve_fleet", "character_id", "fitting"),
                name="fleets_ship_volunteer_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetshipvolunteer",
            constraint=models.UniqueConstraint(
                fields=("eve_fleet", "character_id", "fleet_fitting"),
                name="fleets_ship_volunteer_fleet_fitting_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evefleetshipvolunteer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("fitting__isnull", False),
                        ("fleet_fitting__isnull", True),
                    ),
                    models.Q(
                        ("fitting__isnull", True),
                        ("fleet_fitting__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fleets_ship_volunteer_one_target",
            ),
        ),
    ]
