# Generated by Django 5.2.16 on 2026-09-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0044_fleet_ships_refits_cyno"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="roam_report_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
