# Generated by Django 5.2.16 on 2026-09-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("fleets", "0045_evefleet_roam_report_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleet",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Counts this fleet towards a Faction Warfare campaign.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleets",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="evefleet",
            name="type",
            field=models.CharField(
                choices=[
                    ("strategic", "Strategic Operation"),
                    ("non_strategic", "Non Strategic Operation"),
                    ("training", "Training Operation"),
                    ("npsi", "NPSI"),
                    ("standing", "Campaign Standing Fleet"),
                    ("gang", "Campaign Gang"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="npsieventsource",
            name="default_type",
            field=models.CharField(
                choices=[
                    ("strategic", "Strategic Operation"),
                    ("non_strategic", "Non Strategic Operation"),
                    ("training", "Training Operation"),
                    ("npsi", "NPSI"),
                    ("standing", "Campaign Standing Fleet"),
                    ("gang", "Campaign Gang"),
                ],
                default="npsi",
                max_length=32,
            ),
        ),
    ]
