# Generated by Django 5.2.16 on 2026-08-08 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllianceHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-computed_at"],
                "permissions": (
                    (
                        "view_alliancehealth",
                        "Can view alliance health dashboard",
                    ),
                ),
            },
        ),
    ]
