FROM python:3.12-slim

# install git for doctine pulling and various other dependencies
RUN apt-get update && apt-get install -y git libmariadb-dev gcc sqlite3

WORKDIR /opt/dependencies

# Copy dependencies files and build dependency cache
COPY ./Pipfile /opt/dependencies/
COPY ./Pipfile.lock /opt/dependencies/
RUN pip install pipenv && \
  pipenv requirements > requirements.txt && \
  pip3 install -r requirements.txt && \
  pip install docker

# Copy the rest of the backend source code
# This will generally be replaced by a docker-compose directory mount
COPY . /opt/minmatar

WORKDIR /opt/minmatar

RUN chmod +x *.sh
RUN python3 manage.py collectstatic --noinput

# keep open for debugging
CMD ["tail", "-f", "/dev/null"]
