# Generated by Django 4.2.10 on 2024-02-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("groups", "0002_alter_autogroup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouprequest",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
