# Generated by Django 4.2.11 on 2024-03-05 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0004_teamrequest_team_sigrequest_sig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sig",
            name="officers",
        ),
        migrations.AddField(
            model_name="sig",
            name="officers",
            field=models.ManyToManyField(
                related_name="officer_of", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
