# Generated by Django 4.2.11 on 2024-03-08 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0005_remove_sig_officers_sig_officers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="directors",
        ),
        migrations.AddField(
            model_name="team",
            name="directors",
            field=models.ManyToManyField(
                related_name="director_of", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
