# Generated by Django 4.2.11 on 2024-03-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_remove_team_directors_team_directors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sigrequest",
            name="sig",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.sig"
            ),
        ),
        migrations.AlterField(
            model_name="teamrequest",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.team"
            ),
        ),
    ]
