# Generated by Django 5.0.4 on 2024-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0031_alter_evecharacter_alliance_and_more"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("groups", "0009_rename_autogroup_affiliationtype_useraffiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliationtype",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="affiliationtype",
            name="alliances",
            field=models.ManyToManyField(
                blank=True, to="eveonline.evealliance"
            ),
        ),
        migrations.AlterField(
            model_name="affiliationtype",
            name="corporations",
            field=models.ManyToManyField(
                blank=True, to="eveonline.evecorporation"
            ),
        ),
        migrations.AlterField(
            model_name="affiliationtype",
            name="factions",
            field=models.ManyToManyField(
                blank=True, to="eveuniverse.evefaction"
            ),
        ),
    ]
