# Generated by Django 5.0.6 on 2024-05-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0012_evecorporationgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discord_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
