# Generated by Django 5.0.6 on 2024-05-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0013_team_discord_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sig",
            name="discord_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
