# Generated by Django 5.1.2 on 2025-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_sig_discord_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sigrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="teamrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
