# Generated by Django 5.2.9 on 2026-01-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0015_sigrequest_created_teamrequest_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="sig",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="team",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
