# Generated by Django 5.1.2 on 2026-02-07

from django.db import migrations, models


def set_member_type_for_existing(apps, schema_editor):
    EveCorporationGroup = apps.get_model("groups", "EveCorporationGroup")
    EveCorporationGroup.objects.filter(group_type__isnull=True).update(
        group_type="member"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0016_sig_content_team_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporationgroup",
            name="group_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("member", "Member"),
                    ("recruiter", "Recruiter"),
                    ("director", "Director"),
                    ("gunner", "Gunner"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(
            set_member_type_for_existing, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="evecorporationgroup",
            constraint=models.UniqueConstraint(
                fields=("corporation", "group_type"),
                name="groups_evecorporationgroup_corporation_group_type_uniq",
            ),
        ),
    ]
