# Generated by Django 5.1.2 on 2026-03-02 03:38

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_user_community_status(apps, schema_editor):
    """Backfill UserCommunityStatus for existing users with affiliation. Trial/On Leave groups are created in app code (get_or_create) so signals trigger."""
    User = apps.get_model("auth", "User")
    UserAffiliation = apps.get_model("groups", "UserAffiliation")
    UserCommunityStatus = apps.get_model("groups", "UserCommunityStatus")
    UserCommunityStatusHistory = apps.get_model(
        "groups", "UserCommunityStatusHistory"
    )

    now = timezone.now()
    cutoff = now - timedelta(days=90)
    user_ids_with_affiliation = set(
        UserAffiliation.objects.values_list("user_id", flat=True).distinct()
    )
    for user_id in user_ids_with_affiliation:
        if UserCommunityStatus.objects.filter(user_id=user_id).exists():
            continue
        user = User.objects.get(id=user_id)
        status = "trial" if user.date_joined >= cutoff else "active"
        UserCommunityStatus.objects.create(user_id=user_id, status=status)
        UserCommunityStatusHistory.objects.create(
            user_id=user_id,
            from_status=None,
            to_status=status,
            reason="migration backfill",
            changed_by=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0017_evecorporationgroup_group_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliationtype",
            name="requires_trial",
            field=models.BooleanField(
                default=False,
                help_text="When True, users who first get this affiliation start as trial.",
            ),
        ),
        migrations.CreateModel(
            name="UserCommunityStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("on_leave", "On Leave"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User community statuses",
            },
        ),
        migrations.CreateModel(
            name="UserCommunityStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("on_leave", "On Leave"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("on_leave", "On Leave"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_status_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User community status histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.RunPython(
            backfill_user_community_status, migrations.RunPython.noop
        ),
    ]
