# Generated by Django 5.1.15 on 2026-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0094_evecharacter_security_status"),
        ("groups", "0022_remove_stale_celery_beat_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliationtype",
            name="characters",
            field=models.ManyToManyField(
                blank=True, to="eveonline.evecharacter"
            ),
        ),
    ]
