# Generated by Django 5.1.15 on 2026-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("groups", "0023_affiliationtype_characters"),
        ("tribes", "0027_tribegrouprank_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("affiliation", "Affiliation"),
                            ("tribe_membership", "Tribe membership"),
                            ("tribe_group_target", "Tribe group target"),
                            ("tribe_chief", "Tribe chief"),
                            ("resource_match", "Resource match"),
                            ("auth_group", "Auth group"),
                            ("staff", "Staff"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "legacy_permission",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "staff_permission",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "deny_community_statuses",
                    models.JSONField(blank=True, default=list),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "affiliations",
                    models.ManyToManyField(
                        blank=True, to="groups.affiliationtype"
                    ),
                ),
                (
                    "auth_groups",
                    models.ManyToManyField(blank=True, to="auth.group"),
                ),
                (
                    "tribe_groups",
                    models.ManyToManyField(blank=True, to="tribes.tribegroup"),
                ),
            ],
            options={
                "verbose_name": "Pilot feature",
                "verbose_name_plural": "Pilot features",
                "ordering": ["code"],
            },
        ),
    ]
