# Generated by Django 5.2.16 on 2026-08-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twitch", "Twitch"),
                            ("youtube", "YouTube"),
                            ("reddit", "Reddit"),
                        ],
                        max_length=16,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=128)),
                (
                    "platform_username",
                    models.CharField(blank=True, max_length=255),
                ),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("token_invalid", models.BooleanField(default=False)),
                ("is_live", models.BooleanField(default=False)),
                (
                    "live_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("live_title", models.CharField(blank=True, max_length=512)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreatorItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twitch", "Twitch"),
                            ("youtube", "YouTube"),
                            ("reddit", "Reddit"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("vod", "VOD"),
                            ("stream", "Stream"),
                            ("reddit_post", "Reddit post"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("url", models.URLField(blank=True, max_length=1024)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1024),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="creators.creatoraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="creatoraccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"),
                name="creators_account_user_provider_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoraccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "platform_user_id"),
                name="creators_account_provider_platform_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoritem",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"),
                name="creators_item_provider_external_uniq",
            ),
        ),
    ]
