# Generated by Django 5.1.2 on 2025-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
