# Generated by Django 5.1.2 on 2025-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_usersubscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
