# Generated by Django 5.1.2 on 2024-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="ship_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
