# Generated by Django 5.1.2 on 2024-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0002_evefleetshipreimbursement_ship_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="character_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="primary_character_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="ship_type_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
