# Generated by Django 5.1.2 on 2025-02-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0020_evefleetaudience_add_to_schedule"),
        ("srp", "0003_evefleetshipreimbursement_character_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="is_corp_ship",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="evefleetshipreimbursement",
            name="fleet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reimbursements",
                to="fleets.evefleet",
            ),
        ),
    ]
