# Generated by Django 5.1.2 on 2025-02-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0004_evefleetshipreimbursement_is_corp_ship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="corp_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
