# Generated by Django 5.1.2 on 2025-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0020_evefleetaudience_add_to_schedule"),
        ("srp", "0005_evefleetshipreimbursement_corp_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evefleetshipreimbursement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "approved"])),
                fields=("external_killmail_link",),
                name="unique_pending_or_approved_killmail_link",
            ),
        ),
    ]
