# Generated by Django 5.1.2 on 2025-05-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0021_evefleet_status"),
        (
            "srp",
            "0006_evefleetshipreimbursement_unique_pending_or_approved_killmail_link",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="evefleetshipreimbursement",
            index=models.Index(
                fields=["status", "fleet", "user"],
                name="srp_eveflee_status_18095a_idx",
            ),
        ),
    ]
