# Generated by Django 5.1.2 on 2025-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0007_evefleetshipreimbursement_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evefleetshipreimbursement",
            name="unique_pending_or_approved_killmail_link",
        ),
        migrations.AlterField(
            model_name="evefleetshipreimbursement",
            name="killmail_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
