# Generated by Django 5.1.9 on 2025-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "srp",
            "0008_remove_evefleetshipreimbursement_unique_pending_or_approved_killmail_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefleetshipreimbursement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
