# Generated by Django 5.1.9 on 2025-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0009_alter_evefleetshipreimbursement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="category",
            field=models.CharField(
                choices=[
                    ("logistics", "Logistics"),
                    ("support", "Support"),
                    ("dps", "DPS"),
                    ("capital", "Capital"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
