# Generated by Django 5.1.9 on 2025-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0010_evefleetshipreimbursement_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="comments",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
