# Generated by Django 5.1.9 on 2025-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0011_evefleetshipreimbursement_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipReimbursementValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255, null=True)),
                ("ship_name", models.CharField(max_length=255, null=True)),
                ("srp_value", models.BigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
