# Generated by Django 5.1.9 on 2025-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0012_shipreimbursementvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipReimbursementAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("class", "Ship Class"),
                            ("type", "Ship Type"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("srp_value", models.BigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ShipReimbursementValue",
        ),
    ]
