# Generated by Django 5.1.9 on 2025-09-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combatlog", "0003_combatlog_updated_at"),
        ("srp", "0013_shipreimbursementamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefleetshipreimbursement",
            name="combatLog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="combatlog.combatlog",
            ),
        ),
    ]
