# Generated by Django 5.1.9 on 2025-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0014_evefleetshipreimbursement_combatlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evefleetshipreimbursement",
            old_name="combatLog",
            new_name="combat_log",
        ),
    ]
