# Generated by Django 5.1.15 on 2026-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srp", "0016_evefleetshipreimbursement_approved_at"),
        ("srp", "0018_program_and_amount_history"),
    ]

    operations = []
