# Generated by Django 5.1.15 on 2026-06-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0026_evefittingpod_evefitting_pods"),
        ("srp", "0020_cleanup_legacy_program_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodReimbursementProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "fitting_pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pod_reimbursement_programs",
                        to="fittings.evefittingpod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PodReimbursementProgramAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("srp_value", models.BigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amounts",
                        to="srp.podreimbursementprogram",
                    ),
                ),
            ],
        ),
    ]
