# Generated by Django 5.1.2 on 2024-10-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFreightContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(unique=True)),
                ("status", models.CharField(max_length=32)),
                ("start_location_name", models.CharField(max_length=255)),
                ("end_location_name", models.CharField(max_length=255)),
                ("volume", models.BigIntegerField()),
                ("collateral", models.BigIntegerField()),
                ("reward", models.BigIntegerField()),
            ],
        ),
    ]
