# Generated by Django 5.1.2 on 2024-10-11 22:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0003_evefreightcontract_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightcontract",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evefreightcontract",
            name="date_issued",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 11, 22, 55, 29, 852414)
            ),
            preserve_default=False,
        ),
    ]
