# Generated by Django 5.1.2 on 2025-05-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0060_evelocation"),
        ("freight", "0004_evefreightcontract_date_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightroute",
            name="destination_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_location",
                to="eveonline.evelocation",
            ),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="origin_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_location",
                to="eveonline.evelocation",
            ),
        ),
    ]
