# Generated by Django 5.2.9 on 2026-01-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0006_evefreightroute_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefreightroute",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="evefreightroute",
            name="orgin",
        ),
        migrations.DeleteModel(
            name="EveFreightLocation",
        ),
    ]
