# Generated by Django 5.1.2 on 2026-02-23 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0086_add_corporation_wallet_journal"),
        ("freight", "0007_remove_evefreightroute_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightcontract",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_freight_contracts",
                to="eveonline.evecharacter",
            ),
        ),
    ]
