# Generated by Django for freight rework: flat ISK per m3 + optional collateral modifier, no bidirectional

import django.db.models.deletion
from django.db import migrations, models


def migrate_option_rates_to_route(apps, schema_editor):
    """Set isk_per_m3 and collateral_modifier on each route from its first option, if any."""
    EveFreightRoute = apps.get_model("freight", "EveFreightRoute")
    EveFreightRouteOption = apps.get_model("freight", "EveFreightRouteOption")
    for route in EveFreightRoute.objects.all():
        option = (
            EveFreightRouteOption.objects.filter(route=route)
            .order_by("id")
            .first()
        )
        if option and option.maximum_m3:
            route.isk_per_m3 = option.base_cost // option.maximum_m3
            route.collateral_modifier = option.collateral_modifier
            route.save()


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0008_evefreightcontract_issuer"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightroute",
            name="isk_per_m3",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="collateral_modifier",
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(
            migrate_option_rates_to_route, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="evefreightroute",
            name="bidirectional",
        ),
        migrations.DeleteModel(
            name="EveFreightRouteOption",
        ),
    ]
