# Generated by Django for freight route expiration and completion days

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0009_flat_freight_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightroute",
            name="expiration_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Contract expiration time in days (how long the contract is available to accept).",
            ),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="days_to_complete",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Days allowed to complete the contract after acceptance.",
            ),
        ),
    ]
