# Generated by Django 5.1.2 on 2026-03-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
        ("freight", "0012_freightcontract_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefreightroute",
            name="collateral_modifier",
            field=models.FloatField(
                default=0,
                help_text="Optional: extra ISK per 1 ISK collateral (e.g. 0.01 = 1%% of collateral).",
            ),
        ),
        migrations.AlterField(
            model_name="evefreightroute",
            name="destination_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_freight_routes",
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evefreightroute",
            name="isk_per_m3",
            field=models.BigIntegerField(
                default=0, help_text="Flat ISK charged per m³ for this route."
            ),
        ),
        migrations.AlterField(
            model_name="evefreightroute",
            name="origin_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_freight_routes",
                to="eveonline.evelocation",
            ),
        ),
    ]
