# Generated by Django 5.2.16 on 2026-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freight", "0013_alter_evefreightroute_collateral_modifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefreightroute",
            name="fixed_fee_millions",
            field=models.FloatField(
                default=0,
                help_text="Flat reward in millions of ISK (fixed type only).",
            ),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="max_collateral",
            field=models.BigIntegerField(
                blank=True,
                help_text="Maximum collateral in ISK (fixed type).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="max_m3",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum contract volume in m³ (fixed type).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evefreightroute",
            name="route_type",
            field=models.CharField(
                choices=[
                    ("rate", "Rate (ISK/m³ + collateral %)"),
                    ("fixed", "Fixed fee (max m³ + max collateral)"),
                ],
                default="rate",
                help_text="Rate: isk_per_m3 and collateral_modifier. Fixed: flat fee with max volume and max collateral.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="evefreightroute",
            name="collateral_modifier",
            field=models.FloatField(
                default=0,
                help_text="Optional: extra ISK per 1 ISK collateral (e.g. 0.01 = 1%% of collateral). Rate type only.",
            ),
        ),
        migrations.AlterField(
            model_name="evefreightroute",
            name="isk_per_m3",
            field=models.BigIntegerField(
                default=0,
                help_text="Flat ISK charged per m³ for this route (rate type only).",
            ),
        ),
    ]
