"""
Sovereignty anomaly data: combat sites and ore deposits generated by upgrades.
Mirrors the Bears Sov Planner spreadsheet logic (listAnomsInSystem).
"""

from typing import TypedDict

# Security band from system security_status (nullsec only; high/low sec not in bands).
# sec > -0.25 -> 0; -0.46 < sec <= -0.25 -> 1; -0.66 < sec <= -0.45 -> 2;
# -0.86 < sec <= -0.65 -> 3; sec <= -0.85 -> 4
SEC_BAND_BOUNDS = (-0.25, -0.46, -0.65, -0.86)


def security_band_from_status(security_status: float) -> int | None:
    """Return 0–4 for nullsec bands, or None if system is not nullsec (sec > -0.25 is band 0 but highsec/lowsec)."""
    if security_status > -0.25:
        return 0
    if security_status > -0.46:
        return 1
    if security_status > -0.66:
        return 2
    if security_status > -0.86:
        return 3
    return 4


class AnomEntry(TypedDict):
    name: str
    qty: int


# Combat: major threat (Array 1/2/3) and minor threat (Array 1/2/3).
# Each is [array_index_0, array_index_1, array_index_2], each array has [sec_0..sec_4] lists of AnomEntry.
COMBAT_MAJOR: list[list[list[AnomEntry]]] = [
    # Array 1 (Major Threat 1)
    [
        [{"name": "Drone Herd", "qty": 3}, {"name": "Drone Squad", "qty": 2}],
        [{"name": "Drone Herd", "qty": 2}, {"name": "Drone Squad", "qty": 3}],
        [
            {"name": "Drone Squad", "qty": 4},
            {"name": "Drone Patrol", "qty": 2},
        ],
        [
            {"name": "Drone Squad", "qty": 3},
            {"name": "Drone Patrol", "qty": 3},
        ],
        [
            {"name": "Drone Squad", "qty": 2},
            {"name": "Drone Patrol", "qty": 4},
            {"name": "Drone Horde", "qty": 1},
        ],
    ],
    # Array 2 (Major Threat 2)
    [
        [
            {"name": "Drone Herd", "qty": 5},
            {"name": "Drone Squad", "qty": 4},
            {"name": "Drone Patrol", "qty": 1},
        ],
        [
            {"name": "Drone Herd", "qty": 4},
            {"name": "Drone Squad", "qty": 4},
            {"name": "Drone Patrol", "qty": 3},
        ],
        [
            {"name": "Drone Squad", "qty": 4},
            {"name": "Drone Patrol", "qty": 6},
            {"name": "Drone Horde", "qty": 1},
        ],
        [
            {"name": "Drone Squad", "qty": 2},
            {"name": "Drone Patrol", "qty": 6},
            {"name": "Drone Horde", "qty": 4},
        ],
        [
            {"name": "Drone Squad", "qty": 1},
            {"name": "Drone Patrol", "qty": 7},
            {"name": "Drone Horde", "qty": 5},
        ],
    ],
    # Array 3 (Major Threat 3)
    [
        [
            {"name": "Drone Herd", "qty": 4},
            {"name": "Drone Squad", "qty": 6},
            {"name": "Drone Patrol", "qty": 3},
            {"name": "Drone Horde", "qty": 2},
        ],
        [
            {"name": "Drone Herd", "qty": 2},
            {"name": "Drone Squad", "qty": 4},
            {"name": "Drone Patrol", "qty": 5},
            {"name": "Drone Horde", "qty": 5},
        ],
        [
            {"name": "Drone Squad", "qty": 2},
            {"name": "Drone Patrol", "qty": 8},
            {"name": "Drone Horde", "qty": 7},
        ],
        [
            {"name": "Drone Patrol", "qty": 8},
            {"name": "Drone Horde", "qty": 9},
            {"name": "Teeming Drone Horde", "qty": 1},
        ],
        [
            {"name": "Drone Patrol", "qty": 6},
            {"name": "Drone Horde", "qty": 10},
            {"name": "Teeming Drone Horde", "qty": 3},
        ],
    ],
]

COMBAT_MINOR: list[list[list[AnomEntry]]] = [
    # Array 1
    [
        [
            {"name": "Drone Assembly", "qty": 3},
            {"name": "Drone Gathering", "qty": 2},
            {"name": "Drone Surveillance", "qty": 0},
            {"name": "Drone Menagerie", "qty": 0},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 2},
            {"name": "Drone Surveillance", "qty": 1},
            {"name": "Drone Menagerie", "qty": 0},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 1},
            {"name": "Drone Menagerie", "qty": 0},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 1},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 1},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Gathering", "qty": 2},
            {"name": "Drone Surveillance", "qty": 2},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
    ],
    # Array 2
    [
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 2},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 0},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 2},
            {"name": "Drone Herd", "qty": 1},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 1},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 3},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 3},
            {"name": "Drone Squad", "qty": 1},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
    ],
    # Array 3
    [
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 4},
            {"name": "Drone Surveillance", "qty": 5},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 1},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 4},
            {"name": "Drone Surveillance", "qty": 4},
            {"name": "Drone Menagerie", "qty": 3},
            {"name": "Drone Herd", "qty": 4},
            {"name": "Drone Squad", "qty": 0},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 2},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 4},
            {"name": "Drone Menagerie", "qty": 4},
            {"name": "Drone Herd", "qty": 3},
            {"name": "Drone Squad", "qty": 1},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Assembly", "qty": 1},
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 4},
            {"name": "Drone Menagerie", "qty": 4},
            {"name": "Drone Herd", "qty": 4},
            {"name": "Drone Squad", "qty": 2},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
        [
            {"name": "Drone Gathering", "qty": 3},
            {"name": "Drone Surveillance", "qty": 3},
            {"name": "Drone Menagerie", "qty": 5},
            {"name": "Drone Herd", "qty": 4},
            {"name": "Drone Squad", "qty": 3},
            {"name": "Drone Patrol", "qty": 0},
            {"name": "Drone Horde", "qty": 0},
            {"name": "Teeming Drone Horde", "qty": 0},
        ],
    ],
]

# Ore deposits by type; index 0 = Array 1 (Small), 1 = Array 2 (Medium + Large Mercoxit), 2 = Array 3 (Large + Enormous Mercoxit)
ORE_BY_TYPE: dict[str, list[str]] = {
    "isogen": [
        "Small Griemeer Deposit",
        "Griemeer Deposit",
        "Large Griemeer Deposit",
    ],
    "mexallon": [
        "Small Kylixium Deposit",
        "Kylixium Deposit",
        "Large Kylixium Deposit",
    ],
    "megacyte": [
        "Small Ueganite Deposit",
        "Ueganite Deposit",
        "Large Ueganite Deposit",
    ],
    "nocxium": [
        "Small Nocxite Deposit",
        "Nocxite Deposit",
        "Large Nocxite Deposit",
    ],
    "pyerite": [
        "Small Mordunium Deposit",
        "Mordunium Deposit",
        "Large Mordunium Deposit",
    ],
    "tritanium": [
        "Small Veldspar Deposit",
        "Veldspar Deposit",
        "Large Veldspar Deposit",
    ],
    "zydrine": [
        "Small Hezorime Deposit",
        "Hezorime Deposit",
        "Large Hezorime Deposit",
    ],
}

# Prospecting upgrade name prefix (first word, lowercased) -> ore key in ORE_BY_TYPE
ORE_TYPE_FROM_UPGRADE_PREFIX: dict[str, str] = {
    "isogen": "isogen",
    "mexallon": "mexallon",
    "megacyte": "megacyte",
    "nocxium": "nocxium",
    "pyerite": "pyerite",
    "tritanium": "tritanium",
    "zydrine": "zydrine",
}

MERCOXIT_LEVEL_2 = "Large Mercoxit Deposit"
MERCOXIT_LEVEL_3 = "Enormous Mercoxit Deposit"

# Mining anomaly respawn times (minutes): small = 1h, medium = 4h 20m, large = 12h
RESPAWN_MINUTES_SMALL = 60
RESPAWN_MINUTES_MEDIUM = 4 * 60 + 20  # 260
RESPAWN_MINUTES_LARGE = 12 * 60  # 720

RESPAWN_MINUTES_BY_LEVEL: dict[int, int] = {
    1: RESPAWN_MINUTES_SMALL,
    2: RESPAWN_MINUTES_MEDIUM,
    3: RESPAWN_MINUTES_LARGE,
}

# Mining anomaly name -> respawn time in minutes (built from ORE_BY_TYPE + Mercoxit).
ANOMALY_RESPAWN_MINUTES: dict[str, int] = {}
for _ore_list in ORE_BY_TYPE.values():
    ANOMALY_RESPAWN_MINUTES[_ore_list[0]] = RESPAWN_MINUTES_SMALL
    ANOMALY_RESPAWN_MINUTES[_ore_list[1]] = RESPAWN_MINUTES_MEDIUM
    ANOMALY_RESPAWN_MINUTES[_ore_list[2]] = RESPAWN_MINUTES_LARGE
# Large Mercoxit = large site (12h); Enormous Mercoxit = large (12h)
ANOMALY_RESPAWN_MINUTES[MERCOXIT_LEVEL_2] = RESPAWN_MINUTES_LARGE
ANOMALY_RESPAWN_MINUTES[MERCOXIT_LEVEL_3] = RESPAWN_MINUTES_LARGE


def get_respawn_minutes(anomaly_name: str) -> int | None:
    """Return respawn time in minutes for a mining anomaly name, or None if not a mining anomaly."""
    return ANOMALY_RESPAWN_MINUTES.get((anomaly_name or "").strip())


def get_all_mining_anomaly_names() -> list[str]:
    """Return sorted list of all mining anomaly names (for admin dropdowns)."""
    return sorted(ANOMALY_RESPAWN_MINUTES.keys())


def _add_combat_anomalies(
    result: dict[str, int], name: str, upgrade_level: int, band: int
) -> None:
    """Merge combat threat anomalies for one upgrade into result."""
    arr = COMBAT_MAJOR if "Major" in name else COMBAT_MINOR
    if upgrade_level >= len(arr) or band >= len(arr[upgrade_level]):
        return
    for entry in arr[upgrade_level][band]:
        q = entry.get("qty", 0)
        if q > 0:
            result[entry["name"]] = result.get(entry["name"], 0) + q


def _add_prospecting_anomalies(
    result: dict[str, int], name: str, upgrade_level: int
) -> None:
    """Merge prospecting ore anomalies for one upgrade into result."""
    parts = name.split()
    ore_type_key = parts[0].lower() if parts else ""
    ore_list = ORE_BY_TYPE.get(ore_type_key)
    if ore_list and upgrade_level < len(ore_list):
        anom_name = ore_list[upgrade_level]
        result[anom_name] = result.get(anom_name, 0) + 1
    if upgrade_level == 1:
        result[MERCOXIT_LEVEL_2] = result.get(MERCOXIT_LEVEL_2, 0) + 1
    elif upgrade_level == 2:
        result[MERCOXIT_LEVEL_3] = result.get(MERCOXIT_LEVEL_3, 0) + 1


def _parse_upgrade_level(name: str) -> int:
    """Parse 0-based upgrade level from upgrade name (e.g. 'Array 2' -> 1)."""
    try:
        level_str = name.split()[-1]
        return max(0, min(2, int(level_str) - 1))
    except (ValueError, IndexError):
        return 0


def get_anomalies_for_upgrades(
    upgrade_names: list[str],
    security_status: float,
) -> list[tuple[str, int]]:
    """
    Given a list of upgrade names (e.g. from SystemSovereigntyUpgrade.eve_type.name)
    and system security_status, return merged list of (anomaly_name, qty).
    Matches spreadsheet listAnomsInSystem logic.
    """
    band = security_band_from_status(security_status)
    if band is None:
        band = 0
    result: dict[str, int] = {}

    for upgrade in upgrade_names:
        name = (upgrade or "").strip()
        if not name:
            continue
        level = _parse_upgrade_level(name)
        if "Threat" in name:
            _add_combat_anomalies(result, name, level, band)
        elif "Prospecting" in name:
            _add_prospecting_anomalies(result, name, level)

    return [(n, qty) for n, qty in result.items() if qty > 0]
