from django.db import models


class SystemSovereigntyConfig(models.Model):
    """One row per system we track for sovereignty. Register via register_system(system_id)."""

    system_id = models.BigIntegerField(unique=True)
    system_name = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = "Sovereignty system"
        verbose_name_plural = "Sovereignty systems"

    def __str__(self):
        return self.system_name or str(self.system_id)

    def get_anomalies(self) -> list[tuple[str, int]]:
        """
        Return anomalies generated by this system's sovereignty upgrades.
        Uses system security band; result is [(anomaly_name, qty), ...].
        """
        from sovereignty.services import (  # pylint: disable=import-outside-toplevel
            get_anomalies_for_system,
        )

        return get_anomalies_for_system(self.system_id)

    @property
    def anomalies(self) -> list[tuple[str, int]]:
        """Anomalies generated by this system's upgrades (convenience for get_anomalies())."""
        return self.get_anomalies()


class SystemBaseResources(models.Model):
    """Base power/workforce per system. Created when registering a system (from universe)."""

    system_id = models.BigIntegerField(unique=True)
    base_power = models.IntegerField(default=0)
    base_workforce = models.IntegerField(default=0)

    class Meta:
        verbose_name = "System base resources"
        verbose_name_plural = "System base resources"

    def __str__(self):
        return f"System {self.system_id} (P:{self.base_power} W:{self.base_workforce})"


class SystemSovereigntyUpgrade(models.Model):
    """Which sovereignty upgrade (EveType) is installed in which system."""

    system = models.ForeignKey(
        SystemSovereigntyConfig,
        on_delete=models.CASCADE,
        related_name="installed_upgrades",
    )
    eve_type = models.ForeignKey(
        "eveuniverse.EveType",
        on_delete=models.CASCADE,
        related_name="sovereignty_system_installations",
    )

    class Meta:
        unique_together = ("system", "eve_type")
        verbose_name = "System sovereignty upgrade"
        verbose_name_plural = "System sovereignty upgrades"

    def __str__(self):
        return f"{self.system} — {self.eve_type.name}"
