// Generated by scripts/amamake_market_extract.mjs — do not hand-edit; re-run instead.
// node scripts/amamake_market_extract.mjs --year 2026 --month 8 --slug yc128-08
// Sales: http://localhost:8001 inferred-sales/monthly · Kills: zKillboard per-system cache · Extracted 2026-09-12T23:15:28.240Z

import type {
    MarketCapitalSplitRow,
    MarketCatchmentRow,
    MarketCategoryRow,
    MarketDayRow,
    MarketHubHealth,
    MarketHullRow,
    MarketIndustryIndexRow,
    MarketPipe,
    MarketRegionRow,
    MarketSalesTotals,
    MarketSalesTotalsVs,
    MarketSystemSummary,
    MarketTopTypeRow,
    MarketWarzoneSummary,
    MarketWeekRow,
} from './types'

export const EXTRACTED_AT = "2026-09-12T23:15:28.240Z"
export const MONTH_IS_CLOSED = true
export const LOCATION_ID = 1022167642188
export const DAYS_IN_MONTH = 31

export const SALES_TOTALS: MarketSalesTotals = {
    "isk": 523713648086.32,
    "isk_label": "524B",
    "fills": 69668,
    "units": 78348387,
    "types": 2313,
    "days_with_sales": 22,
    "loudest_day": {
        "date": "2026-08-07",
        "isk": 51945104861.51,
        "fills": 6148
    },
    "quietest_day": {
        "date": "2026-08-18",
        "isk": 636774521.06,
        "fills": 127
    }
}

export const SALES_TOTALS_PREV: MarketSalesTotals = {
    "isk": 1063741096796.93,
    "isk_label": "1.06T",
    "fills": 133987,
    "units": 389018188,
    "types": 2657,
    "days_with_sales": 31,
    "loudest_day": null,
    "quietest_day": null
}

export const SALES_TOTALS_VS: MarketSalesTotalsVs = {
    "isk": -540027448710.61005,
    "isk_pct": -51,
    "fills": -64319,
    "fills_pct": -48,
    "units": -310669801,
    "units_pct": -80,
    "types": -344
}

export const DAYS: readonly MarketDayRow[] = [
    {
        "date": "2026-08-01",
        "isk": 40790211546.01,
        "fills": 5526,
        "units": 4019756
    },
    {
        "date": "2026-08-02",
        "isk": 40976667977.56,
        "fills": 5586,
        "units": 7977490
    },
    {
        "date": "2026-08-03",
        "isk": 37160543894.05,
        "fills": 5524,
        "units": 4337007
    },
    {
        "date": "2026-08-04",
        "isk": 33712637211.96,
        "fills": 4600,
        "units": 7457044
    },
    {
        "date": "2026-08-05",
        "isk": 39165721813.65,
        "fills": 5223,
        "units": 5068737
    },
    {
        "date": "2026-08-06",
        "isk": 35267619961.13,
        "fills": 4559,
        "units": 3256062
    },
    {
        "date": "2026-08-07",
        "isk": 51945104861.51,
        "fills": 6148,
        "units": 5795066
    },
    {
        "date": "2026-08-08",
        "isk": 28830716067.49,
        "fills": 4922,
        "units": 16874783
    },
    {
        "date": "2026-08-09",
        "isk": 7138873306.58,
        "fills": 1020,
        "units": 1088868
    },
    {
        "date": "2026-08-10",
        "isk": 1382904566.97,
        "fills": 337,
        "units": 63720
    },
    {
        "date": "2026-08-11",
        "isk": 4987575968.8,
        "fills": 393,
        "units": 123466
    },
    {
        "date": "2026-08-12",
        "isk": 4622692456.76,
        "fills": 789,
        "units": 214104
    },
    {
        "date": "2026-08-16",
        "isk": 24044217374.57,
        "fills": 3308,
        "units": 1909404
    },
    {
        "date": "2026-08-17",
        "isk": 4240426289.94,
        "fills": 349,
        "units": 262086
    },
    {
        "date": "2026-08-18",
        "isk": 636774521.06,
        "fills": 127,
        "units": 32478
    },
    {
        "date": "2026-08-19",
        "isk": 29074414604.27,
        "fills": 3087,
        "units": 2183473
    },
    {
        "date": "2026-08-20",
        "isk": 16690552424.25,
        "fills": 2146,
        "units": 2862115
    },
    {
        "date": "2026-08-27",
        "isk": 25062049114.55,
        "fills": 3307,
        "units": 1903144
    },
    {
        "date": "2026-08-28",
        "isk": 32368763961.22,
        "fills": 3969,
        "units": 2035864
    },
    {
        "date": "2026-08-29",
        "isk": 24591464507.91,
        "fills": 2740,
        "units": 6084752
    },
    {
        "date": "2026-08-30",
        "isk": 33576880565.89,
        "fills": 4639,
        "units": 4152132
    },
    {
        "date": "2026-08-31",
        "isk": 7446835090.19,
        "fills": 1369,
        "units": 646836
    }
]

export const WEEKS: readonly MarketWeekRow[] = [
    {
        "label": "1–7 Aug",
        "isk": 279018507265.87,
        "fills": 37166,
        "units": 37911162,
        "isk_label": "279B"
    },
    {
        "label": "8–14",
        "isk": 46962762366.600006,
        "fills": 7461,
        "units": 18364941,
        "isk_label": "46.96B"
    },
    {
        "label": "15–21",
        "isk": 74686385214.09,
        "fills": 9017,
        "units": 7249556,
        "isk_label": "74.69B"
    },
    {
        "label": "22–28",
        "isk": 57430813075.770004,
        "fills": 7276,
        "units": 3939008,
        "isk_label": "57.43B"
    },
    {
        "label": "29–31",
        "isk": 65615180163.990005,
        "fills": 8748,
        "units": 10883720,
        "isk_label": "65.62B"
    }
]

export const CATEGORIES: readonly MarketCategoryRow[] = [
    {
        "name": "Modules",
        "isk": 196050236234.33002,
        "units": 103161,
        "fills": 40392,
        "isk_label": "196B",
        "share": 37.4,
        "isk_vs": -191703372470.16998,
        "isk_vs_pct": -49
    },
    {
        "name": "Ships",
        "isk": 180765278520,
        "units": 7056,
        "fills": 4801,
        "isk_label": "181B",
        "share": 34.5,
        "isk_vs": -173521120843,
        "isk_vs_pct": -49
    },
    {
        "name": "Injectors & implants",
        "isk": 54957189996,
        "units": 5787,
        "fills": 2417,
        "isk_label": "54.96B",
        "share": 10.5,
        "isk_vs": -75883159505.01,
        "isk_vs_pct": -58
    },
    {
        "name": "Charges",
        "isk": 41327428417.27998,
        "units": 34723826,
        "fills": 17438,
        "isk_label": "41.33B",
        "share": 7.9,
        "isk_vs": -34393305993.89995,
        "isk_vs_pct": -45
    },
    {
        "name": "Drones",
        "isk": 17858602033,
        "units": 24879,
        "fills": 3660,
        "isk_label": "17.86B",
        "share": 3.4,
        "isk_vs": -10450694469,
        "isk_vs_pct": -37
    },
    {
        "name": "Materials & commodities",
        "isk": 16890362902.710003,
        "units": 43390713,
        "fills": 688,
        "isk_label": "16.89B",
        "share": 3.2,
        "isk_vs": -54671663592.33,
        "isk_vs_pct": -76
    },
    {
        "name": "Other",
        "isk": 15864549983,
        "units": 92965,
        "fills": 272,
        "isk_label": "15.86B",
        "share": 3,
        "isk_vs": 595868162.7999992,
        "isk_vs_pct": 4
    }
]

export const TOP_TYPES: readonly MarketTopTypeRow[] = [
    {
        "typeId": 40519,
        "name": "Skill Extractor",
        "category": "Other",
        "isk": 9561700000,
        "isk_label": "9.56B",
        "units": 20,
        "fills": 8,
        "share": 1.8,
        "isk_vs_pct": 308,
        "is_new": false
    },
    {
        "typeId": 35683,
        "name": "Hecate",
        "category": "Ships",
        "isk": 9288010000,
        "isk_label": "9.29B",
        "units": 103,
        "fills": 90,
        "share": 1.8,
        "isk_vs_pct": -60,
        "is_new": false
    },
    {
        "typeId": 28668,
        "name": "Nanite Repair Paste",
        "category": "Charges",
        "isk": 8752712150,
        "isk_label": "8.75B",
        "units": 280291,
        "fills": 970,
        "share": 1.7,
        "isk_vs_pct": -44,
        "is_new": false
    },
    {
        "typeId": 40520,
        "name": "Large Skill Injector",
        "category": "Injectors & implants",
        "isk": 6316000000,
        "isk_label": "6.32B",
        "units": 8,
        "fills": 6,
        "share": 1.2,
        "isk_vs_pct": -78,
        "is_new": false
    },
    {
        "typeId": 41490,
        "name": "Navy Cap Booster 3200",
        "category": "Charges",
        "isk": 5934431300,
        "isk_label": "5.93B",
        "units": 6651,
        "fills": 97,
        "share": 1.1,
        "isk_vs_pct": -20,
        "is_new": false
    },
    {
        "typeId": 73794,
        "name": "Thrasher Fleet Issue",
        "category": "Ships",
        "isk": 5387650000,
        "isk_label": "5.39B",
        "units": 290,
        "fills": 183,
        "share": 1,
        "isk_vs_pct": -37,
        "is_new": false
    },
    {
        "typeId": 33892,
        "name": "Small Transverse Bulkhead II",
        "category": "Modules",
        "isk": 5293657000,
        "isk_label": "5.29B",
        "units": 1143,
        "fills": 277,
        "share": 1,
        "isk_vs_pct": -65,
        "is_new": false
    },
    {
        "typeId": 16274,
        "name": "Helium Isotopes",
        "category": "Materials & commodities",
        "isk": 4532086206.8,
        "isk_label": "4.53B",
        "units": 5252226,
        "fills": 61,
        "share": 0.9,
        "isk_vs_pct": -49,
        "is_new": false
    },
    {
        "typeId": 73790,
        "name": "Revelation Navy Issue",
        "category": "Ships",
        "isk": 4500000000,
        "isk_label": "4.50B",
        "units": 1,
        "fills": 1,
        "share": 0.9,
        "isk_vs_pct": null,
        "is_new": true
    },
    {
        "typeId": 644,
        "name": "Typhoon",
        "category": "Ships",
        "isk": 4087700000,
        "isk_label": "4.09B",
        "units": 22,
        "fills": 18,
        "share": 0.8,
        "isk_vs_pct": -57,
        "is_new": false
    }
]

export const HULLS: readonly MarketHullRow[] = [
    {
        "typeId": 587,
        "name": "Rifter",
        "group": "Frigate",
        "sold": 485,
        "lost": 806,
        "sold_vs": -122,
        "lost_vs": 256,
        "ratio": 0.6
    },
    {
        "typeId": 73794,
        "name": "Thrasher Fleet Issue",
        "group": "Destroyer",
        "sold": 290,
        "lost": 311,
        "sold_vs": -142,
        "lost_vs": 70,
        "ratio": 0.9
    },
    {
        "typeId": 593,
        "name": "Tristan",
        "group": "Frigate",
        "sold": 277,
        "lost": 272,
        "sold_vs": -25,
        "lost_vs": 99,
        "ratio": 1
    },
    {
        "typeId": 16242,
        "name": "Thrasher",
        "group": "Destroyer",
        "sold": 227,
        "lost": 317,
        "sold_vs": -399,
        "lost_vs": 5,
        "ratio": 0.7
    },
    {
        "typeId": 585,
        "name": "Slasher",
        "group": "Frigate",
        "sold": 230,
        "lost": 217,
        "sold_vs": -258,
        "lost_vs": -21,
        "ratio": 1.1
    },
    {
        "typeId": 32880,
        "name": "Venture",
        "group": "Frigate",
        "sold": 74,
        "lost": 333,
        "sold_vs": -143,
        "lost_vs": 201,
        "ratio": 0.2
    },
    {
        "typeId": 17841,
        "name": "Federation Navy Comet",
        "group": "Frigate",
        "sold": 143,
        "lost": 227,
        "sold_vs": -188,
        "lost_vs": 12,
        "ratio": 0.6
    },
    {
        "typeId": 602,
        "name": "Kestrel",
        "group": "Frigate",
        "sold": 134,
        "lost": 234,
        "sold_vs": -89,
        "lost_vs": 113,
        "ratio": 0.6
    }
]

export const HULLS_SOLD_TOTAL = 6883
export const HULLS_LOST_TOTAL = 8988
export const AMAMAKE: MarketSystemSummary = {
    "system_id": 30002537,
    "ships": 9184,
    "ships_vs": 1175,
    "isk": 852516413236.8219,
    "isk_label": "853B",
    "isk_vs": 5104146626.014526,
    "share_of_warzone": 21.7,
    "unique_characters": 4622,
    "capital_ships": 37,
    "capital_isk": 280174660375.43005,
    "loudest_day": {
        "date": "2026-08-15",
        "ships": 1780
    },
    "holds_today": "minmatar"
}

export const WARZONE: MarketWarzoneSummary = {
    "systems": 70,
    "ships": 42352,
    "ships_vs": 3223,
    "isk": 3609288080767.7427,
    "isk_label": "3.61T",
    "isk_vs": 346487266228.0083
}

export const CATCHMENT: readonly MarketCatchmentRow[] = [
    {
        "system": "Amamake",
        "system_id": 30002537,
        "region": "Heimatar",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002537/",
        "ships": 9184,
        "ships_vs": 1175,
        "isk": 852516413236.8219,
        "isk_label": "853B",
        "isk_vs": 5104146626.014526,
        "capital_ships": 37,
        "capital_isk": 280174660375.43005,
        "capital_share": 32.9,
        "share_of_warzone": 21.7,
        "holds_today": "minmatar"
    },
    {
        "system": "Kourmonen",
        "system_id": 30003068,
        "region": "The Bleak Lands",
        "front": "Amarr front",
        "href": "https://zkillboard.com/system/30003068/",
        "ships": 3314,
        "ships_vs": 1612,
        "isk": 254691760014.25003,
        "isk_label": "255B",
        "isk_vs": 109560495238.80014,
        "capital_ships": 5,
        "capital_isk": 35847513388.82,
        "capital_share": 14.1,
        "share_of_warzone": 7.8,
        "holds_today": "minmatar"
    },
    {
        "system": "Auga",
        "system_id": 30002542,
        "region": "Heimatar",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002542/",
        "ships": 3041,
        "ships_vs": -2455,
        "isk": 173707871709.66962,
        "isk_label": "174B",
        "isk_vs": -230352206907.66907,
        "capital_ships": 3,
        "capital_isk": 22452896496.99,
        "capital_share": 12.9,
        "share_of_warzone": 7.2,
        "holds_today": "minmatar"
    },
    {
        "system": "Dal",
        "system_id": 30002541,
        "region": "Heimatar",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002541/",
        "ships": 2703,
        "ships_vs": 333,
        "isk": 164312079184.81964,
        "isk_label": "164B",
        "isk_vs": -9927481269.110352,
        "capital_ships": 2,
        "capital_isk": 13113873836.8,
        "capital_share": 8,
        "share_of_warzone": 6.4,
        "holds_today": "amarr"
    },
    {
        "system": "Siseide",
        "system_id": 30002539,
        "region": "Heimatar",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002539/",
        "ships": 2605,
        "ships_vs": -523,
        "isk": 144796017924.25992,
        "isk_label": "145B",
        "isk_vs": -28086219656.280212,
        "capital_ships": 2,
        "capital_isk": 9904295072.08,
        "capital_share": 6.8,
        "share_of_warzone": 6.2,
        "holds_today": "minmatar"
    },
    {
        "system": "Kamela",
        "system_id": 30003069,
        "region": "The Bleak Lands",
        "front": "Amarr front",
        "href": "https://zkillboard.com/system/30003069/",
        "ships": 2382,
        "ships_vs": 2217,
        "isk": 474054267085.62036,
        "isk_label": "474B",
        "isk_vs": 444502271111.7604,
        "capital_ships": 50,
        "capital_isk": 272377743693.55997,
        "capital_share": 57.5,
        "share_of_warzone": 5.6,
        "holds_today": "minmatar"
    },
    {
        "system": "Vard",
        "system_id": 30002538,
        "region": "Heimatar",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002538/",
        "ships": 2044,
        "ships_vs": 196,
        "isk": 78050997937.54004,
        "isk_label": "78.05B",
        "isk_vs": -16554648767.480057,
        "capital_ships": 0,
        "capital_isk": 0,
        "capital_share": 0,
        "share_of_warzone": 4.8,
        "holds_today": "amarr"
    },
    {
        "system": "Aset",
        "system_id": 30002084,
        "region": "Metropolis",
        "front": "Minmatar front",
        "href": "https://zkillboard.com/system/30002084/",
        "ships": 1534,
        "ships_vs": -70,
        "isk": 96518492068.24025,
        "isk_label": "96.52B",
        "isk_vs": 1606775316.000351,
        "capital_ships": 0,
        "capital_isk": 0,
        "capital_share": 0,
        "share_of_warzone": 3.6,
        "holds_today": "amarr"
    }
]

export const REGIONS: readonly MarketRegionRow[] = [
    {
        "region": "Heimatar",
        "front": "Minmatar front",
        "ships": 21297,
        "isk": 1498657235763.4312,
        "isk_label": "1.50T",
        "share": 50.3
    },
    {
        "region": "Metropolis",
        "front": "Minmatar front",
        "ships": 12024,
        "isk": 976639332350.3008,
        "isk_label": "977B",
        "share": 28.4
    },
    {
        "region": "The Bleak Lands",
        "front": "Amarr front",
        "ships": 8629,
        "isk": 1102309511686.6504,
        "isk_label": "1.10T",
        "share": 20.4
    },
    {
        "region": "Devoid",
        "front": "Amarr front",
        "ships": 402,
        "isk": 31682000967.36,
        "isk_label": "31.68B",
        "share": 0.9
    }
]

export const PIPE: MarketPipe = {
    "label": "Amamake, Auga, Siseide, Dal, Vard, Lantorn",
    "systems": [
        "Amamake",
        "Auga",
        "Siseide",
        "Dal",
        "Vard",
        "Lantorn"
    ],
    "ships": 20584,
    "isk": 1452529428055.4312,
    "share": 48.6
}

export const CAPITAL_SPLIT: readonly MarketCapitalSplitRow[] = [
    {
        "system": "Amamake",
        "system_id": 30002537,
        "capital_ships": 37,
        "capital_isk": 280174660375.43005,
        "subcap_isk": 572341752861.3918,
        "capital_isk_label": "280B",
        "subcap_isk_label": "572B"
    },
    {
        "system": "Kamela",
        "system_id": 30003069,
        "capital_ships": 50,
        "capital_isk": 272377743693.55997,
        "subcap_isk": 201676523392.0604,
        "capital_isk_label": "272B",
        "subcap_isk_label": "202B"
    },
    {
        "system": "Haras",
        "system_id": 30003087,
        "capital_ships": 14,
        "capital_isk": 101369908822.00002,
        "subcap_isk": 43946919079.03996,
        "capital_isk_label": "101B",
        "subcap_isk_label": "43.95B"
    },
    {
        "system": "Todifrauan",
        "system_id": 30002062,
        "capital_ships": 3,
        "capital_isk": 61865847139.68,
        "subcap_isk": 20564907290.91001,
        "capital_isk_label": "61.87B",
        "subcap_isk_label": "20.56B"
    },
    {
        "system": "Huola",
        "system_id": 30003067,
        "capital_ships": 9,
        "capital_isk": 53490718043.20999,
        "subcap_isk": 52288208073.31004,
        "capital_isk_label": "53.49B",
        "subcap_isk_label": "52.29B"
    },
    {
        "system": "Turnur",
        "system_id": 30002086,
        "capital_ships": 7,
        "capital_isk": 49116742830.45,
        "subcap_isk": 85714418280.49002,
        "capital_isk_label": "49.12B",
        "subcap_isk_label": "85.71B"
    }
]

export const INDUSTRY_INDICES: readonly MarketIndustryIndexRow[] = [
    {
        "system": "Amamake",
        "system_id": 30002537,
        "manufacturing": 0.1331,
        "reaction": 0.1249
    },
    {
        "system": "Jita",
        "system_id": 30000142,
        "manufacturing": 0.1717,
        "reaction": 0.0014
    },
    {
        "system": "Auner",
        "system_id": 30002059,
        "manufacturing": 0.1134,
        "reaction": 0.1548
    },
    {
        "system": "Basgerin",
        "system_id": 30002666,
        "manufacturing": 0.0524,
        "reaction": 0.0742
    },
    {
        "system": "Amo",
        "system_id": 30002055,
        "manufacturing": 0.0437,
        "reaction": 0.0014
    },
    {
        "system": "Auga",
        "system_id": 30002542,
        "manufacturing": 0.0094,
        "reaction": 0.0014
    }
]

export const INDUSTRY_AS_OF = "2026-09-12"
export const HUB_HEALTH: MarketHubHealth | null = {
    "sell_orders_health_pct": null,
    "sell_orders_viability_pct": null,
    "sell_orders_isk": 1952620725706.74,
    "contracts_health_pct": null,
    "contracts_isk": 856465873398,
    "synced_at": "2026-09-12T18:22:02.066520+00:00"
}
