# Generated by Django (sovereignty app)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSovereigntyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.BigIntegerField(unique=True)),
                ("system_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "System sovereignty config",
                "verbose_name_plural": "System sovereignty configs",
            },
        ),
        migrations.CreateModel(
            name="SovereigntyUpgradeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("eve_type_id", models.IntegerField(blank=True, null=True)),
                ("power_cost", models.IntegerField(default=0)),
                ("workforce_cost", models.IntegerField(default=0)),
                (
                    "produces_power",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "consumes_workforce",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "produces_workforce",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "consumes_power",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "mining_upgrade_level",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name": "Sovereignty upgrade type",
                "verbose_name_plural": "Sovereignty upgrade types",
            },
        ),
        migrations.CreateModel(
            name="SystemSovereigntyUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_upgrades",
                        to="sovereignty.systemsovereigntyconfig",
                    ),
                ),
                (
                    "upgrade_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_installations",
                        to="sovereignty.sovereigntyupgradetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "System sovereignty upgrade",
                "verbose_name_plural": "System sovereignty upgrades",
                "unique_together": {("system", "upgrade_type")},
            },
        ),
        migrations.CreateModel(
            name="SystemBaseResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.BigIntegerField(unique=True)),
                ("base_power", models.IntegerField(default=0)),
                ("base_workforce", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "System base resources",
                "verbose_name_plural": "System base resources",
            },
        ),
    ]
