# Generated by Django (sovereignty: switch upgrades to EveType, remove SovereigntyUpgradeType)

from django.db import migrations, models
import django.db.models.deletion


def copy_upgrade_type_to_evetype(apps, schema_editor):
    EveType = apps.get_model("eveuniverse", "EveType")
    SystemSovereigntyUpgrade = apps.get_model(
        "sovereignty", "SystemSovereigntyUpgrade"
    )
    apps.get_model(
        "sovereignty", "SovereigntyUpgradeType"
    )  # ensure model exists
    for inst in SystemSovereigntyUpgrade.objects.select_related(
        "upgrade_type"
    ).all():
        old = inst.upgrade_type
        type_id = getattr(old, "eve_type_id", None) or getattr(
            old, "eve_type_id", None
        )
        if type_id is None:
            continue
        eve_type, _ = EveType.objects.get_or_create(
            id=type_id,
            defaults={"name": getattr(old, "name", f"Type {type_id}")},
        )
        inst.eve_type_id = eve_type.id
        inst.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0001_initial"),
        ("sovereignty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsovereigntyupgrade",
            name="eve_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sovereignty_system_installations",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.RunPython(copy_upgrade_type_to_evetype, noop_reverse),
        migrations.AlterUniqueTogether(
            name="systemsovereigntyupgrade",
            unique_together={("system", "eve_type")},
        ),
        migrations.RemoveField(
            model_name="systemsovereigntyupgrade",
            name="upgrade_type",
        ),
        migrations.AlterField(
            model_name="systemsovereigntyupgrade",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sovereignty_system_installations",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.DeleteModel(
            name="SovereigntyUpgradeType",
        ),
    ]
