# Generated by Django 5.1.15 on 2026-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sovereignty", "0002_switch_to_evetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemsovereigntyconfig",
            options={
                "verbose_name": "Sovereignty system",
                "verbose_name_plural": "Sovereignty systems",
            },
        ),
    ]
