export const space = {
    "space_3xs": "--space-3xs",
    "space_2xs": "--space-2xs",
    "space_xs": "--space-xs",
    "space_s": "--space-s",
    "space_m": "--space-m",
    "space_l": "--space-l",
    "space_xl": "--space-xl",
    "space_2xl": "--space-2xl",
    "space_3xl": "--space-3xl",
    "space_3xs_2xs": "--space-3xs-2xs",
    "space_2xs_xs": "--space-2xs-xs",
    "space_xs_s": "--space-xs-s",
    "space_s_m": "--space-s-m",
    "space_m_l": "--space-m-l",
    "space_l_xl": "--space-l-xl",
    "space_xl_2xl": "--space-xl-2xl",
    "space_2xl_3xl": "--space-2xl-3xl",
    "space_s_l": "--space-s-l",
}