# Generated by Django 5.1.15 on 2026-07-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPageProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_key", models.CharField(max_length=255)),
                (
                    "page_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("version", models.CharField(max_length=128)),
                ("section_total", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User page progress",
                "verbose_name_plural": "User page progress",
                "indexes": [
                    models.Index(
                        fields=["page_key"],
                        name="page_progre_page_ke_f7d99b_idx",
                    ),
                    models.Index(
                        fields=["user", "page_key"],
                        name="page_progre_user_id_253c65_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "page_key", "version"),
                        name="uniq_user_page_progress_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPageSectionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_key", models.CharField(max_length=255)),
                ("section_id", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=128)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_section_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User page section progress",
                "verbose_name_plural": "User page section progress",
                "indexes": [
                    models.Index(
                        fields=["user", "page_key", "version"],
                        name="page_progre_user_id_504613_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "page_key", "section_id", "version"),
                        name="uniq_user_page_section_progress_version",
                    )
                ],
            },
        ),
    ]
