# Generated by Django 5.2.16 on 2026-07-26 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("summary", models.TextField(blank=True, default="")),
                ("published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "personas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of persona keys that include this certificate by default (e.g. ["alliance", "militia"]).',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Learning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "url",
                    models.CharField(
                        help_text="Site-relative path (e.g. /guides/…) or absolute URL.",
                        max_length=500,
                    ),
                ),
                (
                    "content_kind",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("blog", "Blog"),
                            ("page", "Page"),
                            ("youtube", "YouTube"),
                            ("external", "External"),
                            ("other", "Other"),
                        ],
                        default="guide",
                        max_length=20,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CertificateLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_learnings",
                        to="learning.certificate",
                    ),
                ),
                (
                    "learning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_links",
                        to="learning.learning",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="learnings",
            field=models.ManyToManyField(
                blank=True,
                related_name="certificates",
                through="learning.CertificateLearning",
                to="learning.learning",
            ),
        ),
        migrations.CreateModel(
            name="UserCertificateAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="learning.certificate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLearningPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("militia", "Militia"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "persona_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="learning.learning",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User learning progress",
            },
        ),
        migrations.AddConstraint(
            model_name="certificatelearning",
            constraint=models.UniqueConstraint(
                fields=("certificate", "learning"),
                name="uniq_certificate_learning",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercertificateaward",
            constraint=models.UniqueConstraint(
                fields=("user", "certificate"),
                name="uniq_user_certificate_award",
            ),
        ),
        migrations.AddConstraint(
            model_name="userlearningprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "learning"), name="uniq_user_learning_progress"
            ),
        ),
    ]
