# Generated by Django 4.2.8 on 2023-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0002_discordrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordrole",
            name="role_id",
            field=models.BigIntegerField(blank=True),
        ),
    ]
