# Generated by Django 5.1.2 on 2024-10-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("fittings", "0007_alter_evedoctrine_type"),
        ("structures", "0009_alter_evestructuretimer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("completed", "Completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                ("assignee_id", models.BigIntegerField(blank=True, null=True)),
                ("acceptor_id", models.BigIntegerField(blank=True, null=True)),
                ("issuer_external_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fittings.evefitting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketContractExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.evestructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketContractResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                (
                    "expectation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.evemarketcontractexpectation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketItemExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.evestructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketItemOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                ("quantity", models.IntegerField()),
                ("issuer_external_id", models.BigIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.evestructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketItemResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                (
                    "expectation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.evemarketitemexpectation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveMarketItemTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                ("quantity", models.IntegerField()),
                ("issuer_external_id", models.BigIntegerField()),
                ("sell_date", models.DateTimeField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.evestructure",
                    ),
                ),
            ],
        ),
    ]
