# Generated by Django 5.1.2 on 2024-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evemarketcontract",
            name="contract_id",
        ),
        migrations.RemoveField(
            model_name="evemarketcontract",
            name="status",
        ),
        migrations.AlterField(
            model_name="evemarketcontract",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
