# Generated by Django 5.1.2 on 2024-10-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_remove_evemarketcontract_contract_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketLocation",
            fields=[
                (
                    "location_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("solar_system_id", models.BigIntegerField()),
                ("solar_system_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="evemarketcontract",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.evemarketlocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemexpectation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market.evemarketlocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemorder",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market.evemarketlocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemtransaction",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market.evemarketlocation",
            ),
        ),
    ]
