# Generated by Django 5.1.2 on 2024-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0003_evemarketlocation_evemarketcontract_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("outstanding", "Outstanding"),
                    ("finished", "Finished"),
                    ("expired", "Expired"),
                ],
                default="expired",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
