# Generated by Django 5.1.2 on 2024-10-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_evemarketcontract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evemarketcontractexpectation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market.evemarketlocation",
            ),
        ),
    ]
