# Generated by Django 5.1.2 on 2024-10-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_evemarketcontractexpectation_location"),
        ("structures", "0009_alter_evestructuretimer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketlocation",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.evestructure",
            ),
        ),
    ]
