# Generated by Django 5.1.2 on 2025-05-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0060_evelocation"),
        ("market", "0006_evemarketlocation_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evemarketcontract",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketcontractexpectation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemexpectation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemorder",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evelocation",
            ),
        ),
        migrations.AlterField(
            model_name="evemarketitemtransaction",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="eveonline.evelocation",
            ),
        ),
    ]
