# Generated by Django 5.1.9 on 2025-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_alter_evemarketcontract_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evemarketcontract",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
