# Generated by Django 5.1.9 on 2025-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_evemarketcontract_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
