# Generated by Django 5.1.9 on 2025-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_evemarketcontract_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
