# Generated by Django 5.1.9 on 2025-07-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0066_evelocation_region_id"),
        ("market", "0010_evemarketcontract_issued_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketContractError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evelocation",
                    ),
                ),
            ],
        ),
    ]
