# Generated by Django 5.1.9 on 2025-07-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0011_evemarketcontracterror"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evemarketcontracterror",
            name="price",
        ),
    ]
