# Generated by Django 5.2.9 on 2026-01-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0012_remove_evemarketcontracterror_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EveMarketLocation",
        ),
    ]
