# Generated by Django 5.1.2 on 2026-02-16 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0013_delete_evemarketlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
