# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0014_evemarketitemorder_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="imported_by_task_uid",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="evemarketitemorder",
            name="issuer_external_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
