# Generated by Django 5.1.2 on 2026-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0076_migrate_advanced_token_to_basic"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0015_evemarketitemorder_imported_by_task_uid"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evemarketitemorder",
            index=models.Index(
                fields=["location", "imported_by_task_uid"],
                name="market_itemorder_loc_task",
            ),
        ),
        migrations.AddIndex(
            model_name="evemarketitemorder",
            index=models.Index(
                fields=["location", "item"], name="market_itemorder_loc_item"
            ),
        ),
    ]
