# Generated by Django 5.1.2 on 2026-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0016_evemarketitemorder_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="imported_page",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="1-based ESI page this order was imported from (for debugging).",
                null=True,
            ),
        ),
    ]
