# Generated by Django 5.1.2 on 2026-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0017_evemarketitemorder_imported_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="order_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ESI order_id when returned by structure markets; prevents duplicate imports.",
                null=True,
                unique=True,
            ),
        ),
    ]
