# Generated by Django 5.1.2 on 2026-02-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0076_migrate_advanced_token_to_basic"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0018_evemarketitemorder_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketItemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Day this history row is for (ESI date, e.g. midday snapshot)."
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average price for the day.",
                        max_digits=32,
                    ),
                ),
                (
                    "highest",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Highest price for the day.",
                        max_digits=32,
                    ),
                ),
                (
                    "lowest",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lowest price for the day.",
                        max_digits=32,
                    ),
                ),
                (
                    "order_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total number of orders executed that day.",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        default=0, help_text="Total volume traded that day."
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_item_histories",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_item_histories",
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVE market item history",
                "verbose_name_plural": "EVE market item histories",
                "ordering": ["-date", "location", "item"],
                "indexes": [
                    models.Index(
                        fields=["location", "date"],
                        name="market_itemhist_loc_date",
                    ),
                    models.Index(
                        fields=["item", "date"],
                        name="market_itemhist_item_date",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "item", "date"),
                        name="market_itemhistory_loc_item_date",
                    )
                ],
            },
        ),
    ]
