# Generated by Django 5.1.2 on 2026-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0019_evemarketitemhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evemarketitemhistory",
            options={
                "ordering": ["-date", "region_id", "item"],
                "verbose_name": "EVE market item history",
                "verbose_name_plural": "EVE market item histories",
            },
        ),
        migrations.RemoveConstraint(
            model_name="evemarketitemhistory",
            name="market_itemhistory_loc_item_date",
        ),
        migrations.RemoveIndex(
            model_name="evemarketitemhistory",
            name="market_itemhist_loc_date",
        ),
        migrations.RemoveField(
            model_name="evemarketitemhistory",
            name="location",
        ),
        migrations.AddField(
            model_name="evemarketitemhistory",
            name="region_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="ESI region ID; history is per region so we fetch each item once per date.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="evemarketitemhistory",
            index=models.Index(
                fields=["region_id", "date"],
                name="market_itemhist_region_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="evemarketitemhistory",
            constraint=models.UniqueConstraint(
                fields=("region_id", "item", "date"),
                name="market_itemhist_region_item_date",
            ),
        ),
    ]
