# Generated by Django 5.1.2 on 2026-02-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0020_evemarketitemhistory_region_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveTypeWithSellOrders",
            fields=[],
            options={
                "verbose_name": "EVE type (with sell orders)",
                "verbose_name_plural": "EVE types (with sell orders)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eveuniverse.evetype",),
        ),
    ]
