# Generated by Django 5.1.2 on 2026-02-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0086_add_corporation_wallet_journal"),
        ("fittings", "0018_remove_eve_fitting_tags"),
        ("market", "0021_evetypewithsellorders"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketFittingExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("fitting", "location")},
            },
        ),
    ]
