# Generated by Django 5.1.2

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0086_add_corporation_wallet_journal"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0022_evemarketfittingexpectation"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="is_buy_order",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a buy order, False for sell order.",
            ),
        ),
        migrations.CreateModel(
            name="EveMarketItemLocationPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lowest sell order price at this location.",
                        max_digits=32,
                    ),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Highest buy order price at this location; null if no buy orders.",
                        max_digits=32,
                        null=True,
                    ),
                ),
                (
                    "split_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(sell_price + buy_price) / 2; null when buy_price is null.",
                        max_digits=32,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(default=timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_location_prices",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_item_prices",
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVE market item location price",
                "verbose_name_plural": "EVE market item location prices",
                "ordering": ["location", "item"],
            },
        ),
        migrations.AddConstraint(
            model_name="evemarketitemlocationprice",
            constraint=models.UniqueConstraint(
                fields=("location", "item"),
                name="market_itemlocprice_loc_item",
            ),
        ),
    ]
