# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0023_evemarketitemorder_is_buy_order_evemarketitemlocationprice",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="order_range",
            field=models.CharField(
                blank=True,
                help_text="ESI order range: station, region, solarsystem, or jump count (1-40). Used to exclude region-wide lowballs from location buy_price.",
                max_length=20,
            ),
        ),
    ]
