# Generated by Django 5.1.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0025_remove_evemarketitemorder_order_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evemarketitemorder",
            name="is_buy_order",
        ),
    ]
