# Generated by Django 5.1.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("market", "0026_remove_evemarketitemorder_is_buy_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketitemorder",
            name="is_buy_order",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a buy order, False for sell order.",
            ),
        ),
        migrations.CreateModel(
            name="EveMarketBuyOrderExpectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "location")},
            },
        ),
        migrations.AddIndex(
            model_name="evemarketitemorder",
            index=models.Index(
                fields=["location", "item", "is_buy_order"],
                name="market_itemorder_loc_item_buy",
            ),
        ),
    ]
