# Generated by Django 5.1.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0027_buy_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="items_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evemarketcontract",
            name="items_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evemarketcontract",
            name="match_is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evemarketcontract",
            name="match_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EveMarketContractItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("quantity", models.IntegerField(default=1)),
                ("is_included", models.BooleanField(default=True)),
                ("is_singleton", models.BooleanField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.evemarketcontract",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["contract", "type_id"],
                        name="market_contractitem_ct",
                    )
                ],
            },
        ),
    ]
