# Generated by Django 5.1.15 on 2026-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0095_evelocation_market_categories"),
        ("fittings", "0027_migrate_legacy_pod_text"),
        ("market", "0028_contract_items"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evemarketcontract",
            index=models.Index(
                fields=["location", "status"],
                name="market_contract_loc_status",
            ),
        ),
        migrations.AddIndex(
            model_name="evemarketcontract",
            index=models.Index(
                fields=["location", "status", "fitting"],
                name="market_contract_loc_stat_fit",
            ),
        ),
    ]
