# Generated by Django 5.2.16 on 2026-07-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0097_industry_job_status_blueprint_id_idx"),
        ("market", "0030_remove_responsibilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketOpsMonitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("contracts", "Contracts sync"),
                            ("orders", "Structure orders sync"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "contracts_health_pct",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "sell_orders_health_pct",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "sell_orders_viability_pct",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "overall_health_pct",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "understocked_contracts_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("sell_gaps_count", models.PositiveIntegerField(default=0)),
                ("contract_targets", models.PositiveIntegerField(default=0)),
                ("contract_fulfilled", models.PositiveIntegerField(default=0)),
                ("sell_order_targets", models.PositiveIntegerField(default=0)),
                (
                    "sell_order_fulfilled",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "sell_order_viable_fulfilled",
                    models.PositiveIntegerField(default=0),
                ),
                ("contracts_isk", models.FloatField(default=0.0)),
                ("sell_orders_isk", models.FloatField(default=0.0)),
                ("total_isk_on_market", models.FloatField(default=0.0)),
                (
                    "contracts_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "orders_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "understocked_contracts",
                    models.JSONField(blank=True, default=list),
                ),
                ("sell_gaps", models.JSONField(blank=True, default=list)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_monitor_snapshots",
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVE market ops monitor snapshot",
                "verbose_name_plural": "EVE market ops monitor snapshots",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "-captured_at"],
                        name="market_ops_snap_loc_captured",
                    ),
                    models.Index(
                        fields=["trigger", "-captured_at"],
                        name="market_ops_snap_trig_captured",
                    ),
                ],
            },
        ),
    ]
