# Generated by Django 5.2.16 on 2026-07-22 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0097_industry_job_status_blueprint_id_idx"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("market", "0031_ops_monitor_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketOrderBookSync",
            fields=[
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="order_book_sync",
                        serialize=False,
                        to="eveonline.evelocation",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "EVE market order book sync",
                "verbose_name_plural": "EVE market order book syncs",
            },
        ),
        migrations.AddField(
            model_name="evemarketitemorder",
            name="duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ESI order duration in days (for expiry guard on inferred sales).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evemarketitemorder",
            name="issued",
            field=models.DateTimeField(
                blank=True,
                help_text="ESI order issued timestamp (for expiry guard on inferred sales).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EveMarketInferredSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                (
                    "inferred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("order_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("partial_fill", "Partial fill"),
                            ("sellout", "Sellout"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inferred_sales",
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVE market inferred sale",
                "verbose_name_plural": "EVE market inferred sales",
                "ordering": ["-inferred_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "inferred_at"],
                        name="market_infsale_loc_inferred",
                    ),
                    models.Index(
                        fields=["location", "item", "inferred_at"],
                        name="market_infsale_loc_item_inf",
                    ),
                ],
            },
        ),
    ]
