# Generated by Django 5.2.16 on 2026-07-31 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0033_evemarketinferredsale_imported_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketAttributedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField(unique=True)),
                ("type_id", models.IntegerField()),
                ("location_esi_id", models.BigIntegerField(db_index=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=32),
                ),
                ("volume_remain", models.IntegerField()),
                ("is_buy_order", models.BooleanField(default=False)),
                ("issued", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("owner_character_id", models.BigIntegerField(db_index=True)),
                (
                    "corporation_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_character_id", "is_buy_order"],
                        name="market_attrorder_owner_buy",
                    ),
                    models.Index(
                        fields=["location_esi_id", "is_buy_order"],
                        name="market_attrorder_loc_buy",
                    ),
                ],
            },
        ),
    ]
