# Generated by Django 5.2.16 on 2026-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0035_expire_stale_outstanding_contracts"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketopsmonitorsnapshot",
            name="contract_viable_fulfilled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evemarketopsmonitorsnapshot",
            name="contracts_viability_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
