# Generated by Django 5.2.16 on 2026-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0036_ops_monitor_contract_viability"),
    ]

    operations = [
        migrations.AddField(
            model_name="evemarketcontract",
            name="issuer_corporation_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
