# Generated by Django 5.2.16 on 2026-08-11 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("fittings", "0033_evefittingchangerequest_refit_set_null"),
        ("market", "0041_remove_stale_celery_beat_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FittingBuyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("purchased", "Purchased"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "stock_paste",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw inventory / Multibuy paste applied against the BOM.",
                    ),
                ),
                (
                    "include_hull",
                    models.BooleanField(
                        default=False,
                        help_text="If false, hulls are excluded from the shopping list.",
                    ),
                ),
                (
                    "jita_checked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitting_buy_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fitting buy order",
                "verbose_name_plural": "fitting buy orders",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FittingBuyJitaCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("force_refresh", models.BooleanField(default=False)),
                ("type_ids", models.JSONField(blank=True, default=list)),
                ("done_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jita_checks",
                        to="market.fittingbuyorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "fitting buy Jita check",
                "verbose_name_plural": "fitting buy Jita checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FittingBuyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("needed_qty", models.PositiveIntegerField(default=0)),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                ("buy_qty", models.PositiveIntegerField(default=0)),
                (
                    "jita_sell_volume",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "jita_sell_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=32, null=True
                    ),
                ),
                (
                    "jita_order_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual landed unit price pasted by the owner.",
                        max_digits=32,
                        null=True,
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.fittingbuyorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "fitting buy order item",
                "verbose_name_plural": "fitting buy order items",
                "ordering": ["eve_type__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "eve_type"),
                        name="unique_fitting_buy_order_item_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FittingBuyOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "swaps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {preferred_type_id, substitute_type_id, notes?} applied to this line.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fitting_buy_order_lines",
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="market.fittingbuyorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "fitting buy order line",
                "verbose_name_plural": "fitting buy order lines",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "fitting"),
                        name="unique_fitting_buy_order_fitting",
                    )
                ],
            },
        ),
    ]
