# Generated by Django 5.2.16 on 2026-09-19 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0104_fwpayouteventcode_evecharacterfwlppayout"),
        ("feed", "0015_feed_event_link_on_delete_cascade"),
        ("fittings", "0033_evefittingchangerequest_refit_set_null"),
        ("fleets", "0045_evefleet_roam_report_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "short_code",
                    models.CharField(
                        help_text="Donation tag, e.g. BLP. Used to match wallet journal entries and content tags to this campaign.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "tagline",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description_md", models.TextField(blank=True, default="")),
                (
                    "cover_image_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("public", "Public"),
                        ],
                        default="alliance",
                        max_length=16,
                    ),
                ),
                (
                    "discord_channel_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "voice_channel_ids",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "scoring",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Overrides for the default scoring weights.",
                    ),
                ),
                ("order_pool", models.JSONField(blank=True, default=dict)),
                (
                    "commander_order_text",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                (
                    "commander_order_set_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "commander_order_is_draft",
                    models.BooleanField(default=True),
                ),
                (
                    "donation_corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "donation_division",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_fleet_audience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleetaudience",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                (
                    "awarded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "scope",
                    models.CharField(
                        choices=[("campaign", "Campaign"), ("week", "Week")],
                        default="week",
                        max_length=8,
                    ),
                ),
                ("week_start", models.DateField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignComplexCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_ref", models.BigIntegerField(db_index=True)),
                ("completed_at", models.DateTimeField(db_index=True)),
                ("split_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "operational_state",
                    models.CharField(
                        choices=[
                            ("frontline", "Frontline"),
                            ("command_operations", "Command Operations"),
                            ("rearguard", "Rearguard"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("contested_factor", models.FloatField(default=1.0)),
                ("suppression_used", models.FloatField(default=1.0)),
                ("base_lp_tier", models.IntegerField(blank=True, null=True)),
                (
                    "inferred_plex_class",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "class_candidates",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complex_completions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignDailyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fleet", "Fly in a campaign fleet"),
                            ("standing_fleet", "Fly in the standing fleet"),
                            ("kill", "Get a kill"),
                            ("gang_kill", "Kill alongside enlisted pilots"),
                            ("gang", "Form or join a gang"),
                            ("plex", "Capture complexes"),
                            ("plex_class", "Capture a larger complex"),
                            ("advantage_site", "Run an advantage site"),
                            ("supply_cache", "Kill a supply cache"),
                            ("advantage_generated", "Generate advantage"),
                            ("advantage_report", "Report advantage"),
                            ("first_kill", "Get on any mail"),
                            ("first_plex", "Capture your first complex"),
                            ("weekly_active", "Be active five of seven days"),
                        ],
                        max_length=32,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("points", models.IntegerField(default=0)),
                (
                    "scope",
                    models.CharField(
                        choices=[("all", "Everyone"), ("user", "One pilot")],
                        default="all",
                        max_length=8,
                    ),
                ),
                (
                    "gap_share_pct",
                    models.FloatField(
                        default=0,
                        help_text="How much of this week's remaining gap this order closes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignEnlistment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fleet_prompt", "Fleet prompt"),
                            ("gang_ping", "Gang ping"),
                            ("web", "Web"),
                            ("admin", "Admin"),
                        ],
                        default="web",
                        max_length=16,
                    ),
                ),
                ("notify_gang_forming", models.BooleanField(default=True)),
                ("notify_standing_fleet", models.BooleanField(default=True)),
                ("notify_activity_nearby", models.BooleanField(default=False)),
                ("notify_streak_at_risk", models.BooleanField(default=True)),
                ("notify_fleets", models.BooleanField(default=True)),
                ("notify_thresholds", models.BooleanField(default=True)),
                ("notify_digest", models.BooleanField(default=True)),
                ("digest_hour", models.PositiveSmallIntegerField(default=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enlistments",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignEnlistmentCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "included_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "included_until",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "enlistment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="campaigns.campaignenlistment",
                    ),
                ),
            ],
            options={
                "ordering": ["character__character_name"],
            },
        ),
        migrations.CreateModel(
            name="CampaignEnlistmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enlisted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enlistment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="campaigns.campaignenlistment",
                    ),
                ),
            ],
            options={
                "ordering": ["-enlisted_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignFitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("srp_eligible", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fittings",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fittings.evefitting",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignKillmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("killmail_id", models.BigIntegerField(db_index=True)),
                (
                    "killmail_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("killmail_time", models.DateTimeField(db_index=True)),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                (
                    "victim_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_character_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "victim_corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_alliance_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_ship_type_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("isk_value", models.BigIntegerField(default=0)),
                ("is_pod", models.BooleanField(default=False)),
                ("is_solo", models.BooleanField(default=False)),
                ("attacker_count", models.PositiveIntegerField(default=0)),
                (
                    "enlisted_attacker_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("kill", "Kill"),
                            ("loss", "Loss"),
                            ("awox", "Awox"),
                            ("unscored", "Unscored"),
                        ],
                        db_index=True,
                        default="unscored",
                        max_length=16,
                    ),
                ),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "first_seen_via",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("on_zkillboard", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killmails",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleet",
                    ),
                ),
            ],
            options={
                "ordering": ["-killmail_time"],
            },
        ),
        migrations.CreateModel(
            name="CampaignKillmailParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("enlisted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attacker", "Attacker"),
                            ("victim", "Victim"),
                        ],
                        default="attacker",
                        max_length=8,
                    ),
                ),
                (
                    "ship_type_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("damage_done", models.BigIntegerField(default=0)),
                ("final_blow", models.BooleanField(default=False)),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="campaigns.campaignkillmail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignOrderProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="campaigns.campaigndailyorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignParticipantDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("solo_kills", models.PositiveIntegerField(default=0)),
                ("final_blows", models.PositiveIntegerField(default=0)),
                ("gang_kills", models.PositiveIntegerField(default=0)),
                ("isk_destroyed", models.BigIntegerField(default=0)),
                ("isk_lost", models.BigIntegerField(default=0)),
                ("complexes", models.PositiveIntegerField(default=0)),
                ("advantage_sites", models.PositiveIntegerField(default=0)),
                ("supply_caches", models.PositiveIntegerField(default=0)),
                ("battlefields", models.PositiveIntegerField(default=0)),
                ("advantage_generated", models.FloatField(default=0)),
                ("enemy_advantage_removed", models.FloatField(default=0)),
                ("advantage_readings", models.PositiveIntegerField(default=0)),
                ("fleets_attended", models.PositiveIntegerField(default=0)),
                ("fleets_led", models.PositiveIntegerField(default=0)),
                ("gangs_led", models.PositiveIntegerField(default=0)),
                (
                    "standing_fleet_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                ("standing_fleet_day", models.BooleanField(default=False)),
                ("orders_completed", models.PositiveIntegerField(default=0)),
                ("supply_isk_delivered", models.BigIntegerField(default=0)),
                ("project_isk_earned", models.BigIntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("active", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_days",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="CampaignParticipantStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("isk_destroyed", models.BigIntegerField(default=0)),
                ("isk_lost", models.BigIntegerField(default=0)),
                ("complexes", models.PositiveIntegerField(default=0)),
                ("advantage_sites", models.PositiveIntegerField(default=0)),
                ("advantage_generated", models.FloatField(default=0)),
                ("fleets_attended", models.PositiveIntegerField(default=0)),
                (
                    "standing_fleet_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                ("active_days", models.PositiveIntegerField(default=0)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("best_streak_days", models.PositiveIntegerField(default=0)),
                (
                    "shields_used_this_week",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("last_active_day", models.DateField(blank=True, null=True)),
                (
                    "rank_points",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "characters_included",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "characters_tracked",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "characters_lapsed",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "active_hours_utc",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "observed_prime_time",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_stats",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="CampaignStandingFleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_boss_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("handovers", models.PositiveIntegerField(default=0)),
                (
                    "uptime_minutes_today",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "uptime_minutes_prime_today",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "advert_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "voice_channel_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_fleet",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "current_boss_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                ("name", models.CharField(max_length=64)),
                ("region_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("support", "Support"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("capture", "Capture"),
                            ("defend", "Defend"),
                            ("contest", "Contest"),
                            ("none", "No goal"),
                        ],
                        default="capture",
                        max_length=16,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CampaignSiteCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("amount_lp", models.IntegerField(default=0)),
                ("event_code", models.IntegerField(db_index=True)),
                (
                    "site_kind",
                    models.CharField(
                        choices=[
                            ("complex", "Complex"),
                            ("advantage_site", "Advantage site"),
                            ("rendezvous_point", "Rendezvous Point"),
                            ("propaganda_beacon", "Propaganda Beacon"),
                            ("listening_outpost", "Listening Outpost"),
                            ("supply_cache", "Supply Cache"),
                            ("battlefield", "Battlefield"),
                            ("kill", "Kill payout"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_completions",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="campaigns.campaigncomplexcompletion",
                    ),
                ),
                (
                    "payout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacterfwlppayout",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_completions",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("campaign_started", "Campaign started"),
                            ("campaign_completed", "Campaign completed"),
                            ("system_threshold", "System near threshold"),
                            ("system_flipped", "System flipped"),
                            ("fleet_active", "Fleet active"),
                            ("hostile_gang", "Hostile gang detected"),
                            ("killmail_batch", "Kill burst"),
                            ("contested_change", "Contested change"),
                            ("gang_formed", "Gang formed"),
                            ("standing_fleet_taken", "Standing fleet taken"),
                            ("award", "Award"),
                            ("week_plan", "Weekly plan"),
                            ("milestone", "Milestone"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("friendly", "Friendly"),
                            ("hostile", "Hostile"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("campaign", "Campaign"), ("feed", "Feed")],
                        default="campaign",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "feed_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_event",
                        to="feed.feedevent",
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleets.evefleet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="campaigndailyorder",
            name="campaign_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaignsystem",
            ),
        ),
        migrations.AddField(
            model_name="campaigncomplexcompletion",
            name="campaign_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complexes",
                to="campaigns.campaignsystem",
            ),
        ),
        migrations.CreateModel(
            name="CampaignAdvantageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("our_pct", models.FloatField(default=0)),
                ("enemy_pct", models.FloatField(default=0)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("reading", "Pilot reading"),
                            ("estimate", "Estimate"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "reading_age_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("our_generated_since_reading", models.FloatField(default=0)),
                ("enemy_removed_since_reading", models.FloatField(default=0)),
                (
                    "campaign_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_state",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignAdvantageReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("our_pct", models.FloatField()),
                ("enemy_pct", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[("pilot", "Pilot"), ("manager", "Manager")],
                        default="pilot",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("held", "Held"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        max_length=8,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_readings",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignSystemArc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_state",
                    models.CharField(
                        choices=[("flip", "Flip to us"), ("hold", "Hold")],
                        default="flip",
                        max_length=8,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contest_ceiling",
                    models.FloatField(
                        default=25.0,
                        help_text="Defend: keep enemy contest under this.",
                    ),
                ),
                (
                    "advantage_floor",
                    models.FloatField(
                        default=0.0,
                        help_text="Defend: keep our net advantage above this.",
                    ),
                ),
                (
                    "vp_needed_at_start",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "campaign_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arc",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignSystemInsurgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suppression_stage",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "corruption_stage",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("inferred", "Inferred"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "campaign_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurgencies",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="CampaignSystemSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("victory_points", models.BigIntegerField(default=0)),
                (
                    "victory_points_threshold",
                    models.BigIntegerField(default=0),
                ),
                ("contested_percent", models.FloatField(default=0)),
                (
                    "occupier_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "owner_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "contested_state",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "operational_state",
                    models.CharField(
                        choices=[
                            ("frontline", "Frontline"),
                            ("command_operations", "Command Operations"),
                            ("rearguard", "Rearguard"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "campaign_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignWeekTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("victory_points", "Victory points"),
                            ("days_under_line", "Days under contest line"),
                            ("advantage", "Advantage generated"),
                        ],
                        default="victory_points",
                        max_length=24,
                    ),
                ),
                ("target", models.FloatField(default=0)),
                ("proposed", models.BooleanField(default=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("progress", models.FloatField(default=0)),
                ("pace_expected", models.FloatField(default=0)),
                (
                    "days_under_line",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("last_week_actual", models.FloatField(default=0)),
                (
                    "projected_arc_date",
                    models.DateField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_targets",
                        to="campaigns.campaignsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "-start_at"],
                name="campaigns_c_status_ca2e2c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignaward",
            constraint=models.UniqueConstraint(
                fields=("campaign", "code", "week_start"),
                name="campaign_award_week_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignenlistment",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user"), name="campaign_enlistment_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignenlistmentcharacter",
            index=models.Index(
                fields=["character", "included_until"],
                name="campaigns_c_charact_cac4c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignkillmail",
            index=models.Index(
                fields=["campaign", "-killmail_time"],
                name="campaigns_c_campaig_707292_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignkillmail",
            index=models.Index(
                fields=["campaign", "outcome", "-killmail_time"],
                name="campaigns_c_campaig_d6682c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignkillmail",
            constraint=models.UniqueConstraint(
                fields=("campaign", "killmail_id"),
                name="campaign_killmail_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignkillmailparticipant",
            constraint=models.UniqueConstraint(
                fields=("killmail", "character_id"),
                name="campaign_killmail_participant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignorderprogress",
            constraint=models.UniqueConstraint(
                fields=("order", "user"), name="campaign_order_progress_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignparticipantday",
            index=models.Index(
                fields=["campaign", "day", "-points"],
                name="campaigns_c_campaig_4dde8a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignparticipantday",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user", "day"),
                name="campaign_participant_day_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignparticipantstat",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user"),
                name="campaign_participant_stat_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignsystem",
            constraint=models.UniqueConstraint(
                fields=("campaign", "solar_system_id"),
                name="campaign_system_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsitecompletion",
            index=models.Index(
                fields=["campaign", "-occurred_at"],
                name="campaigns_c_campaig_24bad0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignevent",
            index=models.Index(
                fields=["campaign", "-occurred_at"],
                name="campaigns_c_campaig_5f6611_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigndailyorder",
            index=models.Index(
                fields=["campaign", "day"],
                name="campaigns_c_campaig_ef7e79_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigncomplexcompletion",
            constraint=models.UniqueConstraint(
                fields=("campaign", "site_ref"), name="campaign_complex_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignsystemsnapshot",
            index=models.Index(
                fields=["campaign_system", "-captured_at"],
                name="campaigns_c_campaig_08371a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignweektarget",
            constraint=models.UniqueConstraint(
                fields=("campaign_system", "week_start", "metric"),
                name="campaign_week_target_unique",
            ),
        ),
    ]
