# Generated by Django 5.2.16 on 2026-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsitecompletion",
            name="scored",
            field=models.BooleanField(
                default=True,
                help_text="False while the payout's event code is unconfirmed. The completion is still shown, it just cannot move anyone's standing.",
            ),
        ),
    ]
