# Generated by Django 5.2.16 on 2026-09-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaignsitecompletion_scored"),
        ("feed", "0015_feed_event_link_on_delete_cascade"),
        ("fleets", "0046_evefleet_campaign_alter_evefleet_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="feed_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_events",
                to="feed.feedevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignevent",
            constraint=models.UniqueConstraint(
                fields=("campaign", "feed_event"),
                name="campaign_feed_event_unique",
            ),
        ),
    ]
