# Generated by Django 5.2.16 on 2026-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_alter_campaignevent_feed_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignenlistmentcharacter",
            name="payouts_polled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Drives the polling rotation so every character is read.",
                null=True,
            ),
        ),
    ]
