# Generated by Django 5.2.16 on 2026-09-19 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaignenlistmentcharacter_payouts_polled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="campaignaward",
            constraint=models.UniqueConstraint(
                condition=models.Q(("week_start__isnull", True)),
                fields=("campaign", "code"),
                name="campaign_award_final_unique",
            ),
        ),
    ]
