# Generated by Django 5.2.16 on 2026-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaignaward_campaign_award_final_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigndailyorder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fleet", "Fly in a campaign fleet"),
                    ("standing_fleet", "Fly in the standing fleet"),
                    ("kill", "Get a kill"),
                    ("gang_kill", "Kill alongside enlisted pilots"),
                    ("gang", "Form or join a gang"),
                    ("plex", "Capture complexes"),
                    ("advantage_site", "Run an advantage site"),
                    ("supply_cache", "Kill a supply cache"),
                    ("advantage_generated", "Generate advantage"),
                    ("advantage_report", "Report advantage"),
                    ("first_kill", "Get on any mail"),
                    ("first_plex", "Capture your first complex"),
                    ("weekly_active", "Be active five of seven days"),
                ],
                max_length=32,
            ),
        ),
    ]
