# Generated by Django 5.2.16 on 2026-09-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_campaigndailyorder_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignweektarget",
            name="metric",
            field=models.CharField(
                choices=[
                    ("victory_points", "Victory points"),
                    ("days_under_line", "Days under contest line"),
                    ("advantage", "Advantage generated"),
                    ("net_advantage", "Net advantage"),
                ],
                default="victory_points",
                max_length=24,
            ),
        ),
    ]
