# Generated by Django 5.2.16 on 2026-09-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_week_target_net_advantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignadvantagestate",
            name="source",
            field=models.CharField(default="pilot", max_length=16),
        ),
        migrations.AlterField(
            model_name="campaignadvantagereading",
            name="source",
            field=models.CharField(
                choices=[
                    ("pilot", "Pilot"),
                    ("manager", "Manager"),
                    ("frontlines", "Frontlines"),
                ],
                default="pilot",
                max_length=16,
            ),
        ),
    ]
