# Generated by Django 5.2.16 on 2026-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_advantage_reading_source_frontlines"),
    ]

    operations = [
        # net_advantage never shipped; its rows become the new tasks.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model(
                "campaigns", "CampaignWeekTarget"
            )
            .objects.filter(metric="net_advantage")
            .delete(),
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="campaignsystemarc",
            name="advantage_target",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignsystemarc",
            name="advantage_task",
            field=models.CharField(
                choices=[
                    ("none", "No advantage task"),
                    ("gain", "Gain advantage (build ours up to a level)"),
                    (
                        "destroy",
                        "Destroy advantage (knock theirs down to a level)",
                    ),
                    ("maintain", "Maintain advantage (keep ours at or above)"),
                ],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="campaignweektarget",
            name="baseline",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="campaignweektarget",
            name="metric",
            field=models.CharField(
                choices=[
                    ("victory_points", "Victory points"),
                    ("days_under_line", "Days under contest line"),
                    ("advantage", "Advantage generated"),
                    ("advantage_gain", "Gain advantage"),
                    ("advantage_destroy", "Destroy advantage"),
                    ("advantage_maintain", "Maintain advantage"),
                ],
                default="victory_points",
                max_length=24,
            ),
        ),
    ]
