# Generated by Django 5.2.16 on 2026-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_advantage_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignkillmail",
            name="killer_character_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="killer_character_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="killer_faction_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="victim_faction_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
