# Generated by Django 5.2.16 on 2026-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0010_killmail_killer_and_factions"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsystem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="medium",
                max_length=8,
            ),
        ),
    ]
