# Generated by Django 5.2.16 on 2026-09-24 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_system_priority"),
        ("structures", "0019_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="kind",
            field=models.CharField(
                choices=[
                    ("faction_warfare", "Faction Warfare"),
                    ("strategic", "Strategic"),
                ],
                db_index=True,
                default="faction_warfare",
                help_text="Display preset. Does not change how activity is matched.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="is_capital",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="is_structure",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="campaignparticipantday",
            name="capital_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignparticipantday",
            name="capital_losses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignparticipantday",
            name="structure_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignparticipantday",
            name="structure_losses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CampaignStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "structure_type",
                    models.CharField(
                        choices=[
                            ("astrahus", "Astrahus"),
                            ("fortizar", "Fortizar"),
                            ("keepstar", "Keepstar"),
                            ("raitaru", "Raitaru"),
                            ("azbel", "Azbel"),
                            ("sotiyo", "Sotiyo"),
                            ("athanor", "Athanor"),
                            ("tatara", "Tatara"),
                            ("tenebrex_cyno_jammer", "Tenebrex Cyno Jammer"),
                            ("pharolux_cyno_beacon", "Pharolux Cyno Beacon"),
                            ("ansiblex_jump_gate", "Ansiblex Jump Gate"),
                            ("orbital_skyhook", "Orbital Skyhook"),
                            ("metenox_moon_drill", "Metenox Moon Drill"),
                            (
                                "player_owned_customs_office",
                                "Player Owned Customs Office",
                            ),
                            ("player_owned_starbase", "Player Owned Starbase"),
                            ("mercenary_den", "Mercenary Den"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ESI type id when known; used to match killmails.",
                        null=True,
                    ),
                ),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                ("system_name", models.CharField(max_length=128)),
                (
                    "corporation_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ESI corporation id of the structure's legal owner.",
                        null=True,
                    ),
                ),
                (
                    "corporation_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "alliance_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "alliance_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "related_alliance_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Inferred enemy alliance (e.g. CVA when the owner is an alt corp).",
                        null=True,
                    ),
                ),
                (
                    "related_alliance_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Scout-entered related alliance name.",
                        max_length=255,
                    ),
                ),
                (
                    "eve_structure_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "fitting",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Scouted structure fit paste (high slots, services, etc.).",
                    ),
                ),
                (
                    "reinforce_hour",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="EVE reinforce hour (0–23), e.g. 18 for 18:00.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("anchored", "Anchored"),
                            ("reinforced", "Reinforced"),
                            ("destroyed", "Destroyed"),
                            ("unanchored", "Unanchored"),
                        ],
                        db_index=True,
                        default="anchored",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("recon", "Recon"),
                            ("timer", "Timer"),
                            ("killmail", "Killmail"),
                        ],
                        default="recon",
                        max_length=16,
                    ),
                ),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destroyed_structures",
                        to="campaigns.campaignkillmail",
                    ),
                ),
                (
                    "timer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_structures",
                        to="structures.evestructuretimer",
                    ),
                ),
            ],
            options={
                "ordering": ["system_name", "name"],
            },
        ),
        migrations.AddField(
            model_name="campaignkillmail",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="killmails",
                to="campaigns.campaignstructure",
            ),
        ),
        migrations.CreateModel(
            name="CampaignOpponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alliance_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("faction_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "ticker",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opponents",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("alliance_id__isnull", False)),
                        fields=("campaign", "alliance_id"),
                        name="campaign_opponent_alliance_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaignstructure",
            index=models.Index(
                fields=["campaign", "status"],
                name="campaigns_c_campaig_7c295b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignstructure",
            index=models.Index(
                fields=["campaign", "solar_system_id"],
                name="campaigns_c_campaig_d976e0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignstructure",
            constraint=models.UniqueConstraint(
                fields=(
                    "campaign",
                    "solar_system_id",
                    "structure_type",
                    "name",
                ),
                name="campaign_structure_identity_unique",
            ),
        ),
    ]
