# Generated by Django 5.2.16 on 2026-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_campaignstructure_corporation_related_alliance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignweektarget",
            name="metric",
            field=models.CharField(
                choices=[
                    ("victory_points", "Victory points"),
                    ("days_under_line", "Days under contest line"),
                    ("advantage", "Advantage generated"),
                    ("advantage_gain", "Gain advantage"),
                    ("advantage_destroy", "Destroy advantage"),
                    ("advantage_maintain", "Maintain advantage"),
                    ("structures_reported", "Structures reported"),
                ],
                default="victory_points",
                max_length=24,
            ),
        ),
    ]
