# Generated by Django 5.2.16 on 2026-09-24 20:41

import django.db.models.deletion
from django.db import migrations, models


def mark_none_goal_systems_as_ops(apps, schema_editor):
    CampaignSystem = apps.get_model("campaigns", "CampaignSystem")
    CampaignSystem.objects.filter(goal="none").update(is_fw_objective=False)


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_week_target_structures_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsystem",
            name="is_fw_objective",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="FW contest objective (plex/VP/advantage). Off = ops theater only (structure hunt / member guide; no kill scoring).",
            ),
        ),
        migrations.RunPython(
            mark_none_goal_systems_as_ops, migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name="CampaignArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("constellation", "Constellation"),
                            ("region", "Region"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "constellation_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "region_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "constellation")),
                        fields=("campaign", "scope", "constellation_id"),
                        name="campaign_area_constellation_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "region")),
                        fields=("campaign", "scope", "region_id"),
                        name="campaign_area_region_unique",
                    ),
                ],
            },
        ),
    ]
