# Generated by Django 5.2.17 on 2026-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_fw_objective_and_campaign_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignsystem",
            name="goal",
            field=models.CharField(
                choices=[
                    ("capture", "Capture"),
                    ("defend", "Defend"),
                    ("contest", "Contest"),
                    ("scout", "Scout"),
                    ("none", "No goal"),
                ],
                default="capture",
                max_length=16,
            ),
        ),
    ]
