# Generated by Django 5.2.17 on 2026-09-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_system_goal_scout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CampaignStandingFleet",
        ),
    ]
