# Generated by Django 5.2.17 on 2026-09-27 16:36

import django.db.models.deletion
from django.db import migrations, models


def link_theater_lookups(apps, schema_editor):
    CampaignSystem = apps.get_model("campaigns", "CampaignSystem")
    CampaignArea = apps.get_model("campaigns", "CampaignArea")
    EveSolarSystem = apps.get_model("eveuniverse", "EveSolarSystem")
    EveConstellation = apps.get_model("eveuniverse", "EveConstellation")
    EveRegion = apps.get_model("eveuniverse", "EveRegion")

    system_ids = {
        row.id: row
        for row in EveSolarSystem.objects.filter(
            id__in=CampaignSystem.objects.values_list(
                "solar_system_id", flat=True
            )
        )
    }
    for theater in CampaignSystem.objects.filter(
        eve_solar_system__isnull=True
    ):
        linked = system_ids.get(theater.solar_system_id)
        if linked:
            theater.eve_solar_system_id = linked.id
            theater.save(update_fields=["eve_solar_system_id"])

    constellation_ids = {
        row.id: row
        for row in EveConstellation.objects.filter(
            id__in=CampaignArea.objects.filter(
                scope="constellation"
            ).values_list("constellation_id", flat=True)
        )
    }
    for area in CampaignArea.objects.filter(
        scope="constellation", eve_constellation__isnull=True
    ):
        linked = constellation_ids.get(area.constellation_id)
        if linked:
            area.eve_constellation_id = linked.id
            area.save(update_fields=["eve_constellation_id"])

    region_ids = {
        row.id: row
        for row in EveRegion.objects.filter(
            id__in=CampaignArea.objects.filter(scope="region").values_list(
                "region_id", flat=True
            )
        )
    }
    for area in CampaignArea.objects.filter(
        scope="region", eve_region__isnull=True
    ):
        linked = region_ids.get(area.region_id)
        if linked:
            area.eve_region_id = linked.id
            area.save(update_fields=["eve_region_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0018_remove_campaign_standing_fleet"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignarea",
            name="eve_constellation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.eveconstellation",
            ),
        ),
        migrations.AddField(
            model_name="campaignarea",
            name="eve_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.everegion",
            ),
        ),
        migrations.AddField(
            model_name="campaignarea",
            name="goal",
            field=models.CharField(
                choices=[
                    ("capture", "Capture"),
                    ("defend", "Defend"),
                    ("contest", "Contest"),
                    ("scout", "Scout"),
                    ("none", "No goal"),
                ],
                default="scout",
                help_text=(
                    "What members should do in this constellation or region."
                ),
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="campaignarea",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="medium",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="campaignsystem",
            name="eve_solar_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.evesolarsystem",
            ),
        ),
        migrations.RunPython(link_theater_lookups, migrations.RunPython.noop),
    ]
