# Generated by Django 5.1 on 2024-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LpStoreItem",
            fields=[
                (
                    "type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty_1d", models.IntegerField(default=0)),
                ("qty_7d", models.IntegerField(default=0)),
                ("qty_30d", models.IntegerField(default=0)),
                ("blueprint_id", models.IntegerField(null=True)),
            ],
        ),
    ]
