# Generated by Django 5.1 on 2024-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lpconversion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lpstoreitem",
            name="jita_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="lpstoreitem",
            name="store_isk",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lpstoreitem",
            name="store_lp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lpstoreitem",
            name="store_qty",
            field=models.IntegerField(default=0),
        ),
    ]
