# Generated by Django 5.1 on 2024-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lpconversion",
            "0002_lpstoreitem_jita_price_lpstoreitem_store_isk_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lpstoreitem",
            name="jita_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15
            ),
        ),
    ]
