# Generated by Django 5.1.2 on 2024-10-12 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lpconversion", "0004_lpsellorder_lpbuyoffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LpBuyOffer",
            new_name="LpSellOrderPurchase",
        ),
    ]
