# Generated by Django 5.1.2 on 2026-02-08

from django.db import migrations, models


def copy_corporation_fk_to_id(apps, schema_editor):
    """Copy EVE corporation_id from related EveCorporation onto temp field."""
    EveCorporationApplication = apps.get_model(
        "applications", "EveCorporationApplication"
    )
    EveCorporation = apps.get_model("eveonline", "EveCorporation")

    for app in EveCorporationApplication.objects.all():
        if app.corporation_id:  # FK column: stores EveCorporation.pk
            corp = EveCorporation.objects.filter(pk=app.corporation_id).first()
            if corp is not None:
                app._corporation_id = corp.corporation_id
                app.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporationapplication",
            name="_corporation_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_corporation_fk_to_id, noop),
        migrations.RemoveField(
            model_name="evecorporationapplication",
            name="corporation",
        ),
        migrations.RenameField(
            model_name="evecorporationapplication",
            old_name="_corporation_id",
            new_name="corporation_id",
        ),
    ]
