# Generated by Django 5.1.2 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_evecorporationapplication_corporation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecorporationapplication",
            name="corporation_id",
            field=models.BigIntegerField(),
        ),
    ]
