# Generated by Django 5.2.16 on 2026-09-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0003_alter_evecorporationapplication_corporation_id",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evecorporationapplication",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
