# Generated by Django 5.2.16 on 2026-08-20 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveSmallIntegerField(help_text="1-4")),
                (
                    "definition_key",
                    models.CharField(
                        help_text="Key into surveys.definitions.SURVEY_DEFINITIONS.",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spotlight_questions",
                    models.JSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-quarter"],
            },
        ),
        migrations.CreateModel(
            name="SurveyChangelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("body_markdown", models.TextField(blank=True)),
                (
                    "published",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog_entries",
                        to="surveys.surveycampaign",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Survey changelog entries",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_key",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "segment_key",
                    models.CharField(
                        db_index=True, default="all", max_length=64
                    ),
                ),
                ("n", models.PositiveIntegerField(default=0)),
                ("mean", models.FloatField(blank=True, null=True)),
                ("distribution", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregates",
                        to="surveys.surveycampaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "corporation_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128
                    ),
                ),
                ("tribe_names", models.JSONField(blank=True, default=list)),
                (
                    "prime_time",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                ("tenure_days", models.IntegerField(blank=True, null=True)),
                (
                    "tenure_cohort",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                (
                    "activity_tier",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                ("role_flags", models.JSONField(blank=True, default=list)),
                (
                    "context_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.surveycampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_key",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("choice_value", models.CharField(blank=True, max_length=255)),
                ("json_value", models.JSONField(blank=True, null=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.surveyresponse",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="surveycampaign",
            constraint=models.UniqueConstraint(
                fields=("year", "quarter"), name="unique_survey_per_quarter"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestionaggregate",
            constraint=models.UniqueConstraint(
                fields=("campaign", "question_key", "segment_key"),
                name="unique_aggregate_per_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user"),
                name="unique_response_per_user_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question_key"),
                name="unique_answer_per_question",
            ),
        ),
    ]
