# Generated by Django 5.0.4 on 2024-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EveFitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("ship_name", models.CharField(max_length=255)),
                ("ship_type_id", models.IntegerField()),
                ("ship_type_name", models.CharField(max_length=255)),
                ("eft_format", models.TextField()),
                ("multibuy_format", models.TextField(blank=True, null=True)),
                (
                    "latest_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=36
                    ),
                ),
                ("latest_version", models.CharField(max_length=255)),
            ],
        ),
    ]
