# Generated by Django 5.0.4 on 2024-04-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefitting",
            name="latest_price",
        ),
        migrations.RemoveField(
            model_name="evefitting",
            name="multibuy_format",
        ),
        migrations.RemoveField(
            model_name="evefitting",
            name="ship_name",
        ),
        migrations.RemoveField(
            model_name="evefitting",
            name="ship_type_id",
        ),
        migrations.RemoveField(
            model_name="evefitting",
            name="ship_type_name",
        ),
    ]
