# Generated by Django 5.0.4 on 2024-04-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0002_remove_evefitting_latest_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveDoctrine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Armor"),
                            ("shield", "Shield"),
                            ("kitchen_sink", "Kitchen Sink"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EveFittingTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EveDoctrineFitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("support", "Support"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fittings.evedoctrine",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fittings.evefitting",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evefitting",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="fittings.evefittingtag"
            ),
        ),
    ]
