# Generated by Django 5.0.4 on 2024-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fittings",
            "0003_evedoctrine_evefittingtag_evedoctrinefitting_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="ship_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
