# Generated by Django 5.0.6 on 2024-06-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0004_evefitting_ship_id"),
        ("groups", "0014_sig_discord_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evedoctrine",
            name="sigs",
            field=models.ManyToManyField(blank=True, to="groups.sig"),
        ),
    ]
