# Generated by Django 5.1 on 2024-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0005_evedoctrine_sigs"),
    ]

    operations = [
        migrations.AddField(
            model_name="evedoctrine",
            name="ideal_fleet_size",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="evedoctrinefitting",
            name="ideal_ship_count",
            field=models.IntegerField(default=1),
        ),
    ]
