# Generated by Django 5.1 on 2024-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0006_evedoctrine_ideal_fleet_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evedoctrine",
            name="type",
            field=models.CharField(
                choices=[
                    ("skirmish", "Skirmish"),
                    ("strategic", "Strategic"),
                    ("specialized", "Specialized"),
                ],
                max_length=255,
            ),
        ),
    ]
