# Generated by Django 5.1.2 on 2024-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0007_alter_evedoctrine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="aliases",
            field=models.TextField(blank=True, null=True),
        ),
    ]
