# Generated by Django 5.1.2 on 2024-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0008_evefitting_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefitting",
            name="latest_version",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
