# Generated by Django 5.1.2 on 2025-01-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0009_alter_evefitting_latest_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="minimum_pod",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evefitting",
            name="recommended_pod",
            field=models.TextField(blank=True),
        ),
    ]
