# Generated by Django 5.1.9 on 2025-06-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0010_evefitting_minimum_pod_evefitting_recommended_pod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evedoctrine",
            name="type",
            field=models.CharField(
                choices=[
                    ("skirmish", "Skirmish"),
                    ("strategic", "Strategic"),
                    ("specialized", "Specialized"),
                    ("casual", "Casual"),
                ],
                max_length=255,
            ),
        ),
    ]
