# Generated by Django 5.2.9 on 2026-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0011_alter_evedoctrine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evedoctrine",
            name="type",
            field=models.CharField(
                choices=[
                    ("skirmish", "Skirmish"),
                    ("strategic", "Strategic"),
                    ("specialized", "Specialized"),
                    ("casual", "Casual"),
                    ("faction_warfare", "Faction warfare"),
                    ("nullsec", "Nullsec"),
                ],
                max_length=255,
            ),
        ),
    ]
