# Generated by Django 5.2.9 on 2026-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0069_evealliance_eveonline_e_name_44ecf1_idx_and_more"),
        ("fittings", "0012_alter_evedoctrine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="evedoctrine",
            name="locations",
            field=models.ManyToManyField(
                blank=True, to="eveonline.evelocation"
            ),
        ),
    ]
