# Generated by Django 5.2.9 on 2026-01-25 14:59

from django.db import migrations


def migrate_doctrine_types(apps, schema_editor):
    """
    Migrate old doctrine types to new types:
    - strategic -> strategic (no change)
    - casual -> training
    - Everything else (skirmish, specialized, faction_warfare, nullsec) -> non_strategic
    """
    EveDoctrine = apps.get_model("fittings", "EveDoctrine")
    
    # Map casual to training
    EveDoctrine.objects.filter(type="casual").update(type="training")
    
    # Map everything else that's not strategic to non_strategic
    old_types = ["skirmish", "specialized", "faction_warfare", "nullsec"]
    for old_type in old_types:
        EveDoctrine.objects.filter(type=old_type).update(type="non_strategic")


def reverse_migrate_doctrine_types(apps, schema_editor):
    """
    Reverse migration - map back to old types.
    Note: This is a best-effort reverse, as we can't determine the original type.
    We'll map training back to casual, and non_strategic to skirmish.
    """
    EveDoctrine = apps.get_model("fittings", "EveDoctrine")
    
    # Reverse training -> casual
    EveDoctrine.objects.filter(type="training").update(type="casual")
    
    # Reverse non_strategic -> skirmish (best guess)
    EveDoctrine.objects.filter(type="non_strategic").update(type="skirmish")


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0013_evedoctrine_locations"),
    ]

    operations = [
        migrations.RunPython(migrate_doctrine_types, reverse_migrate_doctrine_types),
    ]
