# Generated by Django 5.2.9 on 2026-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0014_migrate_doctrine_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evedoctrine",
            name="type",
            field=models.CharField(
                choices=[
                    ("non_strategic", "Non strategic"),
                    ("training", "Training"),
                    ("strategic", "Strategic"),
                ],
                max_length=255,
            ),
        ),
    ]
