# Generated by Django 5.2.9 on 2026-01-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0015_alter_evedoctrine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evedoctrine",
            name="ideal_fleet_size",
        ),
        migrations.RemoveField(
            model_name="evedoctrinefitting",
            name="ideal_ship_count",
        ),
    ]
