# Generated by Django 5.1.2 on 2026-02-07 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0016_remove_evedoctrine_ideal_fleet_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFittingRefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("eft_format", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refits",
                        to="fittings.evefitting",
                    ),
                ),
            ],
            options={
                "ordering": ["base_fitting", "name"],
                "unique_together": {("base_fitting", "name")},
            },
        ),
    ]
