# Generated by Django 5.1.2 on 2026-02-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0017_evefittingrefit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evefitting",
            name="tags",
        ),
        migrations.DeleteModel(
            name="EveFittingTag",
        ),
    ]
