# Generated by Django 5.1.15 on 2026-04-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0019_remove_evedoctrine_sigs"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFittingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "superseded_version_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("ship_id", models.IntegerField()),
                ("eft_format", models.TextField()),
                ("description", models.TextField()),
                ("aliases", models.TextField(blank=True, null=True)),
                ("minimum_pod", models.TextField(blank=True)),
                ("recommended_pod", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="fittings.evefitting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
