# Generated by Django 5.1.15 on 2026-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0020_eve_fitting_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="deleted",
            field=models.DateTimeField(
                db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="evefitting",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="evefitting",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="evefitting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("name",),
                name="unique_evefitting_name_not_deleted",
            ),
        ),
    ]
