# Generated by Django 5.1.15 on 2026-04-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0021_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="evefittinghistory",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
