# Generated by Django 5.1.15 on 2026-05-25 18:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_doctrine_types_and_versions(apps, schema_editor):
    EveDoctrine = apps.get_model("fittings", "EveDoctrine")
    for doctrine in EveDoctrine.objects.all():
        updated = []
        if doctrine.type == "training":
            doctrine.type = "non_strategic"
            updated.append("type")
        if not doctrine.latest_version:
            doctrine.latest_version = str(uuid.uuid4())
            updated.append("latest_version")
        if updated:
            doctrine.save(update_fields=updated)


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0024_merge_fitting_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evedoctrine",
            options={
                "permissions": [
                    (
                        "change_doctrine_non_strategic",
                        "Can propose non strategic doctrine changes",
                    ),
                    (
                        "approve_doctrine_non_strategic",
                        "Can approve non strategic doctrine changes",
                    ),
                    (
                        "change_doctrine_strategic",
                        "Can propose strategic doctrine changes",
                    ),
                    (
                        "approve_doctrine_strategic",
                        "Can approve strategic doctrine changes",
                    ),
                    (
                        "change_doctrine_fitting_non_strategic",
                        "Can propose non strategic doctrine fitting changes",
                    ),
                    (
                        "approve_doctrine_fitting_non_strategic",
                        "Can approve non strategic doctrine fitting changes",
                    ),
                    (
                        "change_doctrine_fitting_strategic",
                        "Can propose strategic doctrine fitting changes",
                    ),
                    (
                        "approve_doctrine_fitting_strategic",
                        "Can approve doctrine fittings (strategic)",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="evedoctrine",
            name="latest_version",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            migrate_doctrine_types_and_versions,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="evedoctrine",
            name="type",
            field=models.CharField(
                choices=[
                    ("experimental", "Experimental"),
                    ("non_strategic", "Non strategic"),
                    ("strategic", "Strategic"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="EveDoctrineChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("tier", models.CharField(max_length=32)),
                (
                    "change_kind",
                    models.CharField(default="full", max_length=64),
                ),
                ("payload", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="fittings.evedoctrine",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_doctrine_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_doctrine_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="EveDoctrineHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "superseded_version_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("composition", models.JSONField(default=dict)),
                ("location_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="fittings.evedoctrine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EveFittingChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("tier", models.CharField(max_length=32)),
                ("change_kind", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "refit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="fittings.evefittingrefit",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fitting_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_fitting_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
