# Generated by Django 5.1.15 on 2026-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0025_doctrine_approval_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFittingPod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(
                        db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower numbers are higher precedence when multiple pods apply.",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "pod_format",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Newline-separated implant names.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escape_frigate_fittings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="escape_pod_configs",
                        to="fittings.evefitting",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="evefitting",
            name="pods",
            field=models.ManyToManyField(
                blank=True,
                related_name="fittings",
                to="fittings.evefittingpod",
            ),
        ),
    ]
