# Generated by Django 5.1.15 on 2026-07-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0011_extend_industry_activites"),
        ("fittings", "0028_backfill_evefitting_names_from_eft"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFittingModuleSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional context for seeders (e.g. why this swap is acceptable).",
                        max_length=255,
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_substitutions",
                        to="fittings.evefitting",
                    ),
                ),
                (
                    "preferred_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                        verbose_name="If unavailable",
                    ),
                ),
                (
                    "substitute_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                        verbose_name="Buy instead",
                    ),
                ),
            ],
            options={
                "verbose_name": "module substitution",
                "verbose_name_plural": "module substitutions",
                "ordering": ["preferred_module__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fitting", "preferred_module"),
                        name="unique_fitting_preferred_module_substitution",
                    )
                ],
            },
        ),
    ]
