# Generated by Django 5.2.16 on 2026-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0030_evefitting_tags_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="known_key",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "guide.navy-destroyer.cat-blaster",
                        "Blaster Catalyst Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.cat-10mn",
                        "10mn Catalyst Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.coercer-dual-neuts-mwd",
                        "2X Neut Coercer Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.coercer-mwd-scram-brawl",
                        "Pulse Coercer Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.coercer-kite-beams",
                        "Beam Coercer Navy Issue",
                    ),
                    ("guide.navy-destroyer.tfi-ac", "AC Thrasher Fleet Issue"),
                    (
                        "guide.navy-destroyer.tfi-arty",
                        "Arty Thrasher Fleet Issue",
                    ),
                    (
                        "guide.navy-destroyer.corm-dual-masb-neutrons",
                        "Dual MASB Cormorant Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.corm-buffer",
                        "Buffer Cormorant Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.corm-10mn",
                        "10mn Cormorant Navy Issue",
                    ),
                    (
                        "guide.navy-destroyer.talfi-10mn-rocket",
                        "10mn Talwar Fleet Issue",
                    ),
                    ("guide.navy-destroyer.algos-10mn", "10mn Algos"),
                    ("guide.navy-destroyer.algos-brawl", "Brawl Algos"),
                    ("guide.navy-destroyer.algos-farm", "Farm Algos"),
                    ("guide.navy-destroyer.thrasher-arty", "Arty Thrasher"),
                    ("guide.navy-destroyer.thrasher-ac", "AC Thrasher"),
                    ("guide.navy-destroyer.coercer-brawl", "Brawl Coercer"),
                    ("guide.navy-destroyer.dragoon-neut", "Neut Dragoon"),
                    (
                        "guide.navy-frigate.hookbill-shield",
                        "Scram Kite — Shield",
                    ),
                    (
                        "guide.navy-frigate.hookbill-control",
                        "Scram Kite — Control",
                    ),
                    ("guide.navy-frigate.comet-blaster", "Blaster Comet"),
                    ("guide.navy-frigate.comet-rail", "Rail Comet"),
                    ("guide.navy-frigate.slicer-beam", "Beam Slicer"),
                    ("guide.navy-frigate.firetail-arty", "Arty Firetail"),
                    (
                        "guide.navy-frigate.vigil-web-kite",
                        "Web Kite Vigil Fleet",
                    ),
                    ("guide.navy-frigate.tristan-brawl", "Brawl Tristan"),
                    ("guide.navy-frigate.breacher-masb", "MASB Breacher"),
                    (
                        "guide.fw-cruiser.arby-long-kite",
                        "Long Point Arbitrator",
                    ),
                    ("guide.fw-cruiser.arby-brawl", "Brawl Arbitrator"),
                    (
                        "guide.fw-cruiser.arby-td-support",
                        "TD Support Arbitrator",
                    ),
                    (
                        "guide.fw-cruiser.augni-polarized",
                        "Polarized Augoror Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.augni-kite-pulse",
                        "Pulse Augoror Navy Issue",
                    ),
                    ("guide.fw-cruiser.maller-pulse", "Pulse Maller"),
                    ("guide.fw-cruiser.omen-quad-light", "Beam Omen"),
                    ("guide.fw-cruiser.omen-kite-pulse", "Pulse Omen"),
                    ("guide.fw-cruiser.omen-sniper", "Sniper Omen"),
                    (
                        "guide.fw-cruiser.omenni-mid-kite",
                        "Kite Omen Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.omenni-mid-sniper",
                        "Beam Omen Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.caracalni-ham",
                        "HAM Caracal Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.ospreyni-ham-neut",
                        "2X Neut HAM Osprey Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.ospreyni-rhml-kite",
                        "RLML Osprey Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.eni-blaster",
                        "Blaster Exequror Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.eni-250rail",
                        "250mm Rail Exequror Navy Issue",
                    ),
                    (
                        "guide.fw-cruiser.eni-dual-plate-electron",
                        "Dual Plate Electron Exequror Navy Issue",
                    ),
                    ("guide.fw-cruiser.vexor-neut-plate", "Neut Vexor"),
                    ("guide.fw-cruiser.vexor-blaster-neut", "Blaster Vexor"),
                    (
                        "guide.fw-cruiser.vni-dual-rep",
                        "Dual Rep Vexor Navy Issue",
                    ),
                    ("guide.fw-cruiser.bellicose-ham", "HAM Bellicose"),
                    ("guide.fw-cruiser.bellicose-xlsb", "XLASB HAM Bellicose"),
                    (
                        "guide.fw-cruiser.scythefi-dual-prop-ac",
                        "Dual Prop Scythe Fleet Issue",
                    ),
                    (
                        "guide.fw-cruiser.scythefi-rlml-armor",
                        "Armor RLML Scythe Fleet Issue",
                    ),
                    (
                        "guide.fw-cruiser.scythefi-rlml-xlsb",
                        "RLML XLASB Scythe Fleet Issue",
                    ),
                    ("guide.fw-cruiser.stabber-xlsb", "AB XLASB Stabber"),
                    ("guide.fw-cruiser.stabber-vulcan-kite", "Vulcan Stabber"),
                    (
                        "guide.fw-cruiser.stabberfi-dual-prop",
                        "Dual Prop Stabber Fleet Issue",
                    ),
                ],
                help_text="Optional system meaning, e.g. guide.fw-cruiser.omen-kite-pulse.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="evefitting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True), ("known_key__isnull", False)
                ),
                fields=("known_key",),
                name="unique_evefitting_known_key_not_deleted",
            ),
        ),
    ]
