# Generated by Django 5.2.16 on 2026-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0031_evefitting_known_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefittingrefit",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Set when the base fitting EFT changes; clear after "
                    "reviewing this refit."
                ),
            ),
        ),
    ]
