# Generated by Django 5.2.16 on 2026-08-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fittings", "0032_evefittingrefit_needs_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evefittingchangerequest",
            name="refit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_requests",
                to="fittings.evefittingrefit",
            ),
        ),
    ]
