# Generated by Django 5.1.15 on 2026-04-05 18:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Stable initial version for the seeded SRP onboarding program (dev/CI).
SRP_INITIAL_VERSION = uuid.UUID("8c3e9b2a-4d1f-5e6c-9b0a-123456789abc")


def seed_onboarding_programs(apps, schema_editor):
    OnboardingProgram = apps.get_model("onboarding", "OnboardingProgram")
    OnboardingProgram.objects.get_or_create(
        slug="srp",
        defaults={"version": SRP_INITIAL_VERSION},
    )


def unseed_onboarding_programs(apps, schema_editor):
    OnboardingProgram = apps.get_model("onboarding", "OnboardingProgram")
    OnboardingProgram.objects.filter(slug="srp").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProgram",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="UserOnboardingAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acknowledged_version", models.UUIDField()),
                ("acknowledged_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="onboarding.onboardingprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "program")},
            },
        ),
        migrations.RunPython(
            seed_onboarding_programs, unseed_onboarding_programs
        ),
    ]
