# Generated by Django 5.2.16 on 2026-07-31 23:26

import buyback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0100_merge_0099_esi_deleted_executor_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuybackContract",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eveonline.evecorporationcontract",),
        ),
        migrations.CreateModel(
            name="EveBuybackSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignee_name",
                    models.CharField(
                        default="Minmatar Extraction Company",
                        help_text="In-game name to contract to (clipboard).",
                        max_length=255,
                    ),
                ),
                (
                    "accepted_categories",
                    models.JSONField(
                        blank=True,
                        default=buyback.models._default_accepted_categories,
                        help_text="List of category labels shown on the buyback page.",
                    ),
                ),
                (
                    "rate_rules",
                    models.JSONField(
                        blank=True,
                        default=buyback.models._default_rate_rules,
                        help_text="Pricing hints: ore_refine, ore_jita_buy, p1_jita_buy_cap, etc.",
                    ),
                ),
                (
                    "exclusions",
                    models.JSONField(
                        blank=True,
                        default=buyback.models._default_exclusions,
                        help_text="List of items/categories not accepted.",
                    ),
                ),
                (
                    "discord_thread_url",
                    models.URLField(
                        blank=True,
                        default="https://discord.com/channels/1041384161505722368/1528803812599402577",
                    ),
                ),
                (
                    "leading_text",
                    models.TextField(
                        blank=True,
                        default="Alliance buyback via Minmatar Extraction Company. Contract compressed ore, PI, and salvage at Amo — priced with Janice and paid within ~24 hours.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyback_settings",
                        to="eveonline.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyback settings",
                "verbose_name_plural": "Buyback settings",
            },
        ),
    ]
