# Generated by Django 5.2.16 on 2026-08-01 00:50

import buyback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0001_initial"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="accepted_categories",
            field=models.JSONField(
                blank=True, default=buyback.models._default_accepted_categories
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="assignee_name",
            field=models.CharField(
                default="Minmatar Extraction Company", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="exclusions",
            field=models.JSONField(
                blank=True, default=buyback.models._default_exclusions
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="leading_text",
            field=models.TextField(
                blank=True,
                default="Alliance buyback via Minmatar Extraction Company. Paste your items for an instant offer, then contract compressed highsec ore and PI at Amo — paid within ~24 hours.",
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="rate_rules",
            field=models.JSONField(
                blank=True, default=buyback.models._default_rate_rules
            ),
        ),
        migrations.CreateModel(
            name="BuybackAcceptedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ore", "Ore"),
                            ("p1", "P1"),
                            ("pi_other", "PI (P2+)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eve_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyback_accepted_item",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyback accepted item",
                "verbose_name_plural": "Buyback accepted items",
                "ordering": ["category", "eve_type__name"],
            },
        ),
    ]
