# Generated by Django 5.2.16 on 2026-08-01 01:01

from django.db import migrations, models

GROUP_P2 = 1034
GROUP_P3 = 1040
GROUP_P4 = 1041


def split_pi_other(apps, schema_editor):
    BuybackAcceptedItem = apps.get_model("buyback", "BuybackAcceptedItem")
    for item in BuybackAcceptedItem.objects.filter(
        category="pi_other"
    ).iterator():
        group_id = getattr(item.eve_type, "eve_group_id", None)
        if group_id == GROUP_P2:
            item.category = "p2"
        elif group_id == GROUP_P3:
            item.category = "p3"
        elif group_id == GROUP_P4:
            item.category = "p4"
        else:
            item.category = "p2"
        item.save(update_fields=["category"])


def merge_pi_tiers(apps, schema_editor):
    BuybackAcceptedItem = apps.get_model("buyback", "BuybackAcceptedItem")
    BuybackAcceptedItem.objects.filter(category__in=["p2", "p3", "p4"]).update(
        category="pi_other"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0003_seed_accepted_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buybackaccepteditem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ore", "Ore"),
                    ("p1", "P1"),
                    ("p2", "P2"),
                    ("p3", "P3"),
                    ("p4", "P4"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(split_pi_other, merge_pi_tiers),
    ]
