# Generated by Django 5.2.16 on 2026-08-10 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0004_split_pi_categories"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuybackHangarSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField(db_index=True)),
                ("quantities", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Buyback hangar snapshot",
                "verbose_name_plural": "Buyback hangar snapshots",
                "ordering": ["-taken_at"],
            },
        ),
        migrations.AddField(
            model_name="buybackaccepteditem",
            name="demand_quantity",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buybackaccepteditem",
            name="demand_status",
            field=models.CharField(
                choices=[
                    ("surplus", "Surplus"),
                    ("low", "Low"),
                    ("high", "High"),
                ],
                default="surplus",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="buybackaccepteditem",
            name="metrics_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buybackaccepteditem",
            name="stockpile_quantity",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evebuybacksettings",
            name="stockpile_hangar_flag",
            field=models.CharField(
                default="CorpSAG1",
                help_text="ESI location_flag for kept stock (e.g. CorpSAG1).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="evebuybacksettings",
            name="stockpile_include_deliveries",
            field=models.BooleanField(
                default=True,
                help_text="Include CorpDeliveries at the structure in on-hand stock.",
            ),
        ),
        migrations.AddField(
            model_name="evebuybacksettings",
            name="stockpile_office_id",
            field=models.BigIntegerField(
                default=1055001268953,
                help_text="Office location_id for the kept-stock hangar.",
            ),
        ),
        migrations.AddField(
            model_name="evebuybacksettings",
            name="stockpile_structure_id",
            field=models.BigIntegerField(
                default=1040765104287,
                help_text="Structure location_id for CorpDeliveries (Amo).",
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="leading_text",
            field=models.TextField(
                blank=True,
                default="Alliance buyback via Minmatar Extraction Company. We pay full Jita buy for materials our industry supply chain is importing for recent orders, and 90% for other accepted ore and PI. Paste your items for an instant offer, then contract at Amo — paid within ~24 hours.",
            ),
        ),
        migrations.CreateModel(
            name="BuybackLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("in_contract", "In (contract)"),
                            ("sold_order", "Sold (sell order)"),
                            ("sold_contract", "Sold (contract)"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity", models.BigIntegerField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "isk_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyback_ledger_entries",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyback ledger entry",
                "verbose_name_plural": "Buyback ledger entries",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["occurred_at"],
                        name="buyback_buy_occurre_e27d00_idx",
                    ),
                    models.Index(
                        fields=["reason", "occurred_at"],
                        name="buyback_buy_reason_dbb3d7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reason", "source_id", "eve_type"),
                        name="buyback_ledger_reason_source_type_uniq",
                    )
                ],
            },
        ),
    ]
