# Generated by Django 5.2.16 on 2026-08-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0005_stock_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="buybackledgerentry",
            name="counterparty_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buybackledgerentry",
            name="counterparty_kind",
            field=models.CharField(
                blank=True,
                default="",
                help_text="character, corporation, or empty when unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="buybackledgerentry",
            name="counterparty_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
