# Generated by Django 5.2.16 on 2026-08-10 02:11

from django.db import migrations, models

NEW_LEADING_TEXT = (
    "Alliance buyback by Minmatar Extraction Company. "
    "Paste your items for an instant offer, then contract your goods in Amo."
)

# Prior defaults / close variants still stored on settings rows.
OLD_LEADING_TEXTS = (
    (
        "Alliance buyback via Minmatar Extraction Company. "
        "We pay full Jita buy for materials our industry supply chain is "
        "importing for recent orders, and 90% for other accepted ore and PI. "
        "Paste your items for an instant offer, then contract at Amo — "
        "paid within ~24 hours."
    ),
    (
        "Alliance buyback via Minmatar Extraction Company. "
        "Paste your items for an instant offer, then contract compressed "
        "highsec ore and PI at Amo — paid within ~24 hours."
    ),
    (
        "Alliance buyback via Minmatar Extraction Company. "
        "Contract compressed ore, PI, and salvage at Amo — priced with "
        "Janice and paid within ~24 hours."
    ),
)


def update_leading_text(apps, schema_editor):
    EveBuybackSettings = apps.get_model("buyback", "EveBuybackSettings")
    EveBuybackSettings.objects.filter(
        leading_text__in=OLD_LEADING_TEXTS
    ).update(leading_text=NEW_LEADING_TEXT)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0006_ledger_counterparty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="leading_text",
            field=models.TextField(
                blank=True,
                default=NEW_LEADING_TEXT,
            ),
        ),
        migrations.RunPython(update_leading_text, noop_reverse),
    ]
