# Generated by Django 5.2.16 on 2026-08-26 23:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0008_settings_rate_fields"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evebuybacksettings",
            name="sell_markup",
            field=models.FloatField(
                default=0.0,
                help_text="Extra share on the sell basis (0 = none, 0.05 = 5%).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="evebuybacksettings",
            name="sell_price_basis",
            field=models.CharField(
                choices=[
                    ("jita_split", "Jita split"),
                    ("jita_buy", "Jita buy"),
                    ("jita_sell", "Jita sell"),
                ],
                default="jita_split",
                help_text="Jita number used to price hangar sales to buyers.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="demand_jita_buy",
            field=models.FloatField(
                default=1.0,
                help_text="Share of Jita buy paid for in-demand items (1.0 = 100%).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="ore_refine",
            field=models.FloatField(
                default=0.85,
                help_text="Assumed refine yield for compressed ore pricing.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evebuybacksettings",
            name="surplus_jita_buy",
            field=models.FloatField(
                default=0.9,
                help_text="Share of Jita buy paid for surplus accepted items.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="BuybackPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("planner", "Planner"),
                            ("stockpile", "Stockpile"),
                        ],
                        default="stockpile",
                        max_length=16,
                    ),
                ),
                (
                    "character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("paste", models.TextField()),
                ("contract_total", models.BigIntegerField()),
                ("sell_price_basis", models.CharField(max_length=16)),
                ("sell_markup", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyback_purchase_orders_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyback_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyback purchase order",
                "verbose_name_plural": "Buyback purchase orders",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BuybackPurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "fill_source",
                    models.CharField(
                        choices=[("exact", "Exact"), ("refine", "Refine")],
                        default="exact",
                        max_length=16,
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyback_purchase_order_lines",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="buyback.buybackpurchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyback purchase order line",
                "verbose_name_plural": "Buyback purchase order lines",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="buybackpurchaseorder",
            index=models.Index(
                fields=["status", "-created_at"],
                name="buyback_po_status_created",
            ),
        ),
    ]
