# Generated by Django 5.2.16 on 2026-09-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0010_purchase_order_discord_thread"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evebuybacksettings",
            name="coordinators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can see pending hangar sales and mark them complete on the site and in Discord.",
                related_name="buyback_coordinator_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
