# Generated by Django 5.1.2 on 2024-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingfleet", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="standingfleetvoicerecord",
            index=models.Index(fields=["created_on"], name="created_on_idx"),
        ),
        migrations.AddIndex(
            model_name="standingfleetvoicerecord",
            index=models.Index(fields=["username"], name="username_idx"),
        ),
    ]
