# Generated by Django 5.1.1 on 2024-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evepost",
            name="seo_description",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
