# Generated by Django 5.1.1 on 2024-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_evepost_seo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="evepost",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("trash", "Trash"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evepost",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
