# Generated by Django 5.1.2 on 2024-10-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_evepost_state_alter_evepost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="evepost",
            name="tags",
            field=models.ManyToManyField(blank=True, to="posts.evetag"),
        ),
        migrations.DeleteModel(
            name="EvePostTag",
        ),
    ]
