# Generated by Django 5.1.2 on 2024-10-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_evepost_tags_delete_eveposttag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evepost",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
