# Generated by Django 5.2.16 on 2026-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_evepost_title"),
        ("tribes", "0030_tribegroup_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="evepost",
            name="tribe_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional tribe groups this post is associated with.",
                related_name="posts",
                to="tribes.tribegroup",
            ),
        ),
    ]
