# Generated by Django 5.0.4 on 2024-04-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0031_alter_evecharacter_alliance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveStructure",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("system_id", models.BigIntegerField()),
                ("system_name", models.CharField(max_length=255)),
                ("type_id", models.BigIntegerField()),
                ("type_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("reinforce_hour", models.IntegerField()),
                ("fuel_expires", models.DateTimeField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("anchoring", "Anchoring"),
                            ("armor_reinforce", "Armor Reinforce"),
                            ("armor_vulnerable", "Armor Vulnerable"),
                            ("deploy_vulnerable", "Deploy Vulnerable"),
                            ("fitting_invulnerable", "Fitting Invulnerable"),
                            ("hull_reinforce", "Hull Reinforce"),
                            ("hull_vulnerable", "Hull Vulnerable"),
                            ("online_deprecated", "Online Deprecated"),
                            ("onlining_vulnerable", "Onlining Vulnerable"),
                            ("shield_vulnerable", "Shield Vulnerable"),
                            ("unanchored", "Unanchored"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=255,
                    ),
                ),
                ("state_timer_start", models.DateTimeField(null=True)),
                ("state_timer_end", models.DateTimeField(null=True)),
                ("fitting", models.TextField(blank=True, null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecorporation",
                    ),
                ),
            ],
        ),
    ]
