# Generated by Django 5.0.4 on 2024-04-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructure",
            name="is_valid_staging",
            field=models.BooleanField(default=False),
        ),
    ]
