# Generated by Django 5.0.4 on 2024-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0002_evestructure_is_valid_staging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evestructure",
            name="fuel_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evestructure",
            name="state_timer_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evestructure",
            name="state_timer_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
