# Generated by Django 5.0.6 on 2024-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0004_evestructuretimer"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructuretimer",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
