# Generated by Django 5.0.6 on 2024-06-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0005_evestructuretimer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evestructuretimer",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
