# Generated by Django 5.0.6 on 2024-07-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0006_alter_evestructuretimer_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evestructuretimer",
            name="type",
            field=models.CharField(
                choices=[
                    ("astrahus", "Astrahus"),
                    ("fortizar", "Fortizar"),
                    ("keepstar", "Keepstar"),
                    ("raitaru", "Raitaru"),
                    ("azbel", "Azbel"),
                    ("sotiyo", "Sotiyo"),
                    ("athanor", "Athanor"),
                    ("tatara", "Tatara"),
                    ("tenebrex_cyno_jammer", "Tenebrex Cyno Jammer"),
                    ("pharolux_cyno_beacon", "Pharolux Cyno Beacon"),
                    ("ansiblex_jump_gate", "Ansiblex Jump Gate"),
                    ("orbital_skyhook", "Orbital Skyhook"),
                    ("metanox_moon_drill", "Metanox Moon Drill"),
                ],
                max_length=255,
            ),
        ),
    ]
