# Generated by Django 5.1.2 on 2025-05-25 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0060_evelocation"),
        ("structures", "0010_alter_evestructuretimer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveStructureManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poll_time", models.IntegerField(db_index=True, default=0)),
                ("last_update", models.DateTimeField(null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecorporation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["poll_time", "corporation", "character"],
                        name="structures__poll_ti_bbe5ab_idx",
                    )
                ],
            },
        ),
    ]
