# Generated by Django 5.1.2 on 2025-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0012_evestructuremanager_last_polled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveStructurePing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.IntegerField()),
                ("notification_type", models.CharField(max_length=40)),
                ("summary", models.CharField(max_length=255)),
                ("discord_success", models.BooleanField(default=False)),
            ],
        ),
    ]
