# Generated by Django 5.1.2 on 2025-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0013_evestructureping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evestructureping",
            name="notification_id",
            field=models.BigIntegerField(),
        ),
    ]
