# Generated by Django 5.1.2 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0014_alter_evestructureping_notification_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructureping",
            name="created_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="evestructureping",
            name="structure_id",
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="evestructureping",
            name="notification_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
