# Generated by Django 5.1.9 on 2025-05-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0060_evelocation"),
        ("structures", "0015_evestructureping_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructureping",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="evestructureping",
            name="text",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
