# Generated by Django 5.1.9 on 2025-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "structures",
            "0016_evestructureping_reported_by_evestructureping_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructureping",
            name="event_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="evestructureping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
