# Generated by Django 5.1.15 on 2026-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0018_delete_evestructuremanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructure",
            name="deleted",
            field=models.DateTimeField(
                db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="evestructure",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
