# Generated by Django 5.2.16 on 2026-09-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_campaign_kinds_and_structures"),
        ("structures", "0019_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="evestructuretimer",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="structure_timers",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="evestructuretimer",
            name="fitting",
            field=models.TextField(blank=True, null=True),
        ),
    ]
