# Generated by Django 5.0.4 on 2024-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("discord", "0005_alter_discordrole_role_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discordrole",
            index=models.Index(
                fields=["role_id"], name="discord_dis_role_id_115cbc_idx"
            ),
        ),
    ]
