# Generated by Django 5.0.4 on 2024-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0006_discordrole_discord_dis_role_id_115cbc_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
