# Generated by Django 5.0.4 on 2024-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0007_discorduser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="is_down_under",
            field=models.BooleanField(default=False),
        ),
    ]
