# Generated by Django 5.0.4 on 2024-04-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0008_discorduser_is_down_under"),
        ("discord", "0009_discorduser_dress_wearer"),
    ]

    operations = []
