# Generated by Django 5.1.9 on 2025-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0010_merge_20240418_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="discordrole",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
