# Generated by Django 5.1.15 on 2026-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0017_discordchannel_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordchannelactivityrecord",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("text_message", "Text message"),
                    ("voice_minute", "Voice minute"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="discordchannelactivityrecord",
            name="quantity",
            field=models.IntegerField(
                help_text="Minutes for voice activity, message count for text activity."
            ),
        ),
        migrations.AlterModelTable(
            name="discordchannelactivityrecord",
            table=None,
        ),
    ]
