# Generated by Django 5.1.15 on 2026-07-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discord",
            "0018_alter_discordchannelactivityrecord_activity_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="discordchannel",
            name="receive_capital_pings",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, capital kills within 8 LY of Amamake are posted here.",
            ),
        ),
    ]
