/**
 * Warzone Report boards for yc128-07 — generated by scripts/warzone_extract.mjs on 2026-09-04.
 * Source: zKillboard per-system kills for all 70 Amarr-Minmatar FW systems in 2026-07
 * (capsules and NPC-only kills excluded); deltas vs 2026-06; holders and scoreboard from ESI.
 * Do not edit by hand; re-run the script.
 */

import type { WarzoneGroup, WarzonePilot, WarzoneShip, WarzoneTrafficRow } from './types'

export const BOARDS_GENERATED_ON = '2026-09-04'
export const BOARDS_SAMPLED_KILLS = 39_129
export const BOARDS_TOTAL_ISK = 3_262_800_814_540

export const SCOREBOARD_STATS = {
    minmatar: { systems: 27, pilots: 34527, active_pilots: 1490, kills: 11471, kills_last_week: 4203, victory_points_last_week: 1118133 },
    amarr: { systems: 43, pilots: 32940, active_pilots: 1511, kills: 12254, kills_last_week: 2212, victory_points_last_week: 1096376 },
} as const

export const MINMATAR_SOLO: readonly WarzonePilot[] = [
    { characterId: 1_564_908_281, name: "cursedlion", killmails: 197, affiliation: "The Tuskers Co.", affiliation_id: 99_004_357, affiliation_kind: "alliance" },
    { characterId: 90_204_495, name: "PlutoniuM86", killmails: 163, affiliation: "Smile 'n' Wave", affiliation_id: 99_002_584, affiliation_kind: "alliance" },
    { characterId: 2_049_784_221, name: "Onionz", killmails: 145, affiliation: "Spaghetti N' Meatballs", affiliation_id: 99_014_920, affiliation_kind: "alliance" },
    { characterId: 2_114_993_571, name: "Thraxis Grey", killmails: 85, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 490_956_277, name: "Major Theef", killmails: 72, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
]

export const MINMATAR_SMALL_GANG: readonly WarzonePilot[] = [
    { characterId: 1_761_145_024, name: "Dato Koppla", killmails: 288, affiliation: "Spaghetti N' Meatballs", affiliation_id: 99_014_920, affiliation_kind: "alliance" },
    { characterId: 2_114_993_571, name: "Thraxis Grey", killmails: 275, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 2_121_887_372, name: "Donald Barr", killmails: 275, affiliation: "Triumvirate.", affiliation_id: 933_731_581, affiliation_kind: "alliance" },
    { characterId: 1_564_908_281, name: "cursedlion", killmails: 273, affiliation: "The Tuskers Co.", affiliation_id: 99_004_357, affiliation_kind: "alliance" },
    { characterId: 2_112_149_192, name: "Kong iBUN", killmails: 268, affiliation: "Spaghetti N' Meatballs", affiliation_id: 99_014_920, affiliation_kind: "alliance" },
]

export const MINMATAR_FLEET: readonly WarzonePilot[] = [
    { characterId: 490_956_277, name: "Major Theef", killmails: 170, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 762_475_669, name: "SADIST666", killmails: 150, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 345_180_234, name: "XVSSBR", killmails: 143, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 94_503_719, name: "Selita Caltar", killmails: 135, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
    { characterId: 95_277_360, name: "Enderas Tsero", killmails: 134, affiliation: "Minmatar Fleet Alliance", affiliation_id: 99_011_978, affiliation_kind: "alliance" },
]

export const AMARR_SOLO: readonly WarzonePilot[] = [
    { characterId: 2_124_083_756, name: "Tom Shelby 1st", killmails: 167, affiliation: "Slide On Contact", affiliation_id: 99_015_016, affiliation_kind: "alliance" },
    { characterId: 2_124_374_276, name: "Movmax", killmails: 137, affiliation: "The Ravens' Nest", affiliation_id: 99_014_668, affiliation_kind: "alliance" },
    { characterId: 95_865_832, name: "John Clemson", killmails: 133, affiliation: "GOBLIN FLEET", affiliation_id: 99_015_133, affiliation_kind: "alliance" },
    { characterId: 2_123_550_502, name: "Decimus krull", killmails: 103, affiliation: "The Ravens' Nest", affiliation_id: 99_014_668, affiliation_kind: "alliance" },
    { characterId: 92_630_339, name: "Gregory McMorrow", killmails: 91, affiliation: "Empyrean Edict", affiliation_id: 99_010_995, affiliation_kind: "alliance" },
]

export const AMARR_SMALL_GANG: readonly WarzonePilot[] = [
    { characterId: 788_408_631, name: "Freany", killmails: 399, affiliation: "Slide On Contact", affiliation_id: 99_015_016, affiliation_kind: "alliance" },
    { characterId: 92_630_339, name: "Gregory McMorrow", killmails: 308, affiliation: "Empyrean Edict", affiliation_id: 99_010_995, affiliation_kind: "alliance" },
    { characterId: 1_105_980_003, name: "WvW", killmails: 297, affiliation: "Slide On Contact", affiliation_id: 99_015_016, affiliation_kind: "alliance" },
    { characterId: 2_115_058_050, name: "Cyrelle Aurilen", killmails: 251, affiliation: "Khimi Harar", affiliation_id: 99_008_816, affiliation_kind: "alliance" },
    { characterId: 96_902_356, name: "Gaebrielle Theodoulos", killmails: 246, affiliation: "Virtus Crusade Highsec Chapter", affiliation_id: 98_646_281, affiliation_kind: "corporation" },
]

export const AMARR_FLEET: readonly WarzonePilot[] = [
    { characterId: 2_112_984_047, name: "Vanbo Murgalesh", killmails: 89, affiliation: "Curatores Veritatis Alliance", affiliation_id: 1_988_009_451, affiliation_kind: "alliance" },
    { characterId: 111_505_003, name: "Sapporo Ichiban", killmails: 73, affiliation: "Local Is Primary", affiliation_id: 99_005_678, affiliation_kind: "alliance" },
    { characterId: 2_112_028_966, name: "Marius Dethahal", killmails: 72, affiliation: "Khimi Harar", affiliation_id: 99_008_816, affiliation_kind: "alliance" },
    { characterId: 667_436_973, name: "Ehrandir", killmails: 71, affiliation: "Slide On Contact", affiliation_id: 99_015_016, affiliation_kind: "alliance" },
    { characterId: 2_121_910_483, name: "Woof1977", killmails: 64, affiliation: "Curatores Veritatis Alliance", affiliation_id: 1_988_009_451, affiliation_kind: "alliance" },
]

export const SHIPS_SOLO: readonly WarzoneShip[] = [
    { typeId: 73_794, name: "Thrasher Fleet Issue", count: 1105 },
    { typeId: 587, name: "Rifter", count: 943 },
    { typeId: 73_796, name: "Catalyst Navy Issue", count: 738 },
    { typeId: 35_683, name: "Hecate", count: 618 },
    { typeId: 17_841, name: "Federation Navy Comet", count: 596 },
]

export const SHIPS_SMALL_GANG: readonly WarzoneShip[] = [
    { typeId: 73_794, name: "Thrasher Fleet Issue", count: 2161 },
    { typeId: 29_344, name: "Exequror Navy Issue", count: 2073 },
    { typeId: 17_709, name: "Omen Navy Issue", count: 1348 },
    { typeId: 17_713, name: "Stabber Fleet Issue", count: 1139 },
    { typeId: 35_683, name: "Hecate", count: 1010 },
]

export const SHIPS_FLEET: readonly WarzoneShip[] = [
    { typeId: 644, name: "Typhoon", count: 406 },
    { typeId: 11_186, name: "Malediction", count: 369 },
    { typeId: 11_961, name: "Huginn", count: 360 },
    { typeId: 640, name: "Scorpion", count: 356 },
    { typeId: 3_766, name: "Vigil", count: 316 },
]

export const GROUPS: readonly WarzoneGroup[] = [
    { id: 99_011_978, kind: 'alliance', name: "Minmatar Fleet Alliance", killmails: 4_377, isk_destroyed: 560_829_283_785, ships_lost: 2_784, militia: 'minmatar', faction: "Minmatar Republic", faction_id: 500002, fw_share: 0.87 },
    { id: 99_015_016, kind: 'alliance', name: "Slide On Contact", killmails: 3_030, isk_destroyed: 336_136_499_230, ships_lost: 1_397, militia: 'amarr', faction: "Amarr Empire", faction_id: 500003, fw_share: 0.98 },
    { id: 99_009_845, kind: 'alliance', name: "Sedition.", killmails: 3_022, isk_destroyed: 478_214_178_809, ships_lost: 1_177, militia: null, faction: "Angel Cartel", faction_id: 500011, fw_share: 0.60 },
    { id: 99_014_920, kind: 'alliance', name: "Spaghetti N' Meatballs", killmails: 2_228, isk_destroyed: 331_314_280_619, ships_lost: 316, militia: 'minmatar', faction: "Minmatar Republic", faction_id: 500002, fw_share: 0.89 },
    { id: 99_010_995, kind: 'alliance', name: "Empyrean Edict", killmails: 1_974, isk_destroyed: 259_933_377_657, ships_lost: 727, militia: 'amarr', faction: "Amarr Empire", faction_id: 500003, fw_share: 0.98 },
    { id: 99_014_668, kind: 'alliance', name: "The Ravens' Nest", killmails: 1_658, isk_destroyed: 157_453_338_240, ships_lost: 1_005, militia: 'amarr', faction: "Amarr Empire", faction_id: 500003, fw_share: 0.96 },
    { id: 99_005_678, kind: 'alliance', name: "Local Is Primary", killmails: 1_578, isk_destroyed: 311_296_510_594, ships_lost: 430, militia: 'amarr', faction: "Amarr Empire", faction_id: 500003, fw_share: 0.97 },
    { id: 99_008_816, kind: 'alliance', name: "Khimi Harar", killmails: 1_148, isk_destroyed: 189_257_125_226, ships_lost: 262, militia: 'amarr', faction: "Amarr Empire", faction_id: 500003, fw_share: 0.81 },
    { id: 99_002_584, kind: 'alliance', name: "Smile 'n' Wave", killmails: 1_075, isk_destroyed: 110_894_319_944, ships_lost: 394, militia: null, faction: "Angel Cartel", faction_id: 500011, fw_share: 0.89 },
    { id: 99_013_187, kind: 'alliance', name: "The Obsidian Front - Reborn", killmails: 1_057, isk_destroyed: 200_772_988_635, ships_lost: 217, militia: 'minmatar', faction: "Minmatar Republic", faction_id: 500002, fw_share: 0.70 },
]

export const TRAFFIC: readonly WarzoneTrafficRow[] = [
    { system: "Amamake", system_id: 30_002_537, front: "Heimatar", ships: 8_009, vs_last_month: 863, isk: 847_412_266_611, isk_label: "847B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002537/" },
    { system: "Auga", system_id: 30_002_542, front: "Heimatar", ships: 5_496, vs_last_month: 1588, isk: 404_060_078_617, isk_label: "404B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002542/" },
    { system: "Siseide", system_id: 30_002_539, front: "Heimatar", ships: 3_128, vs_last_month: -706, isk: 172_882_237_581, isk_label: "173B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002539/" },
    { system: "Dal", system_id: 30_002_541, front: "Heimatar", ships: 2_370, vs_last_month: -925, isk: 174_239_560_454, isk_label: "174B", holds_today: "amarr", href: "https://zkillboard.com/system/30002541/" },
    { system: "Vard", system_id: 30_002_538, front: "Heimatar", ships: 1_848, vs_last_month: -1157, isk: 94_605_646_705, isk_label: "94.6B", holds_today: "amarr", href: "https://zkillboard.com/system/30002538/" },
    { system: "Turnur", system_id: 30_002_086, front: "Metropolis", ships: 1_726, vs_last_month: 1001, isk: 333_613_135_673, isk_label: "334B", holds_today: "amarr", href: "https://zkillboard.com/system/30002086/" },
    { system: "Kourmonen", system_id: 30_003_068, front: "Bleak Lands", ships: 1_702, vs_last_month: -1178, isk: 145_131_264_775, isk_label: "145B", holds_today: "minmatar", href: "https://zkillboard.com/system/30003068/" },
    { system: "Aset", system_id: 30_002_084, front: "Metropolis", ships: 1_604, vs_last_month: 877, isk: 94_911_716_752, isk_label: "94.9B", holds_today: "amarr", href: "https://zkillboard.com/system/30002084/" },
    { system: "Hadozeko", system_id: 30_002_057, front: "Metropolis", ships: 1_092, vs_last_month: 435, isk: 45_152_169_185, isk_label: "45.2B", holds_today: "amarr", href: "https://zkillboard.com/system/30002057/" },
    { system: "Isbrabata", system_id: 30_002_087, front: "Metropolis", ships: 982, vs_last_month: 142, isk: 57_019_467_658, isk_label: "57.0B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002087/" },
    { system: "Eszur", system_id: 30_002_095, front: "Metropolis", ships: 962, vs_last_month: 39, isk: 51_596_555_720, isk_label: "51.6B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002095/" },
    { system: "Lantorn", system_id: 30_002_540, front: "Heimatar", ships: 909, vs_last_month: 161, isk: 36_748_331_486, isk_label: "36.7B", holds_today: "minmatar", href: "https://zkillboard.com/system/30002540/" },
]

export const FRONTS = {
    minmatar: { ships: 33_623, ships_label: "~34k", hottest_system: "Amamake" },
    amarr: { ships: 5_506, ships_label: "~6k", hottest_system: "Kourmonen" },
} as const

export const SYSTEM_STATS = [
    { system_id: 30_002_537, system: "Amamake", front: "Heimatar", ships: 8_009, vs_last_month: 863, isk: 847_412_266_611, isk_label: "847B", holds_today: "minmatar" },
    { system_id: 30_002_542, system: "Auga", front: "Heimatar", ships: 5_496, vs_last_month: 1588, isk: 404_060_078_617, isk_label: "404B", holds_today: "minmatar" },
    { system_id: 30_002_539, system: "Siseide", front: "Heimatar", ships: 3_128, vs_last_month: -706, isk: 172_882_237_581, isk_label: "173B", holds_today: "minmatar" },
    { system_id: 30_002_541, system: "Dal", front: "Heimatar", ships: 2_370, vs_last_month: -925, isk: 174_239_560_454, isk_label: "174B", holds_today: "amarr" },
    { system_id: 30_002_538, system: "Vard", front: "Heimatar", ships: 1_848, vs_last_month: -1157, isk: 94_605_646_705, isk_label: "94.6B", holds_today: "amarr" },
    { system_id: 30_002_086, system: "Turnur", front: "Metropolis", ships: 1_726, vs_last_month: 1001, isk: 333_613_135_673, isk_label: "334B", holds_today: "amarr" },
    { system_id: 30_003_068, system: "Kourmonen", front: "Bleak Lands", ships: 1_702, vs_last_month: -1178, isk: 145_131_264_775, isk_label: "145B", holds_today: "minmatar" },
    { system_id: 30_002_084, system: "Aset", front: "Metropolis", ships: 1_604, vs_last_month: 877, isk: 94_911_716_752, isk_label: "94.9B", holds_today: "amarr" },
    { system_id: 30_002_057, system: "Hadozeko", front: "Metropolis", ships: 1_092, vs_last_month: 435, isk: 45_152_169_185, isk_label: "45.2B", holds_today: "amarr" },
    { system_id: 30_002_087, system: "Isbrabata", front: "Metropolis", ships: 982, vs_last_month: 142, isk: 57_019_467_658, isk_label: "57.0B", holds_today: "minmatar" },
    { system_id: 30_002_095, system: "Eszur", front: "Metropolis", ships: 962, vs_last_month: 39, isk: 51_596_555_720, isk_label: "51.6B", holds_today: "minmatar" },
    { system_id: 30_002_540, system: "Lantorn", front: "Heimatar", ships: 909, vs_last_month: 161, isk: 36_748_331_486, isk_label: "36.7B", holds_today: "minmatar" },
    { system_id: 30_002_058, system: "Ardar", front: "Metropolis", ships: 809, vs_last_month: -882, isk: 42_792_484_716, isk_label: "42.8B", holds_today: "amarr" },
    { system_id: 30_002_082, system: "Floseswin", front: "Metropolis", ships: 688, vs_last_month: 34, isk: 35_655_352_236, isk_label: "35.7B", holds_today: "amarr" },
    { system_id: 30_003_067, system: "Huola", front: "Bleak Lands", ships: 594, vs_last_month: -762, isk: 51_123_931_845, isk_label: "51.1B", holds_today: "amarr" },
    { system_id: 30_002_085, system: "Eytjangard", front: "Metropolis", ships: 587, vs_last_month: 264, isk: 32_195_191_189, isk_label: "32.2B", holds_today: "amarr" },
    { system_id: 30_003_089, system: "Kurniainen", front: "Bleak Lands", ships: 482, vs_last_month: 166, isk: 32_037_957_675, isk_label: "32.0B", holds_today: "amarr" },
    { system_id: 30_002_090, system: "Frerstorn", front: "Metropolis", ships: 441, vs_last_month: -927, isk: 17_654_733_811, isk_label: "17.7B", holds_today: "amarr" },
    { system_id: 30_002_056, system: "Resbroko", front: "Metropolis", ships: 439, vs_last_month: 122, isk: 14_406_100_710, isk_label: "14.4B", holds_today: "minmatar" },
    { system_id: 30_002_957, system: "Tzvi", front: "Devoid", ships: 363, vs_last_month: 343, isk: 18_356_319_380, isk_label: "18.4B", holds_today: "amarr" },
    { system_id: 30_002_958, system: "Raa", front: "Devoid", ships: 345, vs_last_month: 310, isk: 26_533_680_477, isk_label: "26.5B", holds_today: "amarr" },
    { system_id: 30_002_959, system: "Sifilar", front: "Devoid", ships: 330, vs_last_month: 288, isk: 39_512_535_117, isk_label: "39.5B", holds_today: "amarr" },
    { system_id: 30_002_088, system: "Vimeini", front: "Metropolis", ships: 325, vs_last_month: 171, isk: 10_939_591_480, isk_label: "10.9B", holds_today: "amarr" },
    { system_id: 30_002_962, system: "Ezzara", front: "Devoid", ships: 303, vs_last_month: -39, isk: 14_493_738_223, isk_label: "14.5B", holds_today: "amarr" },
    { system_id: 30_002_089, system: "Avenod", front: "Metropolis", ships: 282, vs_last_month: 19, isk: 17_698_134_514, isk_label: "17.7B", holds_today: "amarr" },
    { system_id: 30_002_083, system: "Uisper", front: "Metropolis", ships: 269, vs_last_month: 51, isk: 13_561_768_898, isk_label: "13.6B", holds_today: "amarr" },
    { system_id: 30_002_097, system: "Klogori", front: "Metropolis", ships: 251, vs_last_month: 194, isk: 7_683_392_305, isk_label: "7.7B", holds_today: "minmatar" },
    { system_id: 30_002_960, system: "Arzad", front: "Devoid", ships: 249, vs_last_month: 117, isk: 28_122_719_180, isk_label: "28.1B", holds_today: "amarr" },
    { system_id: 30_003_063, system: "Lamaa", front: "Bleak Lands", ships: 243, vs_last_month: 138, isk: 36_140_440_440, isk_label: "36.1B", holds_today: "amarr" },
    { system_id: 30_002_961, system: "Oyeman", front: "Devoid", ships: 192, vs_last_month: 143, isk: 21_603_039_870, isk_label: "21.6B", holds_today: "amarr" },
    { system_id: 30_002_517, system: "Gulmorogod", front: "Heimatar", ships: 186, vs_last_month: -590, isk: 13_863_990_028, isk_label: "13.9B", holds_today: "minmatar" },
    { system_id: 30_003_069, system: "Kamela", front: "Bleak Lands", ships: 165, vs_last_month: -90, isk: 29_551_995_974, isk_label: "29.6B", holds_today: "minmatar" },
    { system_id: 30_002_060, system: "Evati", front: "Metropolis", ships: 157, vs_last_month: 72, isk: 8_716_326_195, isk_label: "8.7B", holds_today: "minmatar" },
    { system_id: 30_002_066, system: "Arnher", front: "Metropolis", ships: 133, vs_last_month: 38, isk: 8_241_529_902, isk_label: "8.2B", holds_today: "minmatar" },
    { system_id: 30_002_059, system: "Auner", front: "Metropolis", ships: 130, vs_last_month: -44, isk: 15_713_687_489, isk_label: "15.7B", holds_today: "minmatar" },
    { system_id: 30_002_099, system: "Egmar", front: "Metropolis", ships: 105, vs_last_month: -25, isk: 11_681_662_168, isk_label: "11.7B", holds_today: "minmatar" },
    { system_id: 30_003_086, system: "Sahtogas", front: "Bleak Lands", ships: 102, vs_last_month: -36, isk: 5_700_860_283, isk_label: "5.7B", holds_today: "amarr" },
    { system_id: 30_002_094, system: "Ebolfer", front: "Metropolis", ships: 100, vs_last_month: -244, isk: 4_066_632_933, isk_label: "4.1B", holds_today: "amarr" },
    { system_id: 30_002_514, system: "Bosboger", front: "Heimatar", ships: 88, vs_last_month: -26, isk: 4_205_260_644, isk_label: "4.2B", holds_today: "minmatar" },
    { system_id: 30_003_088, system: "Oyonata", front: "Bleak Lands", ships: 85, vs_last_month: -12, isk: 4_879_863_248, isk_label: "4.9B", holds_today: "amarr" },
    { system_id: 30_003_070, system: "Sosala", front: "Bleak Lands", ships: 84, vs_last_month: 53, isk: 95_192_166_184, isk_label: "95.2B", holds_today: "amarr" },
    { system_id: 30_002_096, system: "Hofjaldgund", front: "Metropolis", ships: 70, vs_last_month: -213, isk: 2_594_605_545, isk_label: "2.6B", holds_today: "amarr" },
    { system_id: 30_002_093, system: "Gebuladi", front: "Metropolis", ships: 58, vs_last_month: -244, isk: 2_509_019_190, isk_label: "2.5B", holds_today: "amarr" },
    { system_id: 30_002_062, system: "Todifrauan", front: "Metropolis", ships: 56, vs_last_month: 1, isk: 13_542_249_615, isk_label: "13.5B", holds_today: "minmatar" },
    { system_id: 30_002_091, system: "Ontorn", front: "Metropolis", ships: 56, vs_last_month: -336, isk: 3_358_904_792, isk_label: "3.4B", holds_today: "amarr" },
    { system_id: 30_002_100, system: "Taff", front: "Metropolis", ships: 48, vs_last_month: 37, isk: 11_587_994_930, isk_label: "11.6B", holds_today: "minmatar" },
    { system_id: 30_002_516, system: "Lulm", front: "Heimatar", ships: 43, vs_last_month: 23, isk: 4_088_469_158, isk_label: "4.1B", holds_today: "minmatar" },
    { system_id: 30_002_098, system: "Orfrold", front: "Metropolis", ships: 42, vs_last_month: -22, isk: 2_098_110_446, isk_label: "2.1B", holds_today: "minmatar" },
    { system_id: 30_003_091, system: "Tannakan", front: "Bleak Lands", ships: 39, vs_last_month: -9, isk: 5_082_974_550, isk_label: "5.1B", holds_today: "amarr" },
    { system_id: 30_002_979, system: "Tararan", front: "Devoid", ships: 38, vs_last_month: -2, isk: 5_622_170_700, isk_label: "5.6B", holds_today: "amarr" },
    { system_id: 30_002_978, system: "Asghed", front: "Devoid", ships: 36, vs_last_month: -28, isk: 57_475_343_858, isk_label: "57.5B", holds_today: "amarr" },
    { system_id: 30_002_102, system: "Gukarla", front: "Metropolis", ships: 35, vs_last_month: 17, isk: 3_000_080_411, isk_label: "3.0B", holds_today: "minmatar" },
    { system_id: 30_003_071, system: "Anka", front: "Bleak Lands", ships: 31, vs_last_month: -170, isk: 1_932_966_784, isk_label: "1.9B", holds_today: "amarr" },
    { system_id: 30_003_090, system: "Saidusairos", front: "Bleak Lands", ships: 29, vs_last_month: 25, isk: 3_467_664_872, isk_label: "3.5B", holds_today: "amarr" },
    { system_id: 30_003_087, system: "Haras", front: "Bleak Lands", ships: 24, vs_last_month: -28, isk: 1_941_945_801, isk_label: "1.9B", holds_today: "amarr" },
    { system_id: 30_002_101, system: "Ualkin", front: "Metropolis", ships: 23, vs_last_month: 19, isk: 1_283_207_314, isk_label: "1.3B", holds_today: "minmatar" },
    { system_id: 30_002_065, system: "Lasleinur", front: "Metropolis", ships: 18, vs_last_month: 0, isk: 523_561_602, isk_label: "524M", holds_today: "minmatar" },
    { system_id: 30_002_063, system: "Helgatild", front: "Metropolis", ships: 17, vs_last_month: 9, isk: 1_800_809_577, isk_label: "1.8B", holds_today: "minmatar" },
    { system_id: 30_002_980, system: "Sosan", front: "Devoid", ships: 16, vs_last_month: -42, isk: 1_742_133_421, isk_label: "1.7B", holds_today: "amarr" },
    { system_id: 30_002_067, system: "Brin", front: "Metropolis", ships: 16, vs_last_month: -1, isk: 1_332_248_407, isk_label: "1.3B", holds_today: "minmatar" },
    { system_id: 30_002_975, system: "Roushzar", front: "Devoid", ships: 13, vs_last_month: -89, isk: 3_844_247_662, isk_label: "3.8B", holds_today: "amarr" },
    { system_id: 30_002_064, system: "Arnstur", front: "Metropolis", ships: 11, vs_last_month: 8, isk: 1_296_245_131, isk_label: "1.3B", holds_today: "minmatar" },
    { system_id: 30_002_061, system: "Ofstold", front: "Metropolis", ships: 11, vs_last_month: 1, isk: 769_652_925, isk_label: "770M", holds_today: "minmatar" },
    { system_id: 30_003_072, system: "Iesa", front: "Bleak Lands", ships: 10, vs_last_month: -4, isk: 2_393_510_467, isk_label: "2.4B", holds_today: "amarr" },
    { system_id: 30_003_077, system: "Uusanen", front: "Bleak Lands", ships: 9, vs_last_month: -14, isk: 1_451_809_068, isk_label: "1.5B", holds_today: "amarr" },
    { system_id: 30_002_976, system: "Labapi", front: "Devoid", ships: 7, vs_last_month: -58, isk: 801_150_042, isk_label: "801M", holds_today: "amarr" },
    { system_id: 30_002_977, system: "Arayar", front: "Devoid", ships: 6, vs_last_month: -25, isk: 654_964_858, isk_label: "655M", holds_today: "amarr" },
    { system_id: 30_002_981, system: "Halmah", front: "Devoid", ships: 6, vs_last_month: -1, isk: 1_160_183_569, isk_label: "1.2B", holds_today: "amarr" },
    { system_id: 30_003_079, system: "Saikamon", front: "Bleak Lands", ships: 3, vs_last_month: -10, isk: 5_666_680_614, isk_label: "5.7B", holds_today: "amarr" },
    { system_id: 30_002_092, system: "Sirekur", front: "Metropolis", ships: 3, vs_last_month: -211, isk: 80_390_902, isk_label: "80M", holds_today: "amarr" },
] as const
