# Generated by Django 4.2.8 on 2023-12-11 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveonline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveprimarytoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eve_primary_token",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
