# Generated by Django 4.2.8 on 2023-12-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0003_evecorporation"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecorporation",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alliance", "Alliance"),
                    ("militia", "Militia"),
                    ("associate", "Associate"),
                ],
                max_length=10,
            ),
        ),
    ]
