# Generated by Django 4.2.8 on 2023-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0004_evecorporation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecorporation',
            name='type',
            field=models.CharField(blank=True, choices=[('alliance', 'Alliance'), ('militia', 'Militia'), ('associate', 'Associate'), ('public', 'Public')], max_length=10),
        ),
    ]
