# Generated by Django 4.2.8 on 2023-12-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0008_evecharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evecharacter',
            name='alliance_id',
        ),
        migrations.RemoveField(
            model_name='evecharacter',
            name='alliance_name',
        ),
        migrations.RemoveField(
            model_name='evecharacter',
            name='corporation_id',
        ),
        migrations.RemoveField(
            model_name='evecharacter',
            name='corporation_name',
        ),
        migrations.RemoveField(
            model_name='evecharacter',
            name='faction_id',
        ),
        migrations.RemoveField(
            model_name='evecharacter',
            name='faction_name',
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporation'),
        ),
    ]
