# Generated by Django 4.2.8 on 2023-12-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0013_evecharacterskillset"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacterskillset",
            name="total_skill_points",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
