# Generated by Django 4.2.8 on 2023-12-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("eveonline", "0014_evecharacterskillset_total_skill_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveAlliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alliance_id", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=255)),
                ("ticker", models.CharField(blank=True, max_length=255)),
                ("member_count", models.IntegerField(blank=True)),
                ("executor_corporation_id", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EveGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0, unique=True)),
                (
                    "alliances",
                    models.ManyToManyField(
                        blank=True, to="eveonline.evealliance"
                    ),
                ),
                (
                    "corporations",
                    models.ManyToManyField(
                        blank=True, to="eveonline.evecorporation"
                    ),
                ),
                (
                    "factions",
                    models.ManyToManyField(
                        blank=True, to="eveuniverse.evefaction"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
