# Generated by Django 4.2.8 on 2023-12-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0015_evealliance_evegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="evegroup",
            name="unique",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="evegroup",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="evegroup",
            unique_together={("priority", "unique")},
        ),
    ]
