# Generated by Django 4.2.11 on 2024-03-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumbleaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
