# Generated by Django 5.1.2 on 2025-05-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mumble", "0002_alter_mumbleaccess_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mumbleaccess",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mumbleaccess",
            name="username",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
