# Generated by Django 5.1 on 2024-09-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=100)),
                ("planet", models.IntegerField()),
                ("moon", models.IntegerField()),
                (
                    "owned_by_ticker",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("system", "planet", "moon")},
            },
        ),
        migrations.CreateModel(
            name="EveMoonDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ore",
                    models.CharField(
                        choices=[
                            ("Bitumens", "Bitumens"),
                            ("Coesite", "Coesite"),
                            ("Sylvite", "Sylvite"),
                            ("Zeolites", "Zeolites"),
                            ("Cobaltite", "Cobaltite"),
                            ("Euxenite", "Euxenite"),
                            ("Scheelite", "Scheelite"),
                            ("Titanite", "Titanite"),
                            ("Chromite", "Chromite"),
                            ("Otavite", "Otavite"),
                            ("Sperrylite", "Sperrylite"),
                            ("Vanadinite", "Vanadinite"),
                            ("Carnotite", "Carnotite"),
                            ("Cinnabar", "Cinnabar"),
                            ("Pollucite", "Pollucite"),
                            ("Zircon", "Zircon"),
                            ("Loparite", "Loparite"),
                            ("Monazite", "Monazite"),
                            ("Xenotime", "Xenotime"),
                            ("Ytterbite", "Ytterbite"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "yield_percent",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                (
                    "moon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moons.evemoon",
                    ),
                ),
            ],
        ),
    ]
