# Generated by Django 5.1 on 2024-09-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evemoon",
            name="owned_by_ticker",
        ),
    ]
