# Generated by Django 5.1.2 on 2026-02-28 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eveonline", "0090_evelocation_is_structure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown-formatted long-form description.",
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("banner_url", models.URLField(blank=True, null=True)),
                (
                    "discord_channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tribe-level Discord channel for announcements.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chief",
                    models.ForeignKey(
                        blank=True,
                        help_text="Single tribe leader; can approve/deny membership across all groups.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_tribes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Tribe-level Discord role (e.g. 'Capitals').",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TribeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "discord_channel_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "ship_type_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="EVE type IDs (hull IDs) used to attribute kills/losses/fleet events to this group.",
                    ),
                ),
                (
                    "blueprint_type_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Blueprint type IDs used to attribute industry jobs to this group.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chief",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group leader; can approve/deny membership for this group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_tribe_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Supporting leaders; can also approve/deny membership for this group.",
                        related_name="elder_tribe_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Group-level Discord role (e.g. 'Dreads').",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe_group",
                        to="auth.group",
                    ),
                ),
                (
                    "tribe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="tribes.tribe",
                    ),
                ),
            ],
            options={
                "ordering": ["tribe__name", "name"],
                "unique_together": {("tribe", "name")},
            },
        ),
        migrations.CreateModel(
            name="TribeGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "requirement_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Per-character compliance dict computed at submission time, stored for reviewer.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when status becomes 'left' or 'removed'.",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tribe_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_tribe_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tribes.tribegroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tribe_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TribeGroupMembershipCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "leave_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("voluntary", "Voluntary"),
                            ("removed", "Removed"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tribe_commitments",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="tribes.tribegroupmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-committed_at"],
            },
        ),
        migrations.CreateModel(
            name="TribeGroupOutreach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="E.g. 'DM'd on Discord'."
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The candidate character that was contacted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tribe_outreach",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        help_text="Chief or elder who sent the outreach.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_tribe_outreach",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_records",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="TribeGroupRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("group", "Auth Group Membership"),
                            ("asset_type", "Asset Ownership"),
                            ("skillset", "Skillset Progress"),
                            ("industry_activity", "Active Industry Job"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "asset_type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="EVE type ID of the required asset.",
                        null=True,
                    ),
                ),
                (
                    "asset_type_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for display.",
                        max_length=255,
                    ),
                ),
                (
                    "minimum_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of this asset the character must own.",
                    ),
                ),
                (
                    "location_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Required asset location (station/structure ID).",
                        null=True,
                    ),
                ),
                (
                    "solar_system_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Required asset solar system (falls back when location_id is unset).",
                        null=True,
                    ),
                ),
                (
                    "minimum_progress",
                    models.FloatField(
                        default=1.0,
                        help_text="Required skillset progress (0.0–1.0). 1.0 = fully trained.",
                    ),
                ),
                (
                    "activity_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ESI activity ID (1=Manufacturing, 3=Researching ME, etc.).",
                        null=True,
                    ),
                ),
                (
                    "minimum_active_jobs",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of active jobs required.",
                    ),
                ),
                (
                    "required_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player must belong to this auth group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "skillset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveonline.eveskillset",
                    ),
                ),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["tribe_group", "requirement_type"],
            },
        ),
        migrations.CreateModel(
            name="TribeActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("fleet_participation", "Fleet Participation"),
                            ("kills", "Kills"),
                            ("losses", "Losses"),
                            ("mining_contribution", "Mining Contribution"),
                            ("freight_contribution", "Freight Contribution"),
                            (
                                "industry_job_completed",
                                "Industry Job Completed",
                            ),
                            ("content_contribution", "Content Contribution"),
                            ("doctrine_update", "Doctrine Update"),
                            ("fitting_update", "Fitting Update"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Raw output number (m³, ISK, ships, etc.)."
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="E.g. 'm3', 'ISK', 'kills', 'fleets'.",
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Source record ID for deduplication (e.g. killmail_id, job_id).",
                        max_length=255,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Source model name (e.g. 'EveCharacterKillmail', 'EveCharacterIndustryJob').",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acting character; null for manually logged activities.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe_activities",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Denormalised from character for query convenience.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tribe_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tribe_group", "activity_type"],
                        name="tribes_trib_tribe_g_b0afa2_idx",
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="tribes_trib_referen_73e6bf_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="tribes_trib_created_f43f9f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("reference_id", ""), _negated=True
                        ),
                        fields=("reference_type", "reference_id"),
                        name="tribes_tribeactivity_unique_reference",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tribegroupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("tribe_group", "user"),
                name="tribes_tribegroupmembership_one_active_per_user_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="tribegroupmembershipcharacter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("membership", "character"),
                name="tribes_tribegroupmembershipchar_one_active_per_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="tribegroupoutreach",
            constraint=models.UniqueConstraint(
                fields=("tribe_group", "character"),
                name="tribes_tribegroupoutreach_unique_per_group_character",
            ),
        ),
    ]
