# Generated by Django 5.1.2 on 2026-03-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="asset_type_id",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="asset_type_name",
        ),
        migrations.AddField(
            model_name="tribegrouprequirement",
            name="asset_type_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of EVE type IDs — owning any one of them satisfies this requirement.",
            ),
        ),
        migrations.AddField(
            model_name="tribegrouprequirement",
            name="asset_type_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Display names corresponding to asset_type_ids (same order).",
            ),
        ),
    ]
