# Generated by Django 5.1.2 on 2026-03-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0002_asset_type_ids_jsonfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="asset_type_ids",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="asset_type_names",
        ),
        migrations.CreateModel(
            name="TribeGroupRequirementAssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.BigIntegerField(help_text="EVE type ID.")),
                (
                    "type_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name (e.g. 'Fenrir'). Used for display only.",
                        max_length=255,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_types",
                        to="tribes.tribegrouprequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
                "ordering": ["type_name", "type_id"],
            },
        ),
    ]
