# Generated by Django 5.1.2 on 2026-03-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0003_asset_type_through_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="minimum_progress",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="skillset",
        ),
        migrations.AlterField(
            model_name="tribegrouprequirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("group", "Auth Group Membership"),
                    ("asset_type", "Asset Ownership"),
                    ("skill", "Qualifying Skill"),
                    ("industry_activity", "Active Industry Job"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TribeGroupRequirementSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_type_id",
                    models.IntegerField(help_text="EVE skill type ID."),
                ),
                (
                    "skill_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name (e.g. 'Caldari Carrier'). Used for display only.",
                        max_length=255,
                    ),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum trained level required (1–5).",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifying_skills",
                        to="tribes.tribegrouprequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualifying Skill",
                "verbose_name_plural": "Qualifying Skills",
                "ordering": ["skill_name", "skill_type_id"],
            },
        ),
    ]
