# Generated by Django 5.1.2 on 2026-03-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("tribes", "0004_qualifying_skill_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tribegrouprequirementassettype",
            options={
                "ordering": ["eve_type__name"],
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
            },
        ),
        migrations.AlterModelOptions(
            name="tribegrouprequirementskill",
            options={
                "ordering": ["eve_type__name"],
                "verbose_name": "Qualifying Skill",
                "verbose_name_plural": "Qualifying Skills",
            },
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="type_id",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="type_name",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirementskill",
            name="skill_name",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirementskill",
            name="skill_type_id",
        ),
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="eve_type",
            field=models.ForeignKey(
                blank=True,
                help_text="EVE ship/item type that qualifies the character.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AddField(
            model_name="tribegrouprequirementskill",
            name="eve_type",
            field=models.ForeignKey(
                blank=True,
                help_text="EVE skill type (must be a skill item).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveuniverse.evetype",
            ),
        ),
    ]
