# Generated by Django 5.1.2 on 2026-03-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0005_eve_type_fk_for_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="solar_system_id",
        ),
    ]
