# Generated by Django 5.1.2 on 2026-03-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0006_remove_solar_system_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="activity_id",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="minimum_active_jobs",
        ),
        migrations.AlterField(
            model_name="tribegrouprequirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("group", "Auth Group Membership"),
                    ("asset_type", "Asset Ownership"),
                    ("skill", "Qualifying Skill"),
                ],
                max_length=32,
            ),
        ),
    ]
