# Generated by Django 5.1.2 on 2026-03-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0007_remove_industry_activity_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="minimum_count",
        ),
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="location_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Required asset location (station/structure ID). Leave blank for any location.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="minimum_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum number of this asset the character must own.",
            ),
        ),
    ]
