# Generated by Django 5.1.2 on 2026-03-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0008_asset_type_location_and_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirement",
            name="required_group",
        ),
        migrations.AlterField(
            model_name="tribegrouprequirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("asset_type", "Asset Ownership"),
                    ("skill", "Qualifying Skill"),
                ],
                max_length=32,
            ),
        ),
    ]
