# Generated by Django 5.1.2 on 2026-03-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0010_remove_requirement_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tribegrouprequirement",
            options={"ordering": ["tribe_group"]},
        ),
        migrations.DeleteModel(
            name="TribeGroupOutreach",
        ),
    ]
