# Generated by Django 5.1.2 on 2026-03-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0012_refactor_membership_status_and_add_history"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TribeActivity",
        ),
    ]
