# Generated by Django 5.1.2 on 2026-03-04 04:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_location_fk(apps, schema_editor):
    """Copy old location_id (EVE ID) to new location FK where EveLocation exists."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE tribes_tribegrouprequirementassettype
            SET location_fk_id = location_id
            WHERE location_id IS NOT NULL
            AND EXISTS (
                SELECT 1 FROM eveonline_evelocation
                WHERE eveonline_evelocation.location_id = tribes_tribegrouprequirementassettype.location_id
            )
            """
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
        ("tribes", "0014_one_membership_per_user_group"),
    ]

    operations = [
        # Add FK with temporary column name to avoid clashing with existing location_id
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Required asset location (staging only). Leave blank for any location.",
                limit_choices_to={"staging_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evelocation",
                db_column="location_fk_id",
            ),
        ),
        migrations.RunPython(backfill_location_fk, noop),
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="location_id",
        ),
        migrations.AlterField(
            model_name="tribegrouprequirementassettype",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Required asset location (staging only). Leave blank for any location.",
                limit_choices_to={"staging_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evelocation",
            ),
        ),
    ]
