# Generated by Django 5.1.2 on 2026-03-04 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
        ("tribes", "0014_one_membership_per_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="location_id",
        ),
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Required asset location (staging only). Leave blank for any location.",
                limit_choices_to={"staging_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evelocation",
            ),
        ),
    ]
