# Generated by Django 5.1.2 on 2026-03-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0015_asset_type_location_fk_to_evelocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegroup",
            name="elders",
        ),
    ]
