# Generated by Django 5.1.2 on 2026-03-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
        ("tribes", "0016_remove_elders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="location",
        ),
        migrations.RemoveField(
            model_name="tribegrouprequirementassettype",
            name="minimum_count",
        ),
        migrations.AddField(
            model_name="tribegrouprequirementassettype",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Required asset locations (staging only). Leave blank for any location.",
                limit_choices_to={"staging_active": True},
                to="eveonline.evelocation",
            ),
        ),
    ]
