# Generated by Django 5.1.2 on 2026-03-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("tribes", "0017_asset_type_m2m_locations_drop_minimum_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribegroup",
            name="blueprint_type_ids",
        ),
        migrations.RemoveField(
            model_name="tribegroup",
            name="ship_type_ids",
        ),
        migrations.AlterField(
            model_name="tribegrouprequirementassettype",
            name="eve_type",
            field=models.ForeignKey(
                blank=True,
                help_text="EVE ship type that qualifies the character.",
                limit_choices_to={"eve_group__eve_category_id": 6},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AlterField(
            model_name="tribegrouprequirementskill",
            name="eve_type",
            field=models.ForeignKey(
                blank=True,
                help_text="EVE skill type.",
                limit_choices_to={"eve_group__eve_category_id": 16},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveuniverse.evetype",
            ),
        ),
    ]
