# Generated by Django 5.1.2 on 2026-03-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0090_evelocation_is_structure"),
        ("tribes", "0018_remove_ship_blueprint_type_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TribeGroupActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("killmail", "Killmail"),
                            ("lossmail", "Lossmail"),
                            ("fleet_participation", "Fleet participation"),
                            ("mining", "Mining"),
                            ("planetary_interaction", "Planetary interaction"),
                            ("industry", "Industry"),
                            ("contract", "Contract"),
                            ("courier_contract", "Courier contract"),
                            ("market_order", "Market order"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "source_eve_type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Filter on what the member was using: ship type for killmail/lossmail/fleet, ore type for mining, blueprint type for industry, item type for market. Null = any.",
                        null=True,
                    ),
                ),
                (
                    "target_eve_type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Filter on what was destroyed/targeted: victim's ship for killmail. Null = any. Not applicable for most activity types.",
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tribe group activities",
                "ordering": ["tribe_group", "activity_type"],
            },
        ),
        migrations.CreateModel(
            name="TribeGroupActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="EVE type ID of what the member was using (ship, ore, blueprint, item). Populated at processing time.",
                        null=True,
                    ),
                ),
                (
                    "target_type_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="EVE type ID of what was destroyed/targeted (victim ship for killmails).",
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        blank=True,
                        help_text="Numeric amount for quantifiable activities: units mined, ISK, runs, m³, etc. Null for killmail/lossmail/fleet (1 per record implicit).",
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "units", "ISK", "runs", "m3". Empty for non-quantifiable types.',
                        max_length=32,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        help_text="Source model name (e.g. EveCharacterKillmail, EveCharacterMiningEntry).",
                        max_length=128,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Source record PK for deduplication; composite string for mining entries.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acting character; may be null for fleet (bare character_id in source).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe_activity_records",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "tribe_group_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="tribes.tribegroupactivity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denormalized from character for fast filtering.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe_activity_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tribe_group_activity", "created_at"],
                        name="tribes_tgarecord_act_created",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="tribes_tgarecord_user_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tribe_group_activity",
                            "reference_type",
                            "reference_id",
                        ),
                        name="tribes_tribegroupactivityrecord_unique_ref",
                    )
                ],
            },
        ),
    ]
