# Generated by Django 5.1.15 on 2026-06-21 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0023_tribegroupactivityrecord_occurred_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTicketPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="tribegroup",
            name="help_ticket_title",
            field=models.CharField(
                blank=True,
                help_text="Dropdown label in #help. Blank = group excluded from help tickets.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tribegroupactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("killmail", "Killmail"),
                    ("lossmail", "Lossmail"),
                    ("fleet_participation", "Fleet participation"),
                    ("fleet_commanded", "Fleet commanded"),
                    ("mining", "Mining"),
                    ("planetary_interaction", "Planetary interaction"),
                    ("industry", "Industry"),
                    ("industry_order", "Industry order"),
                    ("contract", "Contract"),
                    ("courier_contract", "Courier contract"),
                    ("market_order", "Market order"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="tribegroupactivityrecord",
            name="occurred_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the source event happened; metrics use this when set, else created_at.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HelpTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opener_discord_id", models.BigIntegerField()),
                ("thread_id", models.BigIntegerField(unique=True)),
                ("thread_name", models.CharField(max_length=100)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by_discord_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("close_reason", models.TextField(blank=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_tickets_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opener",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_tickets_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_tickets",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["tribe_group", "opened_at"],
                        name="tribes_ht_grp_opened",
                    ),
                    models.Index(
                        fields=["status", "opened_at"],
                        name="tribes_ht_status_opened",
                    ),
                ],
            },
        ),
    ]
