# Generated by Django 5.2.16 on 2026-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0027_tribegrouprank_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tribegroup",
            name="required_token_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Director", "Director"),
                    ("Basic", "Basic"),
                    ("Industry", "Industry"),
                    ("Market", "Market"),
                    ("Executor", "Executor"),
                ],
                default="",
                help_text="If set, characters must have this ESI token type to apply or be added.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="tribegroup",
            name="code",
            field=models.CharField(
                help_text="Stable catalog key for reports and bindings (e.g. supply.mining).",
                max_length=64,
                unique=True,
            ),
        ),
    ]
