# Generated by Django 5.2.16 on 2026-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0029_remove_tribe_group_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="tribegroup",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Markdown-formatted long-form description for the group hub.",
            ),
        ),
    ]
