# Generated by Django 5.2.16 on 2026-08-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0027_drop_legacy_mumble_access_table"),
        ("tribes", "0030_tribegroup_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tribegroup",
            name="allowed_affiliations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Affiliations that may apply to this group. Empty uses the tribes.apply PilotFeature affiliations (currently Alliance and Associate).",
                related_name="tribe_groups",
                to="groups.affiliationtype",
            ),
        ),
    ]
