# Generated by Django 5.2.16 on 2026-08-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0031_tribegroup_allowed_affiliations"),
    ]

    operations = [
        migrations.AddField(
            model_name="tribegroup",
            name="require_off_trial",
            field=models.BooleanField(
                default=False,
                help_text="If set, applicants must be off Alliance trial (community status active) before they can apply.",
            ),
        ),
    ]
