# Generated by Django 5.2.16 on 2026-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0032_tribegroup_require_off_trial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tribegroup",
            name="required_token_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Director", "Director"),
                    ("Basic", "Basic"),
                    ("Industry", "Industry"),
                    ("Market", "Market"),
                    ("Executor", "Executor"),
                    ("FleetCommander", "FleetCommander"),
                ],
                default="",
                help_text="If set, characters must have this ESI token type to apply or be added.",
                max_length=40,
            ),
        ),
    ]
