# Generated by Django 5.2.16 on 2026-09-12 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0022_discordchannel_receive_buyback"),
        ("tribes", "0033_fleet_commander_token_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TribeExternalGuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_role_id",
                    models.BigIntegerField(
                        help_text="Discord role snowflake granted to active tribe members."
                    ),
                ),
                (
                    "invite_channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Channel used to create one-time invites for pending joins.",
                        null=True,
                    ),
                ),
                (
                    "alert_channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Channel for cleanup_failed alerts; falls back to chief DM.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tribe_bindings",
                        to="discord.discordguild",
                    ),
                ),
                (
                    "tribe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_guild",
                        to="tribes.tribe",
                    ),
                ),
            ],
            options={
                "ordering": ["tribe__name"],
            },
        ),
        migrations.CreateModel(
            name="TribeExternalGuildSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_user_id", models.BigIntegerField()),
                (
                    "discord_username",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "discord_nickname",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "eve_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_join", "Pending join"),
                            ("present", "Present"),
                            ("pending_remove", "Pending remove"),
                            ("removed", "Removed"),
                            ("cleanup_failed", "Cleanup failed"),
                        ],
                        default="pending_join",
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="tribes.tribeexternalguild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribe_external_guild_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding", "discord_user_id"),
                        name="tribes_external_guild_seat_unique_binding_discord",
                    )
                ],
            },
        ),
    ]
