# Generated by Django 5.2.16 on 2026-09-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0034_tribe_external_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribeexternalguild",
            name="invite_channel_id",
        ),
    ]
