# Generated by Django 5.2.17 on 2026-10-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tribes", "0039_tribegroup_campaign_token_choice"),
        ("tribes", "0039_tribegroup_roster_hidden"),
    ]

    operations = []
