# Generated by Django 5.1.15 on 2026-06-21 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tribes", "0024_help_tickets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRequestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Dropdown label (e.g. "Contact the freighter team").',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown in the ticket thread welcome message.",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable slug for thread names (e.g. market.freighters).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Select-menu grouping label. Defaults to tribe name when linked.",
                        max_length=128,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users to @mention when a ticket is opened.",
                        related_name="help_request_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_request_category",
                        to="tribes.tribegroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "help request categories",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpTicketPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="HelpTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opener_discord_id", models.BigIntegerField()),
                ("thread_id", models.BigIntegerField(unique=True)),
                ("thread_name", models.CharField(max_length=100)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by_discord_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("close_reason", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="help_tickets.helprequestcategory",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_tickets_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opener",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_tickets_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "opened_at"],
                        name="help_tickets_cat_opened",
                    ),
                    models.Index(
                        fields=["status", "opened_at"],
                        name="help_tickets_status_opened",
                    ),
                ],
            },
        ),
    ]
