doctrines = [
    {
        "model": "fleets.evedoctrine",
        "pk": 9,
        "fields": {
            "name": "BIG ABS",
            "slug": "stratop-battlecruiser-composition",
            "description": "Battlecruiser composition for strategic operations like offensive structure fights.\r\n\r\nExcellent against T3C compositions ,T2 compositions, and outnumbered battleship compositions. Wide engagement profile. Utilizes 100mn afterburner to mitigate damage, or MWD to mitigate damage with range.\r\n\r\nVery low risk, easy to extract.",
            "created_at": "2023-04-06T19:36:18.910Z",
            "updated_at": "2024-02-07T22:26:58.816Z",
            "composition": "3 Claymore\r\n3 Huginn\r\n2 Lachesis\r\n30 Cyclone Fleet Issue\r\n1 Scimitar for every 4-5 enemy DPS",
            "active": True,
            "primary": True,
            "universal": False,
            "tags": [3, 5],
            "fittings": [26, 32, 84, 85, 89],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 17,
        "fields": {
            "name": "PROJEQS",
            "slug": "projexeq",
            "description": "This is the opposite of HAMSPAM, but is more versatile and just as effective at dismantling large fleets. Excellent spammable composition for nearly every ship, with the ability to stay under guns of battlecruisers and battleships with close range ammo.",
            "created_at": "2023-06-24T13:45:00.978Z",
            "updated_at": "2024-01-21T16:08:22.220Z",
            "composition": "40 Exequror Navy Issue\r\n5 Celestis\r\n5 Exequror",
            "active": True,
            "primary": False,
            "universal": False,
            "tags": [3, 5, 6],
            "fittings": [28, 88, 93, 185, 187],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 18,
        "fields": {
            "name": "Universal Support Doctrine",
            "slug": "universal-support-doctrine",
            "description": "These ships can be brought to any fleet, and are alt/newbro accessible.",
            "created_at": "2023-06-24T13:57:46.865Z",
            "updated_at": "2024-01-30T14:03:45.141Z",
            "composition": "None. Bring any number of these.",
            "active": True,
            "primary": False,
            "universal": True,
            "tags": [],
            "fittings": [49, 50, 52, 53, 77, 95, 144, 183, 188, 189, 190],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 22,
        "fields": {
            "name": "TFIs",
            "slug": "armor-battleships",
            "description": "Used for strategic fights in nearby space (titan bridge range) where capital ships will be involved. Most often for defensive timers, or special situations where we can hold a subcapital grid with battleships. Should always be accompanied by capital ships, and at least 1 FAX.\r\n\r\nDefault fittings are focused on fast response to a strategic engagement (capitals tackled, etc), but often we will be refitting our mid slots entirely.\r\n\r\nArtillery refits should always be carried for combat refitting purposes.",
            "created_at": "2023-11-20T02:42:36.999Z",
            "updated_at": "2024-01-21T17:25:39.870Z",
            "composition": "3 Damnation\r\n2 Eos\r\n2 Bhaalgorn\r\n2 Vindicator\r\n2 Devoter\r\n2 Loki\r\n2 Legion\r\n1 Nestor (firewall)\r\n15-20 Tempest Fleet Issue (fighting battlecruisers with artillery or using AC, critical mass)\r\n30-40 Tempest Fleet Issue (fighting battleships with artillery, critical mass)\r\n1 Guardian for every 3-4 enemy DPS\r\n\r\nAdditional alts are slammed into utility ships (dictors, hics, scorpions) if not multi-boxing mainline ships.",
            "active": True,
            "primary": True,
            "universal": False,
            "tags": [2, 3, 5],
            "fittings": [
                55,
                56,
                58,
                59,
                60,
                61,
                62,
                68,
                142,
                143,
                151,
                153,
                154,
            ],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 23,
        "fields": {
            "name": "Kikis",
            "slug": "kikis",
            "description": "Small ships that pack a serious punch with over 800 DPS. Typically used for bashing high EHP targets, or a quick response to killing unsupported capital ships.",
            "created_at": "2023-12-14T16:51:53.789Z",
            "updated_at": "2024-05-21T22:37:07.328Z",
            "composition": "15 Kikimora\r\n5 Kirin\r\n5 Stiletto",
            "active": False,
            "primary": False,
            "universal": False,
            "tags": [2, 5],
            "fittings": [95, 121, 122, 124, 125, 126, 184, 186],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 24,
        "fields": {
            "name": "SLEIPNIRS",
            "slug": "sleipnir",
            "description": "Artillery composition focused on fighting outnumbered by utilizing alpha and increased range. Brought in situations where we expect the enemy to have ridiculous logistics numbers (20+ logistics, FAX) and we will need exceptional upfront damage to alpha targets. T2 resist profile should allow us to punch up and at least fight 2:1, but will struggle to fight 3:1 / 4:1 due to medium range projection and expensive hulls.",
            "created_at": "2023-12-22T03:22:41.004Z",
            "updated_at": "2024-01-21T17:20:03.175Z",
            "composition": "5 Claymore\r\n5 Huginn\r\n30 Sleipnir (required for 100k alpha, critical mass for fighting BCs)\r\n1 Scimitar / Basilisk for every 3 enemy DPS\r\n\r\nLachesis highly recommended for points or dampeners.",
            "active": True,
            "primary": True,
            "universal": False,
            "tags": [3, 5],
            "fittings": [84, 85, 89, 132, 133, 136, 137],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 25,
        "fields": {
            "name": "Slippery Rats",
            "slug": "petes",
            "description": "Slippery",
            "created_at": "2024-01-19T19:39:57.093Z",
            "updated_at": "2024-02-25T17:28:23.883Z",
            "composition": "No composition",
            "active": False,
            "primary": False,
            "universal": False,
            "tags": [1, 3],
            "fittings": [155],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 26,
        "fields": {
            "name": "HAMSPAM",
            "slug": "hamspam",
            "description": "This is a cruiser level doctrine featuring the Osprey Navy Issue with Heavy Assault Missiles. It excels at dissecting battlecruiser and battleship railgun, beam laser, and artillery compositions by staying under their guns (2200 m/s) and applying significant damage. \r\n\r\nIt is designed to be cheap, versatile, and spam able from a wallet perspective. This composition won't win a grid, but it will trade exceptionally well in most cases.",
            "created_at": "2024-01-21T16:05:27.487Z",
            "updated_at": "2024-02-13T22:00:37.744Z",
            "composition": "5 Jaguar / Harpy / Stiletto\r\n5 Bifrost / Stork\r\n30 Osprey Navy Issue\r\n10 Osprey",
            "active": True,
            "primary": False,
            "universal": False,
            "tags": [2, 5, 6],
            "fittings": [40, 95, 104, 181, 182, 184, 186],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 27,
        "fields": {
            "name": "RETRIS",
            "slug": "retributions",
            "description": "Assault frigate doctrine for fast-paced skirmish engagements. Ideal for roaming, node events, or just general patrolling for killmails. Utilize booshes to kill things you have no business killing.",
            "created_at": "2024-02-07T14:36:43.421Z",
            "updated_at": "2024-02-07T14:38:06.380Z",
            "composition": "3x Command Destroyer\r\n5x Retribution\r\n2x Deacon",
            "active": True,
            "primary": False,
            "universal": False,
            "tags": [2, 4, 5, 6],
            "fittings": [185, 187, 188, 189, 195, 196],
        },
    },
    {
        "model": "fleets.evedoctrine",
        "pk": 28,
        "fields": {
            "name": "LEGIONS",
            "slug": "armor-t3cs",
            "description": "Mid-range armor composition used for supporting capital grids away from home. Significantly more versatile than Tempest Fleet Issues, and should be able to punch up due to signature tanking. If we are fighting several regions away from home, T3Cs only with covert refits for bridging. If we are fighting within titan range, bring DPS legions supported by traditional armor hulls.\r\n\r\nShould be supported by a FAX and 2-3 HAWs. This is an expensive composition, and is not made for trading ships. Use Sleipnirs if you intend on trading.",
            "created_at": "2024-03-27T16:49:18.000Z",
            "updated_at": "2024-04-07T14:39:33.718Z",
            "composition": "3x Link Ships (Legion, Proteus, Eos, Damnation)\r\n2x Web Ships (Loki, Vindicator, etc)\r\n30 DPS Legion / DPS Proteus \r\n10 LOGI Legion / LOGI Proteus\r\n5x Support Ships (Devoter, Scorpion, etc)",
            "active": True,
            "primary": True,
            "universal": False,
            "tags": [3, 5],
            "fittings": [209, 210, 211, 212, 213, 214, 215],
        },
    },
]
