# Generated by Django 5.1.9 on 2025-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedditScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subreddit", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField()),
                ("posting_day", models.CharField(max_length=12)),
                ("last_post_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
