# Generated by Django 5.1.9 on 2025-10-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditscheduledpost",
            name="posting_day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=12,
            ),
        ),
    ]
