# Generated by Django 5.1.9 on 2025-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0002_alter_redditscheduledpost_posting_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditscheduledpost",
            name="discord_channel",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="redditscheduledpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
