# Generated by Django 5.1.9 on 2025-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0003_redditscheduledpost_discord_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditscheduledpost",
            name="discord_channel",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
