# Generated by Django 5.1.9 on 2025-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0004_alter_redditscheduledpost_discord_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditscheduledpost",
            name="last_post_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
