# Generated by Django 5.1.9 on 2025-10-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0005_alter_redditscheduledpost_last_post_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditscheduledpost",
            name="flair",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
