# Generated by Django 5.1.2 on 2026-01-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0005_alter_redditscheduledpost_last_post_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redditscheduledpost",
            name="discord_channel",
        ),
        migrations.AddField(
            model_name="redditscheduledpost",
            name="discord_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="redditscheduledpost",
            name="flair_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="redditscheduledpost",
            name="last_reddit_post_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="redditscheduledpost",
            name="last_reddit_post_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
