# Generated by Django 5.1.9 on 2025-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0006_redditscheduledpost_flair"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditscheduledpost",
            name="latest_comment_url",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
