# Generated by Django 5.1.9 on 2025-10-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0007_redditscheduledpost_latest_comment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditscheduledpost",
            name="latest_fullname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
