# Generated by Django 5.1.2 on 2026-02-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0076_migrate_advanced_token_to_basic"),
        ("industry", "0003_industryorder_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryorder",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Station or structure where the order should be built/delivered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="industry_orders",
                to="eveonline.evelocation",
            ),
        ),
    ]
