# Generated by Django 5.1.2 on 2026-02-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0076_migrate_advanced_token_to_basic"),
        ("industry", "0004_industryorder_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "activity_id",
                    models.IntegerField(
                        help_text="Activity: 1=Manufacturing, 2=Researching TE, 3=Researching ME, etc."
                    ),
                ),
                ("blueprint_id", models.BigIntegerField()),
                ("blueprint_type_id", models.IntegerField(db_index=True)),
                ("blueprint_location_id", models.BigIntegerField()),
                ("facility_id", models.BigIntegerField()),
                ("location_id", models.BigIntegerField(db_index=True)),
                ("output_location_id", models.BigIntegerField()),
                ("status", models.CharField(db_index=True, max_length=32)),
                (
                    "installer_id",
                    models.BigIntegerField(
                        help_text="Character ID that installed the job."
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Duration in seconds."
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("runs", models.PositiveIntegerField()),
                ("licensed_runs", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=32, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_jobs",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
                "indexes": [
                    models.Index(
                        fields=["character", "status"],
                        name="industry_in_charact_5d12e3_idx",
                    )
                ],
            },
        ),
    ]
