# Generated by Django 5.1.2 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0005_add_industry_job"),
    ]

    operations = [
        migrations.DeleteModel(name="IndustryJob"),
    ]
