# Generated by Django 5.1.2 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eveuniverse",
            "0010_alter_eveindustryactivityduration_eve_type_and_more",
        ),
        ("industry", "0006_remove_industry_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("produce", "Produce"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "eve_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_product",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "industry product",
                "verbose_name_plural": "industry products",
            },
        ),
    ]
