# Generated by Django 5.1.2 on 2026-02-16

from django.db import migrations, models


def produce_to_integrated(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    IndustryProduct.objects.filter(strategy="produce").update(
        strategy="integrated"
    )


def integrated_to_produce(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    IndustryProduct.objects.filter(strategy="integrated").update(
        strategy="produce"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0007_industryproduct"),
    ]

    operations = [
        migrations.RunPython(produce_to_integrated, integrated_to_produce),
        migrations.AlterField(
            model_name="industryproduct",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("export", "Export"),
                    ("integrated", "Integrated"),
                ],
                max_length=16,
            ),
        ),
    ]
