# Generated by Django 5.1.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0008_produce_to_integrated"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryproduct",
            name="breakdown",
            field=models.JSONField(
                blank=True,
                help_text="Cached nested component tree (root quantity=1). From get_nested_breakdown.",
                null=True,
            ),
        ),
    ]
