# Generated by Django 5.1.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0009_industryproduct_breakdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industryproduct",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("build", "Build"),
                    ("export", "Export"),
                    ("integrated", "Integrated"),
                ],
                max_length=16,
            ),
        ),
    ]
