# Generated by Django 5.1.2 on 2026-02-16

from django.db import migrations, models


def strategy_to_trade_strategy_produced(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    for p in IndustryProduct.objects.all():
        if p.strategy == "export":
            p.trade_strategy = "export"
            p.produced = False
        elif p.strategy in ("integrated", "build"):
            p.trade_strategy = "import"
            p.produced = True
        else:
            # import or anything else
            p.trade_strategy = "import"
            p.produced = False
        p.save()


def trade_strategy_produced_to_strategy(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    for p in IndustryProduct.objects.all():
        if p.trade_strategy == "export":
            p.strategy = "export"
        elif p.produced:
            p.strategy = "integrated"
        else:
            p.strategy = "import"
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0010_industryproduct_build_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryproduct",
            name="trade_strategy",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("export", "Export"),
                    ("stockpile", "Stockpile"),
                ],
                default="import",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="industryproduct",
            name="produced",
            field=models.BooleanField(
                default=False,
                help_text="True if we build this; False if we import or otherwise source it.",
            ),
        ),
        migrations.RunPython(
            strategy_to_trade_strategy_produced,
            trade_strategy_produced_to_strategy,
        ),
        migrations.RemoveField(
            model_name="industryproduct",
            name="strategy",
        ),
    ]
