# Generated by Django 5.1.2 on 2026-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0011_trade_strategy_produced"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryproduct",
            name="supplied_for",
            field=models.ManyToManyField(
                blank=True,
                help_text="Industry products that use this one as a direct component (this is supplied for those).",
                related_name="supplies",
                to="industry.industryproduct",
            ),
        ),
        migrations.AlterField(
            model_name="industryproduct",
            name="breakdown",
            field=models.JSONField(
                blank=True,
                help_text="Full-depth nested component tree (root quantity=1). From get_breakdown_for_industry_product.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="industryproduct",
            name="trade_strategy",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("export", "Export"),
                    ("stockpile", "Stockpile"),
                ],
                default="import",
                max_length=16,
            ),
        ),
    ]
