# Generated by Django 5.1.2 on 2026-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0012_add_supplied_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryproduct",
            name="harvested",
            field=models.BooleanField(
                default=False,
                help_text="True for types with no blueprint (e.g. ore, ice); we obtain these by mining/harvesting.",
            ),
        ),
        migrations.AlterField(
            model_name="industryproduct",
            name="produced",
            field=models.BooleanField(
                default=False,
                help_text="True if we build this from a blueprint; False if we import or otherwise source it.",
            ),
        ),
    ]
