# Generated by Django 5.1.2 on 2026-02-17

from django.db import migrations, models


def to_strategy(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    for p in IndustryProduct.objects.all():
        if getattr(p, "harvested", False):
            p.strategy = "harvested"
        elif getattr(p, "produced", False):
            p.strategy = "produced"
        else:
            p.strategy = "imported"
        p.save()


def from_strategy(apps, schema_editor):
    IndustryProduct = apps.get_model("industry", "IndustryProduct")
    for p in IndustryProduct.objects.all():
        if p.strategy == "harvested":
            p.trade_strategy = "import"
            p.produced = False
            p.harvested = True
        elif p.strategy == "produced":
            p.trade_strategy = "import"
            p.produced = True
            p.harvested = False
        else:
            p.trade_strategy = "import"
            p.produced = False
            p.harvested = False
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0013_add_harvested"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryproduct",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("imported", "Imported"),
                    ("harvested", "Harvested"),
                    ("produced", "Produced"),
                ],
                default="imported",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(to_strategy, from_strategy),
        migrations.RemoveField(
            model_name="industryproduct",
            name="trade_strategy",
        ),
        migrations.RemoveField(
            model_name="industryproduct",
            name="produced",
        ),
        migrations.RemoveField(
            model_name="industryproduct",
            name="harvested",
        ),
    ]
