# Generated by Django 5.1.2 on 2026-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0015_miningupgradecompletion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="miningupgradecompletion",
            new_name="industry_mi_system__756d08_idx",
            old_name="industry_mi_system__a2c8b4_idx",
        ),
        migrations.AlterField(
            model_name="industryproduct",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("imported", "Imported"),
                    ("harvested", "Harvested"),
                    ("supplied", "Supplied"),
                    ("produced", "Produced"),
                ],
                default="imported",
                max_length=16,
            ),
        ),
    ]
