# Generated by Django 5.1.2 on 2026-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0019_industry_order_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryorderitem",
            name="target_estimated_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target estimated margin (ISK) for this line; shown on the public order list.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="industryorderitem",
            name="target_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target unit price (ISK) for this line; shown on the public order list.",
                max_digits=20,
                null=True,
            ),
        ),
    ]
