# Generated by Django 5.1.15 on 2026-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0022_remove_industryorder_order_identifier"),
        ("tribes", "0020_add_tribegroupactivity_point_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryorder",
            name="tribe_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tribe groups this order belongs to (reporting, town hall).",
                related_name="industry_orders",
                to="tribes.tribegroup",
            ),
        ),
    ]
