# Generated by Django 5.1.15 on 2026-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0023_industryorder_tribe_groups"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="miningupgradecompletion",
            new_name="industry_mi_sov_sys_68b836_idx",
            old_name="industry_mi_sov_syst_comp_idx",
        ),
    ]
