# Generated by Django 5.2.16 on 2026-07-17 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry",
            "0024_rename_industry_mi_sov_syst_comp_idx_industry_mi_sov_sys_68b836_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustrySystemCostIndex",
            fields=[
                (
                    "solar_system_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("manufacturing", models.FloatField(default=0.0)),
                ("reaction", models.FloatField(default=0.0)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Industry system cost index",
                "verbose_name_plural": "Industry system cost indices",
            },
        ),
    ]
