# Generated by Django 5.2.16 on 2026-07-17 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0025_industrysystemcostindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLpStoreOffer",
            fields=[
                (
                    "offer_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("corporation_id", models.BigIntegerField()),
                ("type_id", models.BigIntegerField(db_index=True)),
                ("lp_cost", models.PositiveIntegerField()),
                ("isk_cost", models.BigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Industry LP store offer",
                "verbose_name_plural": "Industry LP store offers",
            },
        ),
    ]
