# Generated by Django 5.2.16 on 2026-07-17 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0097_industry_job_status_blueprint_id_idx"),
        ("industry", "0026_industrylpstoreoffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLoyaltyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "corporation_id",
                    models.BigIntegerField(
                        help_text="ESI NPC corporation ID for this LP store (e.g. TLIB 1000182).",
                        unique=True,
                    ),
                ),
                (
                    "default_isk_per_lp",
                    models.PositiveIntegerField(
                        default=800,
                        help_text="Default ISK per LP used when planning navy BPC costs.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry loyalty point",
                "verbose_name_plural": "Industry loyalty points",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="industrylpstoreoffer",
            name="corporation_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name="IndustryLoyaltyPointContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=64)),
                (
                    "discord_user_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "discord_username",
                    models.CharField(blank=True, max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eve_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_contacts",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "loyalty_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="industry.industryloyaltypoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry loyalty point contact",
                "verbose_name_plural": "Industry loyalty point contacts",
                "ordering": ["loyalty_point__name", "character_name"],
            },
        ),
    ]
