# Generated by Django 5.2.16 on 2026-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0029_industrycontractassociation"),
        ("industry", "0029_lp_accounts_and_ledger"),
    ]

    operations = []
