# Generated by Django 5.2.16 on 2026-07-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0097_industry_job_status_blueprint_id_idx"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry", "0030_merge_contract_assoc_and_lp_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryOrderBlueprintCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="industryorderblueprintcoordinator",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industry_order_blueprint_coordinators",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="industryorderblueprintcoordinator",
            name="eve_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Order item types whose blueprints this character can supply.",
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AddField(
            model_name="industryorderblueprintcoordinator",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blueprint_coordinators",
                to="industry.industryorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="industryorderblueprintcoordinator",
            constraint=models.UniqueConstraint(
                fields=("order", "character"),
                name="uniq_order_blueprint_coordinator_character",
            ),
        ),
    ]
