# Generated by Django 5.2.16 on 2026-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0031_industryorderblueprintcoordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryorderitemassignment",
            name="has_blueprints",
            field=models.BooleanField(
                default=False,
                help_text="Whether the assignee has blueprints for this line.",
            ),
        ),
    ]
