# Generated by Django 5.2.16 on 2026-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0033_industryorder_mineral_pi_coordinators"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="industrycontractassociation",
            new_name="industry_in_order_i_8a15f2_idx",
            old_name="industry_in_order_i_7c2a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="industrycontractassociation",
            new_name="industry_in_contrac_04aef4_idx",
            old_name="industry_in_contrac_9f4e2d_idx",
        ),
        migrations.AddField(
            model_name="industryorder",
            name="profit_breakdown",
            field=models.JSONField(
                blank=True,
                help_text="Frozen profit/price breakdown for graphs and order summaries (rows, totals, assumptions, facility_key, compressed).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="industryorder",
            name="profit_breakdown_computed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When profit_breakdown was last computed and stored.",
                null=True,
            ),
        ),
    ]
