# Generated by Django 5.2.16 on 2026-07-31 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0034_industryorder_profit_breakdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLoyaltyPointMarketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("quantity", models.BigIntegerField()),
                ("isk_per_lp", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("claimed", "Claimed"),
                            ("awaiting_lp", "Awaiting LP"),
                            ("awaiting_isk", "Awaiting ISK"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "destination_character_name",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "discord_thread_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_market_orders_claimed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_point_market_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loyalty_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_orders",
                        to="industry.industryloyaltypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry loyalty point market order",
                "verbose_name_plural": "Industry loyalty point market orders",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "side", "-created_at"],
                        name="industry_lp_mkt_status_side",
                    )
                ],
            },
        ),
    ]
