# Generated by Django 5.2.16 on 2026-08-01 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0035_industryloyaltypointmarketorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="industryloyaltypointledgerentry",
            name="counterparty_character_name",
            field=models.CharField(
                blank=True,
                help_text="Destination / receiving character when known.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="industryloyaltypointledgerentry",
            name="counterparty_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Other side of the trade (claimer / Conversion Team).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_point_ledger_entries_as_counterparty",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="industryloyaltypointledgerentry",
            name="market_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Buyback market order that produced this entry, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="industry.industryloyaltypointmarketorder",
            ),
        ),
        migrations.AddField(
            model_name="industryloyaltypointledgerentry",
            name="seller_character_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="industryloyaltypointledgerentry",
            name="seller_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Pilot who sold LP (market order creator).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_point_ledger_entries_as_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
