# Generated by Django 5.2.16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0036_lp_ledger_counterparties"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLoyaltyPointMarketOrderClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="LP quantity claimed in this fill.",
                    ),
                ),
                (
                    "destination_character_name",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "destination_corporation_name",
                    models.CharField(blank=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_point_market_order_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="industry.industryloyaltypointmarketorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry loyalty point market order claim",
                "verbose_name_plural": (
                    "Industry loyalty point market order claims"
                ),
                "ordering": ["created_at", "id"],
            },
        ),
    ]
