# Generated by Django 5.2.16 on 2026-08-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0037_industryloyaltypointmarketorderclaim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLoyaltyPointPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_isk_per_lp",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "new_isk_per_lp",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty for published currency default rate changes; set for account offer price changes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="industry.industryloyaltypointaccount",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_point_price_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loyalty_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="industry.industryloyaltypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry loyalty point price history",
                "verbose_name_plural": "Industry loyalty point price histories",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
