# Generated by Django 5.2.16 on 2026-08-04 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0038_lp_price_history"),
    ]

    operations = [
        # ESI cache is collision-corrupted under offer_id PK; wipe and rebuild.
        migrations.DeleteModel(name="IndustryLpStoreOffer"),
        migrations.CreateModel(
            name="IndustryLpStoreOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.BigIntegerField()),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("type_id", models.BigIntegerField(db_index=True)),
                ("lp_cost", models.PositiveIntegerField()),
                ("isk_cost", models.BigIntegerField()),
                (
                    "ak_cost",
                    models.BigIntegerField(
                        default=0,
                        help_text=(
                            "ESI ak_cost (EverMarks / alliance points); "
                            "0 when unused."
                        ),
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Industry LP store offer",
                "verbose_name_plural": "Industry LP store offers",
            },
        ),
        migrations.CreateModel(
            name="IndustryLpStoreOfferRequiredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.BigIntegerField(db_index=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_items",
                        to="industry.industrylpstoreoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry LP store offer required item",
                "verbose_name_plural": (
                    "Industry LP store offer required items"
                ),
            },
        ),
        migrations.AddIndex(
            model_name="industrylpstoreoffer",
            index=models.Index(
                fields=["corporation_id", "type_id"],
                name="industry_lp_offer_corp_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrylpstoreoffer",
            constraint=models.UniqueConstraint(
                fields=("corporation_id", "offer_id"),
                name="uniq_lp_store_offer_corp_offer",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrylpstoreofferrequireditem",
            constraint=models.UniqueConstraint(
                fields=("offer", "type_id"),
                name="uniq_lp_store_offer_req_type",
            ),
        ),
    ]
