# Generated by Django 5.2.16 on 2026-08-04 23:27

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_quantity(apps, schema_editor):
    Assignment = apps.get_model("industry", "IndustryOrderItemAssignment")
    Assignment.objects.filter(delivered_at__isnull=False).update(
        delivered_quantity=F("quantity")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0039_lp_store_offer_full_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryorderitemassignment",
            name="delivered_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Units already delivered against this claim (supports partial deliveries).",
            ),
        ),
        migrations.AlterField(
            model_name="industryorderitemassignment",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this assignment was fully delivered.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_delivered_quantity, noop_reverse),
    ]
