# Generated by Django 5.2.16 on 2026-08-05 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0040_assignment_delivered_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryLpStoreOfferEconomics",
            fields=[
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="economics_row",
                        serialize=False,
                        to="industry.industrylpstoreoffer",
                    ),
                ),
                ("esi_offer_id", models.BigIntegerField(db_index=True)),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("type_id", models.BigIntegerField(db_index=True)),
                ("type_name", models.CharField(db_index=True, max_length=255)),
                (
                    "currency_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "kind",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("lp_cost", models.PositiveIntegerField()),
                ("isk_cost", models.BigIntegerField()),
                ("ak_cost", models.BigIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "required_items_summary",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("other_cost", models.BigIntegerField(blank=True, null=True)),
                ("jita_sell", models.BigIntegerField(blank=True, null=True)),
                ("jita_buy", models.BigIntegerField(blank=True, null=True)),
                (
                    "conversion_isk_per_lp_sell",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "conversion_isk_per_lp_buy",
                    models.FloatField(blank=True, null=True),
                ),
                ("volume_1d", models.BigIntegerField(blank=True, null=True)),
                ("volume_7d", models.BigIntegerField(blank=True, null=True)),
                ("volume_30d", models.BigIntegerField(blank=True, null=True)),
                (
                    "involves_tag",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "involves_supply_package",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "involves_chip",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "is_useless",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "is_below_set_lp_price",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("offer_updated_at", models.DateTimeField()),
                (
                    "rebuilt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry LP store offer economics",
                "verbose_name_plural": "Industry LP store offer economics",
                "indexes": [
                    models.Index(
                        fields=[
                            "corporation_id",
                            "-conversion_isk_per_lp_sell",
                        ],
                        name="industry_lp_econ_corp_conv",
                    )
                ],
            },
        ),
    ]
