# Generated by Django for LP conversion breakdown fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0044_lp_store_offer_economics_avg_7d"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrylpstoreoffereconomics",
            name="input_cost_isk",
            field=models.BigIntegerField(
                blank=True,
                help_text=(
                    "ISK cost + required items + Amamake mfg "
                    "(no alliance freight)."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="industrylpstoreoffereconomics",
            name="input_freight_isk",
            field=models.BigIntegerField(
                blank=True,
                help_text=(
                    "Red Frog value freight on required items + materials."
                ),
                null=True,
            ),
        ),
    ]
