# Generated by Django 5.2.16 on 2026-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0047_close_orphan_lp_buyback_discord_threads"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryloyaltypoint",
            name="allow_buy",
            field=models.BooleanField(
                default=True,
                help_text="Allow buy orders (Conversion Team purchasing this LP).",
            ),
        ),
        migrations.AddField(
            model_name="industryloyaltypoint",
            name="allow_sell",
            field=models.BooleanField(
                default=True,
                help_text="Allow sell orders (pilots selling this LP to the alliance).",
            ),
        ),
    ]
