# Generated by Django 5.2.17 on 2026-10-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0049_industryorder_campaign"),
        ("industry", "0049_keep_shared_rows_when_actor_deleted"),
    ]

    operations = []
