import { experimental_AstroContainer as AstroContainer } from 'astro/container'
import { expect, test } from 'vitest'

import AmamakeMarketReportIssue from '@components/blocks/amamake-market/AmamakeMarketReportIssue.astro'
import { get_latest_issue } from '@/data/amamake-market'

test('AmamakeMarketReportIssue renders the latest issue sections', async () => {
    const container = await AstroContainer.create()
    const issue = get_latest_issue()
    const result = await container.renderToString(AmamakeMarketReportIssue, {
        props: { issue },
    })

    expect(result).toContain('Market sales overview')
    expect(result).toContain('What moved through the Amamake keepstar this month, by class and by day.')
    expect(result).not.toContain('Through the book')
    expect(result).not.toContain('Inferred ISK sold at the freeport, by calendar day')
    expect(result).not.toContain('August inferred fills by SDE class')
    expect(result).toContain('Top Items Sold')
    expect(result).toMatch(/href="#sold"[^>]*>Top Items Sold/)
    expect(result).toContain('Biggest tickets on the book.')
    expect(result).not.toContain('Markup is included so that you can gauge how much profit traders made on them.')
    expect(result).not.toContain('Rank by ISK')
    expect(result).not.toContain('Top types by inferred ISK')
    expect(result).not.toContain('>What sold<')
    expect(result).toContain('hx-get')
    expect(result).toContain('amamake_market_sold_types_component')
    expect(result).toContain('sold_class=all')
    expect(result).toContain('sold_class=ships')
    expect(result).toContain('aria-pressed="true"')
    expect(result).toContain('Demand')
    expect(result).toContain('Sold vs lost')
    expect(result).toContain('What we sold here versus what died in the warzone.')
    expect(result).toContain('Ships destroyed by system')
    expect(result).toContain('Loudest systems this month.')
    expect(result).not.toContain('Shop in the quiet ones')
    expect(result).not.toContain('whoever flew the pipe')
    expect(result).not.toContain('August counts. Sells: inferred fills')
    expect(result).toContain('Sold in Amamake')
    expect(result).toContain('Died in the warzone')
    expect(result).toContain('href="#demand"')
    expect(result).not.toContain('href="#hulls"')
    expect(result).not.toContain('href="#catchment"')
    expect(result).not.toContain('Died vs sold')
    expect(result).not.toContain('The catchment')
    expect(result).not.toContain('Focus of the month')
    expect(result).not.toContain('Focus story')
    expect(result).not.toContain('Build in Amamake')
    expect(result).not.toContain('Loyalty points')
    expect(result).toContain('Ships destroyed at the hub')
    expect(result).toContain('ISK sold by day')
    expect(result).not.toContain('Inferred ISK sold')
    expect(result).not.toContain('Inferred profit</span>')
    expect(result).toContain('Profit')
    expect(result).toContain(issue.sales.profit_label)
    expect(result).toContain('450 ISK/m³')
    expect(result).toContain(issue.catchment.amamake.ships.toLocaleString('en-US'))
    expect(result).toContain('Sell orders by class')
    expect(result).toContain('Markup')
    expect(result).not.toContain('Where the ISK went')
    expect(result).not.toContain('1–7 Aug')
    expect(result).toContain('Ships')
    expect(result).toContain('Rigs')
    expect(result).toContain('Charges')
    expect(result).toContain('Drones')
    expect(result).toContain('All Items Sold')
    expect(result).toContain('href="#volume"')
    expect(result).toMatch(/href="#volume"[^>]*>All Items Sold/)
    expect(result).toContain('Everything that moved. Markup still vs Jita after freight.')
    expect(result).not.toContain('Items worth seeding')
    expect(result).not.toContain('href="#margins"')
    expect(result).not.toContain('>Worth seeding<')
    expect(result).not.toContain('>Volume<')
    expect(result).toContain('Orders')
    expect(result).not.toContain('>Fills<')
    expect(result).toMatch(/units · [\d,]+ orders/)
    expect(result).not.toMatch(/units · [\d,]+ fills/)
    expect(result).not.toContain('Ranked by extra ISK (spread × units), not the fattest percent.')
    expect(result).not.toContain('Volume that still pays after Jita and the hauler.')
    expect(result).toContain('amamake_market_volume_component')
    expect(result).toContain('sold_class=all')
    expect(result).toContain('Filter All Items Sold by class')
    expect(result).not.toContain('Sort All Items Sold')
    expect(result).toContain('Search types')
    expect(result).toContain('placeholder="Search types…')
    expect(result).not.toContain('Import vs local')
    expect(result).not.toContain('The shelf')
    expect(result).not.toContain('Use the hub')
    expect(result).toContain('How to get involved')
    expect(result).toContain('href="#get-involved"')
    expect(result).toContain('Find the holes')
    expect(result).toContain('Haul it in')
    expect(result).toContain('List it')
    expect(result).toContain('Coverage and gaps')
    expect(result).toContain('Freight calculator')
    expect(result).toContain('/market/ops/sell_orders/')
    expect(result).toContain('/market/freight/calculator/')
    expect(result).toContain('PushX')
    expect(result).toContain('Ready to seed?')
    expect(result).not.toContain('About the numbers')
    expect(result).not.toContain('The month')
    expect(result).not.toContain('href="#month"')
    expect(result).not.toContain('Hello sales tax enjoyers')
    expect(result).not.toContain('Kamela ate capitals. Amamake sold destroyers.')
    expect(result).not.toContain('Fill / Jita')
    expect(result).not.toContain('Rorqual Blueprint')
    expect(result).not.toContain('Loki Hrada-Oki Offender SKIN')
    expect(result).not.toContain('href="#methodology"')
    expect(result).toContain('Published by')
    expect(result).toContain('Minmatar Fleet order-book snapshots')
    expect(result).toContain(issue.period_utc)
    expect(result).toContain('70 FW systems')
    expect(result).toContain('Holder mark')
    expect(result).not.toContain('href="#contracts"')
    expect(result).not.toContain('href="#import"')
    expect(result).not.toContain('href="#shelf"')
    expect(result).toContain('Amamake Economic Report')
    expect(result).toContain(issue.top_types.rows[0]!.name)
    expect(result).toContain(issue.sales.isk_label)
    expect(result).not.toContain('Capital ISK')
    expect(result).not.toContain('Amamake share of warzone ships')
    expect(result).not.toContain('Heimatar pipe share of warzone ships')
    expect(result).not.toContain('Characters on Amamake mails')
    expect(result).not.toContain('Where the warzone ships died')
    expect(result).not.toContain('In Amamake')
    expect(result).not.toContain('Warzone ships')
    expect(result).not.toContain('/campaigns/amamake-market')
})
