import { experimental_AstroContainer as AstroContainer } from 'astro/container'
import { expect, test } from 'vitest'

import AmamakeMarketReportIssue from '@components/blocks/amamake-market/AmamakeMarketReportIssue.astro'
import { get_latest_issue } from '@/data/amamake-market'

test('AmamakeMarketReportIssue renders the latest issue sections', async () => {
    const container = await AstroContainer.create()
    const issue = get_latest_issue()
    const result = await container.renderToString(AmamakeMarketReportIssue, {
        props: { issue },
    })

    expect(result).toContain('Market sales overview')
    expect(result).toContain('A high level overview of the items that sold in the Amamake freeport keepstar, broken down by category and timeline.')
    expect(result).not.toContain('Through the book')
    expect(result).not.toContain('Inferred ISK sold at the freeport, by calendar day')
    expect(result).not.toContain('August inferred fills by SDE class')
    expect(result).toContain('What sold')
    expect(result).toContain('The top items sold for each category. Markup is included so that you can gauge how much profit traders made on them.')
    expect(result).not.toContain('Rank by ISK')
    expect(result).not.toContain('Top types by inferred ISK')
    expect(result).toContain('hx-get')
    expect(result).toContain('amamake_market_sold_types_component')
    expect(result).toContain('sold_class=all')
    expect(result).toContain('sold_class=ships')
    expect(result).toContain('aria-pressed="true"')
    expect(result).toContain('Market Capture')
    expect(result).toContain('Hulls sold in Amamake versus lost in the warzone, and the systems around the shop that feed the book.')
    expect(result).toContain('Sold in Amamake')
    expect(result).toContain('Died in the warzone')
    expect(result).toContain('href="#capture"')
    expect(result).not.toContain('href="#hulls"')
    expect(result).not.toContain('href="#catchment"')
    expect(result).not.toContain('Died vs sold')
    expect(result).not.toContain('The catchment')
    expect(result).not.toContain('Focus of the month')
    expect(result).not.toContain('Focus story')
    expect(result).not.toContain('Build in Amamake')
    expect(result).not.toContain('Loyalty points')
    expect(result).toContain('Ships destroyed at the hub')
    expect(result).toContain('Inferred profit')
    expect(result).toContain(issue.sales.profit_label)
    expect(result).toContain('450 ISK/m³')
    expect(result).toContain(issue.catchment.amamake.ships.toLocaleString('en-US'))
    expect(result).toContain('Sell orders by class')
    expect(result).toContain('Markup')
    expect(result).not.toContain('Where the ISK went')
    expect(result).not.toContain('1–7 Aug')
    expect(result).toContain('Ships')
    expect(result).toContain('Rigs')
    expect(result).toContain('Charges')
    expect(result).toContain('Drones')
    expect(result).toContain('Items worth seeding')
    expect(result).not.toContain('>Worth seeding<')
    expect(result).toContain('High volume items that still offer great profit margins.')
    expect(result).not.toContain('Ranked by extra ISK (spread × units), not the fattest percent.')
    expect(result).toContain(issue.margins.rows[0]!.name)
    expect(result).not.toContain('Import vs local')
    expect(result).not.toContain('The shelf')
    expect(result).not.toContain('Use the hub')
    expect(result).not.toContain('About the numbers')
    expect(result).not.toContain('href="#contracts"')
    expect(result).not.toContain('href="#import"')
    expect(result).not.toContain('href="#shelf"')
    expect(result).toContain('The month')
    expect(result).toContain('Amamake Economic Report')
    expect(result).toContain(issue.top_types.rows[0]!.name)
    expect(result).toContain(issue.sales.isk_label)
    expect(result).not.toContain('/campaigns/amamake-market')
})
