# Generated by Django 5.1.9 on 2025-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditentry_old_character_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="old_character_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
