# Generated by Django 5.1.9 on 2025-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditentry_old_character_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("user_registered", "User registered"),
                    ("user_deleted", "User deleteed"),
                    ("primary_char", "Primary character set"),
                    ("character_added", "Character added"),
                    ("character_deleted", "Character deleted"),
                    ("team_change", "Team changed"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
