name: deploy to production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USERNAME }}
          password: ${{ secrets.UBUNTU_PASSWORD }}
          script: cd /home/minmatar/minmatar.org; git pull; docker-compose -f docker-compose-prod.yml up -d --build
  notify-discord-failure:
    name: Notify Discord Failure
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "New release has failed to deploy! 😢"
  notify-discord-success:
    name: Notify Discord Success
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: Notify Discord Success
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "New release has been successfully deployed! 🚀"
