# Generated by Django 5.1.15 on 2026-06-19 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("message", models.TextField()),
                (
                    "author_display",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedMonitoredSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solar_system_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fw_warzone", "FW warzone (seeded)"),
                            ("manual", "Manual admin addition"),
                        ],
                        default="fw_warzone",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeedR2z2Cursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sequence_id", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "R2Z2 cursor",
            },
        ),
        migrations.CreateModel(
            name="FeedRollupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollup_code", models.CharField(max_length=64, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feed rollup config",
            },
        ),
        migrations.CreateModel(
            name="FeedCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("kill_burst", "Kill burst"),
                            ("fleet_engagement", "Fleet engagement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cluster_key", models.CharField(max_length=256, unique=True)),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                (
                    "dominant_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField()),
                ("last_kill_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("kill_count", models.PositiveIntegerField(default=0)),
                ("pilot_count", models.PositiveIntegerField(default=0)),
                ("ship_counts", models.JSONField(default=dict)),
                ("attacker_ids", models.JSONField(default=list)),
                ("killmail_ids", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_kill_at"],
                "indexes": [
                    models.Index(
                        fields=["cluster_type", "is_active"],
                        name="feed_feedcl_cluster_954ee3_idx",
                    ),
                    models.Index(
                        fields=["solar_system_id", "started_at"],
                        name="feed_feedcl_solar_s_679c13_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fleet_active", "Fleet active"),
                            ("killmail_batch", "Killmail batch"),
                            ("communication", "Communication"),
                            ("militia_joins", "Militia joins"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("title", models.CharField(max_length=256)),
                (
                    "subheader",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("preview", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(default=dict)),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("militia", "Militia"),
                            ("amarr", "Amarr"),
                        ],
                        default="combat",
                        max_length=16,
                    ),
                ),
                (
                    "rollup_code",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("rollup_version", models.PositiveIntegerField(default=1)),
                (
                    "cluster_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=256
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-occurred_at", "-id"],
                        name="feed_feedev_occurre_30cd72_idx",
                    ),
                    models.Index(
                        fields=["rollup_code", "cluster_key"],
                        name="feed_feedev_rollup__408ca1_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="feed_feedev_source__7e38b9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cluster_key__gt", "")),
                        fields=("rollup_code", "cluster_key"),
                        name="feed_event_rollup_cluster_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("source_type__gt", "")),
                        fields=("source_type", "source_id"),
                        name="feed_event_source_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedEventAnnouncementLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed_announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="feed.feedannouncement",
                    ),
                ),
                (
                    "feed_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_link",
                        to="feed.feedevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedKillmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "killmail_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("hash", models.CharField(max_length=64)),
                ("killmail_time", models.DateTimeField(db_index=True)),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                (
                    "victim_character_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_ship_type_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("attacker_summary", models.JSONField(default=list)),
                ("raw_killmail", models.JSONField()),
                ("zkb_meta", models.JSONField(default=dict)),
                (
                    "zkill_sequence_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-killmail_time"],
                "indexes": [
                    models.Index(
                        fields=["solar_system_id", "killmail_time"],
                        name="feed_feedki_solar_s_f60131_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedMilitiaFirstSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("faction_id", models.IntegerField(db_index=True)),
                ("first_seen_at", models.DateTimeField()),
                ("first_seen_killmail_id", models.BigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attacker", "Attacker"),
                            ("victim", "Victim"),
                        ],
                        max_length=16,
                    ),
                ),
                ("solar_system_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-first_seen_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_id", "faction_id"),
                        name="feed_militia_first_seen_char_faction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedEventFleetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fleet_instance_id", models.BigIntegerField(db_index=True)),
                (
                    "feed_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_links",
                        to="feed.feedevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_event", "fleet_instance_id"),
                        name="feed_event_fleet_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedEventKillmailLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killmail_links",
                        to="feed.feedevent",
                    ),
                ),
                (
                    "feed_killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="feed.feedkillmail",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_event", "feed_killmail"),
                        name="feed_event_killmail_unique",
                    )
                ],
            },
        ),
    ]
