# Generated by Django 5.1.15 on 2026-06-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("corporation", "Corporation"),
                            ("alliance", "Alliance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                (
                    "militia_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("killmail", "Killmail ESI tag"),
                            ("esi_fw_stats", "ESI FW stats"),
                            ("esi_corporation", "ESI corporation"),
                            ("site_character", "Site character record"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "last_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["entity_type", "entity_id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "militia_faction_id"],
                        name="feed_feedaf_entity__f7473d_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "last_confirmed_at"],
                        name="feed_feedaf_entity__3e1c7f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "entity_id"),
                        name="feed_affiliation_entity_unique",
                    )
                ],
            },
        ),
    ]
