# Generated by Django 5.1.15 on 2026-06-20

from django.db import migrations, models

_LEGACY_RESOLVED_SOURCES = frozenset(
    {
        "killmail",
        "esi_affiliations",
        "esi_fw_stats",
        "site_character",
        "not_enlisted",
    }
)


def _normalize_source(old_source: str, militia_faction_id) -> str:
    if old_source == "pending":
        return "pending"
    if militia_faction_id is not None:
        return "esi_affiliations"
    if old_source in _LEGACY_RESOLVED_SOURCES:
        return "not_enlisted"
    return "not_enlisted"


def copy_character_affiliations(apps, schema_editor):
    Old = apps.get_model("feed", "FeedAffiliation")
    New = apps.get_model("feed", "FeedCharacterAffiliation")

    rows = []
    for old in Old.objects.filter(entity_type="character").iterator():
        rows.append(
            New(
                character_id=old.entity_id,
                militia_faction_id=old.militia_faction_id,
                corporation_id=old.corporation_id,
                alliance_id=old.alliance_id,
                source=_normalize_source(old.source, old.militia_faction_id),
                last_confirmed_at=old.last_confirmed_at,
                created_at=old.created_at,
                updated_at=old.updated_at,
            )
        )
    if rows:
        New.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_feedaffiliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCharacterAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                (
                    "militia_faction_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "corporation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pending", "Pending populate"),
                            ("esi_affiliations", "ESI affiliations batch"),
                            ("not_enlisted", "Checked, not enlisted"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "last_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["character_id"],
            },
        ),
        migrations.RunPython(
            copy_character_affiliations,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="feedcharacteraffiliation",
            index=models.Index(
                fields=["source", "created_at"],
                name="feed_feedch_source_8a1f2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedcharacteraffiliation",
            index=models.Index(
                fields=["last_confirmed_at"],
                name="feed_feedch_last_co_4d9e81_idx",
            ),
        ),
        migrations.DeleteModel(
            name="FeedAffiliation",
        ),
    ]
