# Generated by Django 5.1.15 on 2026-06-20

from django.db import migrations


def delete_communication_events(apps, schema_editor):
    FeedEvent = apps.get_model("feed", "FeedEvent")
    FeedEvent.objects.filter(kind="communication").delete()
    FeedEvent.objects.filter(rollup_code="communication").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_feedcharacteraffiliation"),
    ]

    operations = [
        migrations.RunPython(
            delete_communication_events,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="FeedEventAnnouncementLink",
        ),
        migrations.DeleteModel(
            name="FeedAnnouncement",
        ),
    ]
