# Generated by Django 5.1.15 on 2026-06-20

from django.db import migrations, models


def copy_esi_checked_at(apps, schema_editor):
    FeedCharacterAffiliation = apps.get_model(
        "feed", "FeedCharacterAffiliation"
    )
    for row in FeedCharacterAffiliation.objects.all().iterator():
        if (
            row.source in ("esi_affiliations", "not_enlisted")
            and row.last_confirmed_at
        ):
            FeedCharacterAffiliation.objects.filter(pk=row.pk).update(
                esi_checked_at=row.last_confirmed_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_remove_feed_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedcharacteraffiliation",
            name="esi_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When ESI affiliations last confirmed this row.",
                null=True,
            ),
        ),
        migrations.RunPython(copy_esi_checked_at, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="feedcharacteraffiliation",
            name="feed_feedch_source_8a1f2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedcharacteraffiliation",
            name="feed_feedch_last_co_4d9e81_idx",
        ),
        migrations.RemoveField(
            model_name="feedcharacteraffiliation",
            name="last_confirmed_at",
        ),
        migrations.RemoveField(
            model_name="feedcharacteraffiliation",
            name="source",
        ),
        migrations.AddIndex(
            model_name="feedcharacteraffiliation",
            index=models.Index(
                fields=["created_at"],
                name="feed_feedch_created_91a4b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedcharacteraffiliation",
            index=models.Index(
                fields=["esi_checked_at"],
                name="feed_feedch_esi_che_7c3d19_idx",
            ),
        ),
    ]
