# Generated by Django 5.1.15 on 2026-06-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_remove_source_add_esi_checked_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedcharacteraffiliation",
            old_name="militia_faction_id",
            new_name="faction_id",
        ),
    ]
