# Generated by Django 5.1.15 on 2026-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feed",
            "0006_rename_militia_faction_id_feedcharacteraffiliation_faction_id",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedSystemContestedSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                ("contested_percent", models.FloatField()),
                (
                    "occupier_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "victor_faction_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="feedcharacteraffiliation",
            new_name="feed_feedch_created_f8613c_idx",
            old_name="feed_feedch_created_91a4b2_idx",
        ),
        migrations.RenameIndex(
            model_name="feedcharacteraffiliation",
            new_name="feed_feedch_esi_che_87b986_idx",
            old_name="feed_feedch_esi_che_7c3d19_idx",
        ),
        migrations.AlterField(
            model_name="feedevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fleet_active", "Fleet active"),
                    ("killmail_batch", "Killmail batch"),
                    ("militia_joins", "Militia joins"),
                    ("contested_change", "Contested change"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="feedsystemcontestedsnapshot",
            index=models.Index(
                fields=["solar_system_id", "-captured_at"],
                name="feed_feedsy_solar_s_00adec_idx",
            ),
        ),
    ]
