# Generated by Django 5.1.15 on 2026-06-20 16:09

from django.db import migrations, models


def purge_militia_joins_data(apps, schema_editor):
    FeedEvent = apps.get_model("feed", "FeedEvent")
    FeedRollupConfig = apps.get_model("feed", "FeedRollupConfig")
    FeedEvent.objects.filter(kind="militia_joins").delete()
    FeedRollupConfig.objects.filter(rollup_code="militia_joins").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_feed_system_contested_snapshot"),
    ]

    operations = [
        migrations.RunPython(
            purge_militia_joins_data, migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name="FeedMilitiaFirstSeen",
        ),
        migrations.AlterField(
            model_name="feedevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fleet_active", "Fleet active"),
                    ("killmail_batch", "Killmail batch"),
                    ("contested_change", "Contested change"),
                ],
                max_length=32,
            ),
        ),
    ]
