# Generated by Django 5.1.15 on 2026-07-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_remove_militia_first_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCapitalPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "killmail_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("solar_system_id", models.BigIntegerField()),
                ("distance_ly", models.FloatField()),
                (
                    "discord_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
