# Generated by Django 5.1.15 on 2026-07-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0010_feedr2z2cursor_dual_cursors"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCapitalAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solar_system_id", models.BigIntegerField(db_index=True)),
                ("system_name", models.CharField(max_length=64)),
                ("distance_ly", models.FloatField()),
                ("capitals", models.JSONField(default=list)),
                ("kills", models.JSONField(default=list)),
                ("discord_messages", models.JSONField(default=list)),
                ("last_activity_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.AddField(
            model_name="feedcapitalping",
            name="alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pings",
                to="feed.feedcapitalalert",
            ),
        ),
    ]
