# Generated by Django 5.2.16 on 2026-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0015_feed_event_link_on_delete_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedmonitoredsystem",
            name="source",
            field=models.CharField(
                choices=[
                    ("fw_warzone", "FW warzone (seeded)"),
                    ("manual", "Manual admin addition"),
                    ("campaign", "Campaign theater"),
                ],
                default="fw_warzone",
                max_length=16,
            ),
        ),
    ]
